### ISSUE TITLE
Parse.User.current() replacement in query

### ISSUE THREAD

**Issue by leoskye** [ParsePlatform/Parse-SDK-JS#1]
I'm seeing this error when I run my React Native app:

My observe() function:

```
  observe: function() {
    return {
      user: ParseReact.currentUser,
      current: new Parse.Query('Idea')
        .equalTo('User', Parse.User.current())
        .equalTo('State', Config.IDEA_STATES[Config.CURRENT]),
    };
  },
```

![image](https://cloud.githubusercontent.com/assets/1527177/9951673/5155d0a2-5d7e-11e5-9b93-10c1802b9d23.png)

I tried using Parse.User.currentAsync(), but that returns a Promise instead of Parse.Object. How do I filter by current user in my subscription query?

**Comment by andrewimm** [comment]
Questions and issues related to the Parse+React library should be reported on that library's repo: https://github.com/ParsePlatform/ParseReact
