### ISSUE TITLE
including array of pointers returns null, while the object exists

### ISSUE THREAD

**Issue by geo8bit** [ParsePlatform/Parse-SDK-JS#103]
In a class named "Orders" I have an array of pointers, called "items", pointing to class "Products". When I fetch an order and include "items", some of the products return null, although I can see them in the data browser and they are returnec correctly when I query directly to Products.

This is my testing code:

```javascript
var query = new Parse.Query("Orders");
query.equalTo("objectId", "****");
query.include("items");
query.find({
	success: function(results) {
		console.log(results[0].get("items"))
	},
	error: function(error) {
		alert("Error: " + error.code + " " + error.message);
	}
});
```

returns:

```
[ 
  { _objCount: 3, className: 'Products', id: '****' },
  { _objCount: 6, className: 'Products', id: '****' },
  null ]
```

**Comment by wangmengyan95** [comment]
Hi @geo8bit, I test the latest SDK in node/browser environment and unfortunately I can not repo this issue. In your case, could you provide the following information to us:
1. The SDK version you are using
2. Your environment (node or browser)
3. Whether you can repo it consistently
4. Whether you can repo it through our [REST api](https://www.parse.com/docs/rest/guide#queries)
Thanks
