### ISSUE TITLE
object.get(key) returning undefined in Parse.Cloud.afterDelete

### ISSUE THREAD

**Issue by UberJason** [ParsePlatform/Parse-SDK-JS#105]
Greetings,

I'm new to the JavaScript SDK so I hope I'm doing something stupid.

I have an afterDelete hook where I would like to check if a recipe has any "ScheduleItems" pointing to it. If it has none, and it's been flagged for deletion, I'd like to delete the recipe. Here's the code snippet:

```
Parse.Cloud.afterDelete("ScheduleItem", function(request, response) {
	var recipe = request.object.get("recipe");
	query = new Parse.Query("ScheduleItem");
	query.equalTo("recipe", recipe);
	query.count({
		success: function(count) {
			if(count == 0) {
				if(recipe.get("deleted") === true) {
					// There are no more scheduleItems pointing to this recipe, so we can delete it
					recipe.destroy({
						success: function(recipe) {
							console.log("Success deleting recipe");
						},
						error: function(recipe, error) {
							console.error("Error deleting recipe " + error.code + ": " + error.message)
						}
					})
				}
				else {
					console.log("recipe[\"deleted\"] = " + recipe.get("deleted"));
				}
			}
		},
		error: function(error) {
			console.error("Error " + error.code + " : " + error.message + " when getting scheduleItem count.");
		}
	});
});
```

Here's the console output:
```
I2015-12-02T03:56:31.227Z]v19 after_delete triggered for ScheduleItem for user NWbY9XFrCz:
  Input: {"object":{"createdAt":"2015-12-02T03:55:55.621Z","date":{"__type":"Date","iso":"2015-11-30T05:00:00.000Z"},"objectId":"hf7djmsYgD","recipe":{"__type":"Pointer","className":"Recipe","objectId":"8QrTMjYhvJ"},"updatedAt":"2015-12-02T03:55:55.658Z"}}
  Result: Success
I2015-12-02T03:56:31.341Z]recipe["deleted"] = undefined
```

As you can see, the value of recipe.get("deleted") is coming back undefined, even though that flag is definitely set (I've verified by checking the appropriate data table on parse.com). I also found [these](http://stackoverflow.com/questions/32667395/parse-request-object-getkey-always-returns-undefined) [two](http://stackoverflow.com/questions/32530832/parse-cloud-code-request-object-getkey-return-always-undefined) StackOverflow links that suggest this may be a bug in the JavaScript SDK. But since I'm relatively new to the JavaScript SDK, I'd be happy to be doing something stupid. Can you please advise?

**Comment by mnazemi** [comment]
If you pay attention to the console output, you can see that your `recipe` object is only a **pointer** to an object in your `Recipe` class:

    "recipe":{"__type":"Pointer","className":"Recipe","objectId":"8QrTMjYhvJ"}

If you want to access the given `Recipe` object whihc is being pointer to, you either need to fetch that object or you can user the `include` method in your query to expand the pointer with the `Recipe` data automatically.

**Comment by UberJason** [comment]
Thank you! How would I use the include method to get the Recipe data in this case, since I'm actually getting the recipe pointer from the request object? It's not being queried for. So would I have to fetch the object?

**Comment by mnazemi** [comment]
Well you are doing a `count` query, but when you do a normal `find` query you can easily add an extra line `query.include("recipe");` which will automatically expands the pointer in your parent object. Alternatively you can fetch the object directly like this:
```javascript
var object= new Parse.Object("Recipe");
object.id = recipe.id;
object.fetch().then( function(data) {
    // success
}, function(error) {
   // error
});
```

**Comment by UberJason** [comment]
For a normal ````find```` query, yep, that ````include()```` method would be great. But in this case, the ````count```` query is a query for ````ScheduleItems````, and not the ````recipe```` object that came from ````request.object````. So I suppose I'll have to do the fetch in this situation. In any case, thank you for helping me see my error!
