### ISSUE TITLE
Cannot create an object using Parse.Object(Parse.user) 

### ISSUE THREAD

**Issue by mohnazemi** [ParsePlatform/Parse-SDK-JS#106]
Hi guys,
I am using the `objectId` of a User object to build a Parse object and fetch its data on the Cloud. Here is my code which does not work:

```javascript
var user = new Parse.Object(Parse.User);
user.id = "abcd1234"
user.fetch().then( function(data) {
    // success
}, function(error) {
   // error, this always gets called with error code 101
});
```
The code above always returns this error message: `code 101, object not found for get`
Now if you simply change the first line to the following, it works fine!
```javascript 
var user = new Parse.Object("_User");
``` 
Is this a bug or am I missing something?
Thanks,

**Comment by andrewimm** [comment]
Why not just write
```
var user = new Parse.User()
```

That is how Parse.User objects are intended to be initiated.
