### ISSUE TITLE
Delete ParseFile function fails

### ISSUE THREAD

**Issue by progrmor** [ParsePlatform/Parse-SDK-JS#107]
I'm having serious issues with deleting a Parsefile bound to a ParseObject using Javascript SDK.
This method fails with code 141 and in Log info window on Parse.com it logs the "failed" response.
I really wish Parse had an easier method for deleting images/files. 

```javascript
Parse.Cloud.define("deleteFile1", function(request, response) {
  Parse.Cloud.httpRequest({
       method: 'DELETE',
       url: 'https://api.parse.com/1/files/image1.png',
       headers: {
        "X-Parse-Application-Id": "********",
        "X-Parse-REST-API-Key" : "********"
       },
       success: function(httpResponse) {
            console.log('Delete succeeded  ' + httpResponse.text);
                response.success();
       },
       error: function(httpResponse) {
                response.error("failed");
       }
       });
}); 
```

**Comment by mnazemi** [comment]
Because you should use your Master key instead of your REST key. See: http://stackoverflow.com/questions/34001172/delete-parsefile/34003797#34003797

**Comment by progrmor** [comment]
I have tried with the Master key as well. Same thing occurs.
