### ISSUE TITLE
Master privilege is not graned when calling a Cloud function using the Master key

### ISSUE THREAD

**Issue by mohnazemi** [ParsePlatform/Parse-SDK-JS#108]
Hi guys,

I have a cloud function which I call using `cURL` command with my Master key. Inside the function `request.master` is always true but when I want to perform actions that requires Master privilege, like doing a query on the Session class, I get errors.
I realised that I must also add `Parse.Cloud.useMasterKey()` to my code in order to raise the privilege to Master even though the Cloud function is being called with the Master key. Is this an expected behaviour ?
Regards,

**Comment by andrewimm** [comment]
Yes, this is by design. Otherwise it would be difficult to rely cloud code that relies on session token or public privileges. This is covered in the documentation.

**Comment by andrewimm** [comment]
`request.master` tells you whether the method was called with the master key, but does not affect the default behavior of cloud code.
