### ISSUE TITLE
Save object whit Parse.Cloud.beforeSave cause ACL become null

### ISSUE THREAD

**Issue by flessard** [ParsePlatform/Parse-SDK-JS#109]
I think i find a bug whit Parse JS v1.6.7. 

If you have a PFObject on you application and you change ACL of this object and you save it and you modifiy this object whit a Parse.Cloud.beforeSave, if you try to get ACL again on you application, you will get null.

If you skip the Parse.Cloud.beforeSave, work fine.

Work fine whit Parse JS v1.5.0 no bug.

**Comment by andrewimm** [comment]
Can you provide a code sample that reproduces this bug?

**Comment by flessard** [comment]
Sure, 
See : https://jsfiddle.net/9m6bfraj/4/

Thanks !

**Comment by wangmengyan95** [comment]
Hi @flessard, I test with your code and it works fine for me. I test with parse js SDK in browser and node environment to trigger the cloud code. Could you give us your test environment?

**Comment by flessard** [comment]
Hi wangmengyan95,

I juste create a new app on parse and i update my jsfiddle. Juste run the jsfiddle and check browser console.

https://jsfiddle.net/9m6bfraj/8/

**Comment by flessard** [comment]
Hi @wangmengyan95 , Did you try my jsfiddle ? Are you able to reproduce this bug ?

**Comment by wangmengyan95** [comment]
Ho @flessard, sorry I missed your last reply. I will take a look. Thx!

**Comment by wangmengyan95** [comment]
Hi @flessard, I can repo this issue. I will try to figure our where is the problem. Thx!

**Comment by wangmengyan95** [comment]
PR #123
