### ISSUE TITLE
Uncaught TypeError: provider.getAuthType is not a function

### ISSUE THREAD

**Issue by limulidae** [ParsePlatform/Parse-SDK-JS#11]
_linkWith	@	parse-latest.js:7350
success	@	parse-latest.js:7370
exports.default.init._ParseUser2.default._registerAuthenticationProvider.authenticate.FB.login.scope	@	parse-latest.js:504
window.FB.v.__wrapper	@	sdk.js:98
window.FB.ea.permissions.oauth.transform	@	sdk.js:118
window.FB.ia.prepareCall	@	sdk.js:118
o	@	sdk.js:119
window.FB.k.provide.login	@	sdk.js:120
(anonymous function)	@	sdk.js:100
(anonymous function)	@	sdk.js:98
authenticate	@	parse-latest.js:501
_linkWith	@	parse-latest.js:7360
_logInWith	@	parse-latest.js:7972
logIn	@	parse-latest.js:599
$scope.login	@	welcome.js:15
fn	@	VM27794:4
(anonymous function)	@	ionic.bundle.js:57514
parent.$get.Scope.$eval	@	ionic.bundle.js:24673
parent.$get.Scope.$apply	@	ionic.bundle.js:24772
(anonymous function)	@	ionic.bundle.js:57513
eventHandler	@	ionic.bundle.js:12098
triggerMouseEvent	@	ionic.bundle.js:2865
tapClick	@	ionic.bundle.js:2854
tapMouseUp	@	ionic.bundle.js:2927
.

**Comment by jrmce** [comment]
Getting this as well when using Parse.FacebookUtils.logIn

**Comment by jrmce** [comment]
To provide some additional details, after calling Parse.FacebookUtils.logIn, Parse.User.linkWith is being called once successfully with the provider parameter set correctly to "facebook". Once the Facebook Login popup closes, it looks like Parse.User.linkWith is called a second time, but the provider parameter is set to Window. I can't really figure out why it's being called a second time, but wanted to share in case it helps.

My use case is not unique, it's simply calling Parse.FacebookUtils.logIn('public_profile, email', {...})

I'm also noticing that Parse.FavebookUtils.logIn is not returning a promise, it's instead looking for a success callback. Is that correct?

**Comment by janicduplessis** [comment]
This error was fixed in #3. However, the package has not been updated on npm since then.

**Comment by limulidae** [comment]
please let use know which release has this fix. thank you.

**Comment by jrmce** [comment]
@janicduplessis thanks!!

**Comment by andrewimm** [comment]
1.6.4 has been released on npm
