### ISSUE TITLE
Manage sessions in Cloud Code

### ISSUE THREAD

**Issue by franexposito** [ParsePlatform/Parse-SDK-JS#119]
Hello,
I'm going to try to explain my problem the clearest possible way.
I'm using the jssdk 1.6.7.
In order to manage the sessions I use parse-express-cookie-session:
```
var parseExpressHttpsRedirect = require('parse-express-https-redirect');
var parseExpressCookieSession = require('parse-express-cookie-session');
app.use(parseExpressHttpsRedirect());
app.use(express.bodyParser());
app.use(express.methodOverride());
app.use(express.cookieParser('mykey'));
app.use(parseExpressCookieSession({
  fetchUser: true,
  cookie: { maxAge: 3600000 }
}));
app.post('/login', function(req, res) {
  Parse.User.logIn(req.body.username, req.body.password).then(function() {
    res.send(true);
  }, function(error) {
    res.send(error);
  });
});
```
When I do login from the website, the cookie gets created without any problem. When an user access to an url such as /prueba I retrieve the user with:
```
app.get('/prueba', function(req, res) {
  res.send(Parse.User.current());
});
```
The problem is when on Javascript I call the cloud method on the client-side, Parse.User.current() is always null and I can't get the currentUser. Any ideas?

**Comment by wangmengyan95** [comment]
Hi @franexposito, I am sorry but I still do not understand your problem clearly.
1. Which platform are you using the SDK, client, node? I assume it is node.
2.  I check npm  `parse-express-cookie-session`, it is a third party library which has not been updated for a year. Not sure it still works well with our current SDK.
3. You mention you call cloud method on the client-side, but I do not see any description or codes about it. It seems the codes are all related to node server side. Maybe give us some details how you do that?

**Comment by franexposito** [comment]
Hi @wangmengyan95 

When I do for example (Client-side):

```
Parse.Cloud.run("getNumbersWords", {id: country, userc: cUser}, {
  success: function(count) {
    numberWords = count;
    changePalabra();
  },
  error: function(error) {
    console.log(error);
   }
});
```

My getNumbersWords is (Server-side):

```
Parse.Cloud.define('getNumbersWords', function (request, response) {
  console.error(request);
  var query = new Parse.Query("Pais");
  query.get(request.params.id).then( function(pais) {
    var queryP = new Parse.Query('Palabras');
    queryP.equalTo('idioma', pais.get('idioma').toLowerCase());
    return queryP.count();
  }).then( function(count) {
    response.success(count);
  }, function(error) {
    response.error({'resp': error.code, 'message': error.message});
  });
});
```

Parse.User.current(), request.user and request.params.sessionToken are null.

**Comment by andrewimm** [comment]
@franexposito it sounds like the issue is because you are not setting the current user on the client side (the user's browser). When communicating with your cloud code (the express server), you are using cookies to manager users. However, your JS SDK on the client side is not aware of this current user without you explicitly setting it. When you call a cloud job from your client, it does not run your express code, and does not get the current user from the cookie. It is depending on the client-side SDK to pass the credentials of the current user, but these are not sent because the client does not know about the current user.

I hope that made some sense. I'd recommend that when you render your web pages in express, you include a `<script>` tag that calls `.become()` with the current session token, so that your client SDK can also act as the current user.

**Comment by franexposito** [comment]
Thanks @andrewimm, I found the solution:

Ok so after a lot of digging I have worked it out. First you need to do something like this in your client-side:

```
Parse.User.logIn(usern, pass, {
  success: function(user) {
    var sess = user.get("sessionToken");
    $.ajax({
      type: 'POST',
      dataType: "json",
      data: {sessionToken: sess},
      url: "/login",
      success: function(resp) {
        console.log(resp)
      },
      error: function(error) {
        console.log(error);
      }
    });
  },
  error: function(error) {
    console.log(error);
  }
});
```

In your server-side, your /login post must be this:

```
app.post('/login', function(req, res) {
  var sessionToken = req.body.sessionToken;

  Parse.User.become(sessionToken).then(function (user) {
    res.send(true);
  }, function (error) {
    console.log(error);
    res.send(false);
  });
});
```

Et voilà. The "become" method puts a cookie in the browser.

**Comment by atom2ueki** [comment]
@franexposito I usually use Parse.User.become at client side to set user cookies
