### ISSUE TITLE
ParseUser._linkWith call to provider.authenticate need to reject promise on error

### ISSUE THREAD

**Issue by taivo** [ParsePlatform/Parse-SDK-JS#12]
At approx. at line 100 in ParseUser.js, these lines
```
this._linkWith(provider, opts).then(() => {
            promise.resolve(this);
          });
```
recursively call `_linkWith` and only handle the smooth sailing case. However, it's still possible for this error to happen `{ code=208,  message="Another user is already linked to this facebook id."}`. A `promise.reject` call is needed to propagate the error message.

**Comment by andrewimm** [comment]
Should be fixed in #34, it'll go out in v1.6.5
