### ISSUE TITLE
Error not caught through promises

### ISSUE THREAD

**Issue by cfoulston** [ParsePlatform/Parse-SDK-JS#120]
Hi, maybe I'm misunderstanding error handling with Parse Promises, but this is never caught:

```javascript
Parse.Cloud.define("testError", function (request, response) {

	request.user.fetch().then(function (user) {

		throw "Test Error";

	}).then(function () {

		console.log("Got success");

		response.success(true);

	}, function (error) {

		//This never happens
		console.log("Got error: " + error);

		response.error(error);
	});
});
```
In my client I receive the error: ```Parse.ParseException: Uncaught Test Error```

How do you handle errors in this way, especially for when an exception is raised at an unknown point?

**Comment by andrewimm** [comment]
Hi @cfoulston, please read more in #57.

Parse Promises, when they were first implemented, were based on the Promises/A spec (the more modern A+ spec had not been introduced yet). The differences between the two are negligible, with one exception (no pun intended): A+ promises will catch exceptions and not propagate them, A promises will propagate exceptions upwards, stopping execution. From 1.6.8 onwards, we've allowed users to explicitly enable A+ compatibility, and it will be the default in 1.7 and beyond.
