### ISSUE TITLE
Changelogs and releases

### ISSUE THREAD

**Issue by TylerBrock** [ParsePlatform/Parse-SDK-JS#121]
Hey I was just wondering if there was a reason that 1.6.7 is the latest available on the website but we are now at 1.6.10 on NPM.

There are also no change logs for 1.6.8-10 on the download page either: https://parse.com/docs/downloads

As a result I find myself wondering what changed between 1.6.9 -> 1.6.10 and I'm sure others are wondering the same about 1.6.8 and 1.6.9 as well.

**Comment by andrewimm** [comment]
@TylerBrock we're moving the changelogs to live here on GitHub. Just look at the releases page. I released 1.6.10 at midnight last night, and neglected to put up the changelogs before I turned in. I'll put it up right now.

As for the web stuff, we slipped a bit leading up to the launch of the new web site, but I put an internal PR out last night to make sure .8, .9, and .10 get up there asap.

**Comment by TylerBrock** [comment]
As of now there is no 1.6.10 release so I can't do that...

**Comment by Rauno56** [comment]
What about older releases(from 1.3.x)? I saw them somewhere while ago...
