### ISSUE TITLE
Handling Dev/Staging/Production environments

### ISSUE THREAD

**Issue by cfoulston** [ParsePlatform/Parse-SDK-JS#125]
Hi, wanted to start a conversation about how to handle switching between dev, staging and production environments. Currently I see no elegant solution to this problem.

My company is building an app that desperately requires this functionality.

1. We build front end client, update cloud code, change data and class schema, background jobs (Dev)
2. Push everything (cloud code, data, class schema, jobs) to Staging
3. Client validates on Staging
4. Push Staging to Production, release updated front end client (if necessary).

Cloning apps is not possible since doing so generates new application ids meaning client would be pointing to invalid app id.

Exporting database seems like the only option. But can you export the entire database and then re-import to a new app?

How are other people handling this?

Can we use the REST Api to achieve this?

**Comment by cfoulston** [comment]
Still struggling with this.

I've managed to create some scripts using the RestAPI to delete/change schema and objects from a Parse App. But now, transferring the data across from a Dev to Staging app is looking like an impossibility.

The simple fact that I can't create an object with an id prevents this system from working. All pointers are lost as those objectId's don't exist. The only option I see is after creating an object, I create a hashmap between the previous id and new id. Then when saving any object, check this hash, and update the reference id for the pointer being saved. This is tricky though, Objects that have references to them need to be saved before all other objects pointing to them.

So now I'm faced with manually importing classes :(

Any chance you guys are working on a bulk import?

**Comment by andrewimm** [comment]
This should be easily managed with `parse-server`.
