### ISSUE TITLE
Cloud code - calling signUp on anonymous user doesn't make user non-anonymous

### ISSUE THREAD

**Issue by alexblack** [ParsePlatform/Parse-SDK-JS#13]
I'm using this cloud function to upgrade a user from anonymous to real, and then request a password reset, on app https://www.parse.com/apps/invoice-maker-dev

After doing this, I then login with that user on an AndroidDevice, then call ParseAnonymousUtils.isLinked and expected the result to be false (real) but I get true (anonymous).

Looking at the ParseUser in the parse console I see that the user is still anonymous.  If I follow a similar process from Android code, the user doesn't remain anonymous (the desired result).

See user bF2wHKAFDM in the screenshot, it does have the username set from the code below, but still is an anonymous user.

What do I need to do to make this user not anonymous?

Thanks!  Alex

```javascript
Parse.Cloud.define('requestPasswordResetInBackgroundAnonymous', function(request, response) {
  var googleAccountQuery = new Parse.Query(GoogleAccount);
  var email = request.params.email;

  if (!email || !email.length) 
    response.error('Email parameter required');

  Parse.Cloud.useMasterKey();

  googleAccountQuery.equalTo('name', email);
  googleAccountQuery.ascending('updatedAt'); // in case there are multiple
  googleAccountQuery.first({    
    success: function(googleAccount) {
      if (googleAccount) {
        var account = googleAccount.get("account");

        var userQuery = new Parse.Query(Parse.User);
        userQuery.equalTo('account', account);
        userQuery.ascending('updatedAt');
        userQuery.first({
          success: function(user) {
            if (user) {
              user.setUsername(email);
              user.setPassword('Eq54mY914Tt4:2U7WIf28K+o4483xi3Y');
              user.signUp(null, {
                success: function() {
                  Parse.User.requestPasswordReset(email, {
                    success: function() {
                      response.success();
                    },
                    error: function(error) {
                      response.error('requestPasswordReset failed: ' + error.code + ', ' + error.message);
                    }
                  });
                },
                error: function(user, error) {
                  response.error('signup failed: ' + error.code + ', ' + error.message);
                }
              });
            } else {
              response.error('No ParseUser found for account: ' + account.id);              
            }
          },
          error: function(error) {
            response.error('Error searching for ParseUser by account' + account.id + ': ' + error.code + ', ' + error.message);
          }
        });
      } else {
        response.error('No GoogleAccount found with email: ' + email);
      }
    },
    error: function(error) {
      response.error('Error searching for GoogleAccount with email' + email + ': ' + error.code + ', ' + error.message);
    }
  });  
});
```

![screenshot 2015-09-23 13 03 30](https://cloud.githubusercontent.com/assets/148930/10057175/abbe38c6-61f3-11e5-8b8f-733e443c5f3d.png)

**Comment by alexblack** [comment]
Bump :)

**Comment by stanleyw** [comment]
Hi Alex, Based on the info you provided, its unclear to me whether the user didn't become non-anonymous because the logic prior to the signUp call failed.  Do you have some logs demonstrating that signUp was actually executed?

Could you try removing all code except for just set username, set password, and signUp to help narrow down the range of possibilities?  If you can repro with this simpler case, please also provide info like SDK version number.  Thanks!

**Comment by alexblack** [comment]
Hi Stanleyw, yes the fact that the function succeeded without errors would be logged in the logs at parse.  It looks like it doesn't let me go back that far though.  

Another way I know it succeeds because reset password emails get sent out.

**Comment by stanleyw** [comment]
@alexblack What version of JS SDK did you use?

**Comment by alexblack** [comment]
@stanleyw 1.4. I'll retest on Monday with the latest.

**Comment by stanleyw** [comment]
I dug into this further, here is what I've found:

* Looks like the Parse backend has always left the anonymous authData unchanged when an anonymous user gets upgraded to a normal user via setting username/password.   You can reproduce this by calling the Parse REST API directly to save the user.  We can't really change this backend behavior because we don't know whether anyone relies on this today.

* The JS SDK currently does not support anonymous user manipulation (i.e. Parse.AnonymousUtils doesn't exist), so there is no JS `unlink` method.  However, if you really want to unlink the user from the anonymous authData, you can use the REST API (https://www.parse.com/docs/rest/guide#users-unlinking).  The Cloud Code equivalent is:

```
	Parse.Cloud.httpRequest({
	  method: 'PUT',
	  url: 'https://api.parse.com/1/users/' + yourUser.id,
	  body: '{ "authData": { "anonymous": null }}',
	  headers: {
	  	'Content-Type': 'application/json',
	  	'X-Parse-Application-Id': Parse.applicationId,
	  	'X-Parse-Master-Key': Parse.masterKey
	  }
	}).then(function(httpResponse) {
	  console.log(httpResponse.text);
	}, function(httpResponse) {
	  console.error('Request failed ' + httpResponse.status + ' ' + httpResponse.text);
	});
```

Let us know whether this workaround works!

**Comment by alexblack** [comment]
Hi @stanleyw thanks for looking into it. Is it a bug then?

I will try the work around to try to fix up the signUp call.

**Comment by alexblack** [comment]
Currently I have this code in my Android app to work around the bug:

```
    final ParseUser user = ParseUser.getCurrentUser();
    // hack: if we use the cloud function requestPasswordResetInBackgroundAnonymous to upgrade an anonymous user
    // then Parse still thinks its anonymous, so lets check the username and see if its set to an email address (which we would have done)
    // see: https://github.com/ParsePlatform/Parse-SDK-JS/issues/13
    if (!ParseAnonymousUtils.isLinked(user) || Fmt.isValidEmail(user.getUsername()) ) {
```

**Comment by stanleyw** [comment]
Thanks for the new info, dug into this more and realized that our iOS and Android SDKs strip the authData client-side.  See https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParseUser.java#L429

We'll look into doing the same for the JS SDK.

**Comment by alexblack** [comment]
Great.
