### ISSUE TITLE
Cloud.code version vs JS SDK version 

### ISSUE THREAD

**Issue by jeveloper** [ParsePlatform/Parse-SDK-JS#131]
Hi 

There seems to be something at odds with two systems.

It appears that only 1.6.7 (at the time of writing) (cli 3.0.2) that works and allows for deployment
"parse": {
    "jssdk": "1.6.7"
  }

I have tried 1.6.12 which is a current JS SDK and an error happens with no message.

thanks

**Comment by andrewimm** [comment]
Looks like we had an issue that was deploying new SDKs to invalid version strings. Should be resolved now.
