### ISSUE TITLE
Using alternate Storage Controllers when localStorage is not available

### ISSUE THREAD

**Issue by delux75** [ParsePlatform/Parse-SDK-JS#132]
The user get a `QuotaExceededError` on Safari Mobile while Private mode is enabled and Parse try to use the local storage.

Apparently I found on Stackoverflow that Safari Mobile in Private mode does not allow local storage to be used at all.

**Source**: http://stackoverflow.com/questions/21159301/quotaexceedederror-dom-exception-22-an-attempt-was-made-to-add-something-to-st

Something needs to be done, because it's broken all the javascript.

**Comment by andrewimm** [comment]
Certain behaviors (like caching Config or persisting Installation IDs) depend on local storage. However, we know that this is an issue with Safari on Private Browsing, and so we allow developers to replace the Storage Controller at runtime.
How you do this depends on how you are using the SDK, but you can call `Parse.CoreManager.setStorageController()` and replace the one being used. If you do not need any sort of persistence features, I recommend either using the `StorageController.default.js` controller found in the npm module and this repo, or simply implementing a no-op controller yourself.

**Comment by delux75** [comment]
Thanks for the solution. I think it should be written somewhere that Safari Mobile in Private mode broke the local storage because I don't think it's well known and it's never easy to debug on Safari Mobile (even impossible if you don't have a Mac).

Or you could throw an alert or something like that :
```javascript
try { localStorage.test = 2; } catch (e) {
    alert('Local storage is disable...');
}
```

**Comment by andrewimm** [comment]
@delux75 I'll wrap the functionality of StorageController.browser.js to catch any exceptions. Even if it won't save anything to disk, it'll keep the SDK functional

**Comment by delux75** [comment]
That's a great solution imho.
