### ISSUE TITLE
Where are the docs for Parse.Op?

### ISSUE THREAD

**Issue by diegohaz** [ParsePlatform/Parse-SDK-JS#133]
Where can I find it? I'm trying to use this: https://parse.com/docs/js/api/classes/Parse.Object.html#methods_op

**Comment by andrewimm** [comment]
`Parse.Op` is not publicly documented, because at this time we do not expect developers to interact with them directly. Also, because they are not a public API, they may change at any time (in fact, we are considering a number of changes for them).

The code can be found in this repo though.
