### ISSUE TITLE
Parse Login GET method (security flag)

### ISSUE THREAD

**Issue by cornerolive** [ParsePlatform/Parse-SDK-JS#134]
Hi,

Hi see today that when I'm calling Parse.User.logIn method, the request Method is POST but in the request Payload I see the password of the user logged in and also I see this field: _method:"GET".

This is causing me a problem in Google Analytics because I see the url's when logIn because that GET post form:

    /?name=julian&lastname=bizot&email=julian@mail.com&password1=password&password=password

This is the request Payload:
            {"username":"mail@gmail.com","password":"password","_method":"GET","_ApplicationId":"xxxx","_JavaScriptKey":"xxx","_ClientVersion":"js1.6.7","_InstallationId":"xxxx"}

I use React and Formsy react component for the html part:

    <Formsy.Form onValid={this.enableButton} onInvalid={this.disableButton} ref="form">
      <Input
       layout= "vertical"
       name="email"
       ref="email"
       id="email"
       value={this.state.email}
       label={translate('form.email')}
       type="email"
       autoComplete="off"
       validations="isEmail"
       required />
       <Input
       layout= "vertical"
       name="password"
       ref="password"
       id="password"
       value={this.state.password}
       label={translate('form.password')}
       type="password"
       onClick={this.removeData}
       required />
       <div className="checkbox">
       <Checkbox
         layout= "vertical"
         name="remember"
         ref="checkbox"
         id="checkbox"
         onClick={this.handleChange}
         checked={this.state.isChecked}
         value={this.state.isChecked}
         label={translate('form.rememberMe')} />
       </div>
     <button className="btn-block btn btn-lg btn-primary" disabled={!this.state.canSubmit} onClick={this.submit}>{translate('form.enter')}</button>
    </Formsy.Form>

Thank you!

**Comment by andrewimm** [comment]
What problems is this causing you? Parse only uses this format when communicating with the Parse API, which should not be included in your google analytics.

**Comment by andrewimm** [comment]
Also, we have to send the password in the payload when the user is logged in. How else would we actually check that it's a valid password? It's sent over HTTPS from the same client that generated the password, so it's not a security issue.

**Comment by cornerolive** [comment]
That someone could intercept the plain password and also Google Analytics could ban us because of having security issues.

Also how come I can see this information in google analytics if it is not supposed to be sent there?

This is the snippet we're using to send data to analytics:

    <noscript><iframe src="//www.googletagmanager.com/ns.html?id=XXXXXX"
        height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
        <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','XXXXXXX');</script>

Thank you very much!

**Comment by andrewimm** [comment]
The password is not passed in plaintext, it's passed over HTTPS, so it cannot be intercepted.

It sounds like there is an issue with the forms library you are using; if you had a `<form>` tag with `method="get"`, submitting the form would reload your web page with all of the form's contents added as query parameters, which matches the GA URL you copied above. I recommend that when you submit your form, it prevents the browser from calling the default form action.

Closing, as this is not related to the Parse SDK.
