### ISSUE TITLE
Parse.Config only accessible with Masterkey?

### ISSUE THREAD

**Issue by ChristopherHeymann** [ParsePlatform/Parse-SDK-JS#135]
I am not sure if this is intended or not, but it's weird that I can access my config parameters on my client SDK's(iOS, Android), but not on CloudCode without the MasterKey. This is a real problem, since some of my CloudCode is on Heroku and everything works without the MasterKey, so I don't intend to store it there. 
Is this a bug? Is this intended? What would be the reason? 

Some users on stackoverflow reported the same: http://stackoverflow.com/questions/31410235/in-cloud-code-seems-impossible-to-use-parse-config-get-with-express-is-it-corr/33628586#33628586

**Comment by andrewimm** [comment]
This is not intended behavior. If I can reproduce this issue, I'll report back here.

**Comment by andrewimm** [comment]
@ChristopherHeymann can you provide code that reproduces this issue for you? I'm not seeing it.

keep in mind that Parse.Config.get() is asynchronous, as it is fetching from the API. If the cloud function ends before it has been fetched, you will not see a callback.

**Comment by ChristopherHeymann** [comment]
@andrewimm , big sorry...forgot to use that beast asynchronously. >.>
Thank you for your time, all the best!
