### ISSUE TITLE
Get the particular object that was added into an array and access it on afterSave

### ISSUE THREAD

**Issue by srameshr** [ParsePlatform/Parse-SDK-JS#137]
In my collection called ```A``` I have a ```column``` ```X``` that stores an array of ```User``` ```Pointers```.
That is:
```
[
  {"__type":"Pointer","className":"_User","objectId":"nP1VjrzfhY"},
  {"__type":"Pointer","className":"_User","objectId":"skdfjk343kf"},
 ...
]
```

Each time a new ```User``` pointer, is pushed and saved, I would want to access the <b>item that was pushed</b> in my ```afterSave``` definition. Is there any way to access this in ```request.object```?

**Comment by srameshr** [comment]
Cant find this on docs. May be I should do just send a req to my server and and then call request.success(data) inside the main cloud code and not on after save?

**Comment by srameshr** [comment]
@parse-github-bot Is there any strict rule, that enforces ```addUnique``` will push an object to the end of the array?

**Comment by andrewimm** [comment]
From the docs (https://parse.com/docs/js/guide#objects-arrays): "addUnique add the given object only if it isn't already contained in an array field. The position of the insert is not guaranteed."

When using cloud code, you can compare the before and after states in a beforeSave hook, but not an afterSave hook. If you were using our webhooks service with an external server (like an app hosted on Heroku), you would be able to access the before state in the payload we send.

**Comment by srameshr** [comment]
Why is position of insert not guaranteed? Is it not just like regular arrays?

**Comment by andrewimm** [comment]
It's not supported on the backend; `addUnique` is not like a `push` on an array. You can trace this back to the underlying Mongo DB method, `$addToSet`, which does not guarantee order of the result. You may find in practice that nearly every time, the item is pushed onto the end of the array, but you cannot rely on this behavior in your code.

**Comment by srameshr** [comment]
Thanks! I think I understand now.
