### ISSUE TITLE
Twitter login

### ISSUE THREAD

**Issue by olivierlesnicki** [ParsePlatform/Parse-SDK-JS#138]
Enable to call _linkWith('twitter', authData)
As I'm receiving the following error: `authenticate.provider` is not an object

Is Twitter login still supported? (consumer key has been added to my parse dashboard correctly)

**Comment by andrewimm** [comment]
Twitter login has never been supported by the JS SDK -- Twitter only provides login libraries for iOS and Android. It does not provide a client-side web popup in the style that FB does, so we can't do login from JavaScript clients.
