### ISSUE TITLE
need ParseObject.Revert Method

### ISSUE THREAD

**Issue by yutin1987** [ParsePlatform/Parse-SDK-JS#141]
_clearPendingOps method should is public method, maybe it name is Parse.Object.revet()

When obj.set('plan', 70) ...
and then user can undo that change, we only need call revet() method

**Comment by andrewimm** [comment]
Appreciate the suggestion. We'll consider adding this functionality to the API.

**Comment by yutin1987** [comment]
@andrewimm  Thanks, ^^
so far so I have been a direct call to _clearPendingOps Function.

**Comment by andrewimm** [comment]
@yutin1987 we have this functionality in iOS and Android, so we'll implement it here under the public instance method `.revert()`.

**Comment by andrewimm** [comment]
This will be added to the 1.7.0 release. Changes in 7c16dee0f90a6d85bb409851de86107a04007c06

**Comment by yutin1987** [comment]
:+1: :wave:
