### ISSUE TITLE
When creating a relationship between an existing object A and a new one B and saving B, it's also saving A for no reason

### ISSUE THREAD

**Issue by delux75** [ParsePlatform/Parse-SDK-JS#142]
So I'm creating a relationship between an existing object `post` and a new object `myComment` like so:

```javascript
var post = new Post();
post.id = "1zEcyElZ80";

var myComment = new Comment();
myComment.set("parent", post);
```

When I'm run a `mycComment.save();` the framework runs a batch trying to save `post` for no reason. I just want to create a relationship between `myComment` and `post` and saving `myComment`. Because after my CloudCode verification on `Post` objects throw me the error that my object attributes are empty...

**Comment by andrewimm** [comment]
This shouldn't be the case. Does your `Post` object have any additional changes that happen in its constructor (such as setting initial attributes?) If so, it would be marked as `dirty`, and the client would attempt to save it. I'll need more of your code to actually reproduce this bug.

In the meantime, I've added a test at https://github.com/ParsePlatform/Parse-SDK-JS/blob/master/src/__tests__/ParseObject-test.js#L986 which covers this case.

**Comment by typhonrt** [comment]
This is an issue in Backbone-ES6 being tracked here:
https://github.com/typhonjs/backbone-parse-es6/issues/5

Andrew, you can close this issue. Cheers..
