### ISSUE TITLE
Make Facebook login work with parse/node

### ISSUE THREAD

**Issue by jordi12100** [ParsePlatform/Parse-SDK-JS#145]
I'm getting an `The Facebook JavaScript SDK must be loaded before calling init.` error. I spend over an hour finding a workaround, but I don't see any way to include FB SDK in NodeJS. 

```
var Parse = require('parse/node');

const ParseID = '';
const ParseApiKey = '';

if (!Parse.applicationId) {
    Parse.initialize(ParseID, ParseApiKey);
    Parse.FacebookUtils.init(); 
}

module.exports = Parse;
```

**Comment by wangmengyan95** [comment]
Hi @jordi12100, the exception is because Facebook SDK does not support node environment. The Facebook SDK is meant to be used client-side only, since it cannot manage more than one user session simultaneously. If you really need this, you can use Facebook and parse REST API instead.

**Comment by andrewimm** [comment]
Closing, since there is no FB SDK for Node JS, and this is not something we can implement.
