### ISSUE TITLE
Third-party authentication using REST API from JavaScript

### ISSUE THREAD

**Issue by sraveh** [ParsePlatform/Parse-SDK-JS#147]
I am trying to code a new third-party service authentication provider (such as google and etc) and based on the REST API comments and the examples  I tried posting the following auth data: 

I removed the access token from the post for security reasons

{"authData":{"google":{"access_token":"VALID_ACCESS_TOKEN","expiration_date":"", "id":"111089308599922358192"} } }

But I got an error back from the server
{
    "code": 251,
    "error": "custom credential verification for auth service google failed"
}

Is there any kind of Parse platform limitation right now that is only allowing Facebook, Twitter and Anonymous as authentication service type?

Thanks,
Simon

**Comment by andrewimm** [comment]
At the moment, authData has some level of validation on the server, and you can't implement your own auth providers. However, we are exploring the possibility of letting developers design their own auth providers, since this seems to be a good feature.

**Comment by andrewimm** [comment]
This should be possible to implement with `parse-server`
