### ISSUE TITLE
Dot notation can only be used on objects

### ISSUE THREAD

**Issue by srameshr** [ParsePlatform/Parse-SDK-JS#148]
How to do a ```query.equalTo``` on a nested JSON object?

```authData```: ```{"facebook":{"access_token":"token","expiration_date":"2016-02-28T09:10:57.664Z","id":"1004913476994195"}}```

On this data, I am trying to access ```id``` like this:
```
var User = Parse.Object.extend('User');
var query = new Parse.Query(User);
query.equalTo('authData.facebook.id', someId); 
```
On trying this, I get an error: ```Dot notation can only be used on objects```. Is this not an object?

**Comment by wangmengyan95** [comment]
Hi @srameshr, I do not think we support this kind of query. You can use dot notation to do multiple levels include. But we do not support use dot notation in `equalTo ` query.
