### ISSUE TITLE
Scheduled job keeps failing

### ISSUE THREAD

**Issue by ParadimeWeb** [ParsePlatform/Parse-SDK-JS#149]
I have 1 job that is schedule to run every 10 minutes and it fails with message "Max concurrent job limit 1 reached".

Can someone explain why it is failing? It was working just a few hours before.

**Comment by andrewimm** [comment]
This suggests that your job is taking longer than 10 minutes to run, so scheduling another job 10 minutes later fails.

Issues on this GitHub repo are reserved for bugs or feature requests related to the JavaScript SDK -- if it is not specific to this SDK, we recommend seeking support through another channel.
