### ISSUE TITLE
Make promises A+ compliant

### ISSUE THREAD

**Issue by keeth** [ParsePlatform/Parse-SDK-JS#15]
For consistency with other promise libs I'm using it would be great if Parse promises were A+ compliant.

I see this has been anticipated, per

```
// We may want to expose this value at a later time, so that Promises/A+ style
// can be employed instead
var isPromisesAPlusCompliant = false;
```

Would be great if this was the default!

Thanks!

**Comment by andrewimm** [comment]
Stay tuned. I'll be posting a Discussion Issue shortly to discuss the future of `Parse.Promise`

That being said, `Parse.Promise` is almost entirely Promises/A+ compliant. Flipping that flag only changes the behavior around how a promises handles an exception

**Comment by roddylindsay** [comment]
A++ would compliance again

**Comment by TylerBrock** [comment]
Thanks for looking at this. Compatibility on this front goes a long way.

**Comment by stanleyw** [comment]
Andrew will open separate issue to discuss further.
