### ISSUE TITLE
Fetching user object by pointer

### ISSUE THREAD

**Issue by quisse** [ParsePlatform/Parse-SDK-JS#150]
*SDK version: 1.6.12*
*usage: browser*

I have a table with a column for a pointer to a user object (_User). The permissions for a user object are public read and read/write for owner

    var query = new Parse.Query(ClassName);
    query.find({
        success: function (row) {
            angular.forEach(rows, function(row){
                // here i am trying to retrieve the user object
            });
        }
    });

Now I want to retrieve the properties for each user per row. Other objects which are referenced with a pointer I can retrieve by using this:

    row.get('nameOfPointerColumn').fetch({
        success: function(object){
        console.log(object); // here is the object available.
    })
    // result of console.log
    // _objCount: 2
    // attributes: Object
    // className: "ClassName"
    // createdAt: Sun Dec 13 2015 17:51:43 GMT+0100 (Romance Standard Time)
    // id: "JbMFvhYJwK"
    // name: "this is a name"
    // updatedAt: Mon Dec 14 2015 14:35:59 GMT+0100 (Romance Standard Time)
    // __proto__: o

But for some reason when doing this for an user object, the only thing the success function returns is a pointer.

    row.get('user').fetch({
        success: function(object){
        console.log(object); // here is only a pointer available
    })
    // result of console.log
    // {_objCount: 8, className: "_User", id: "jKtCUYlceU"}

Then I saw some people using include on their query, but that doesn't work. It doesn't even work when I try including a object which is not a user.

**Comment by andrewimm** [comment]
Do you have extra class-level permissions on your User class?

**Comment by quisse** [comment]
The class level permissions are public read and write...

**Comment by wangmengyan95** [comment]
Hi @quisse, I test with both get and then fetch and include to retrieve a nested _User object and both of them works. In this case, is it possible for you to provide a sample project to repo this issue?

**Comment by quisse** [comment]
The issue was that i need to inject the custom user class with my get properties in my controller(angular). I already did this for the other classes but that was because i needed to add/edit object of those class types.
So this is solved. Thanks for your help and sorry for wasting your time with my stupid question @andrewimm & @wangmengyan95!

**Comment by andrewimm** [comment]
Glad you figured it out!
