### ISSUE TITLE
SDK JS: saveAll() with updates (PUT) is setting className into body 

### ISSUE THREAD

**Issue by pjnovas** [ParsePlatform/Parse-SDK-JS#156]
Hey, so if I fire from JS (client) with new entities works fine

```javascript
Parse.Object.saveAll( [ parseObject, parseObject ] )
```

but, if I send entities which already have an id (by `PUT`) it fails retrieving an error: 
```javascript
{
  code: 105,
  message: "The className key is a reserved word"
}
```

So I checked out the Request is sending (Chrome 46) from the console and it's setting the `className` into the body of each PUT request for the Batch.

```javascript 
{
  // .. removed keys from here
  requests: [{
    body: {
      className: "TeamMember", // < -- THIS
      displayName: "test",
      isAdmin: true
    },
    method: "PUT",
    path: "/1/classes/TeamMember/RQDYlZqgLA"
  }]
}
```

I give it a try doing a REST API request (without using the JS SDK) exactly the same but without that `className` property and it seems to work fine.

```javascript 
{
  // .. removed keys from here
  requests: [{
    body: {
      displayName: "test",
      isAdmin: true
    },
    method: "PUT",
    path: "/1/classes/TeamMember/RQDYlZqgLA"
  }]
}
```

Is this a bug or am I missing something?, I'm using parse version `1.6.14` and I'm working on the Browser.

Thanks!

**Comment by andrewimm** [comment]
I'm having trouble reproducing this. `classname` is not injected into the payload anywhere in the code; it suggests that your object is setting a className attribute. Can you show how you created the objects?

**Comment by pjnovas** [comment]
Sure!, here is an extract:

```javascript
const TeamMember = Parse.Object.extend("TeamMember");

createMembers(members){
    return members.map( member => {

      if (member.objectId){
        member.id = member.objectId;
        delete member.objectId;
        delete member.className;
        delete member.createdAt;
        delete member.updatedAt;
        delete member.__type;
      }

      return new TeamMember(member);
    });
  }
```
I call createMembers() with an array of JSON (previously ParseObjects doing .toJSON()) and then I call the following:

```javascript
Parse.Object.saveAll(members).then( done,  
 (error) => console.dir(error) /* <-- I get the error here */ );
```

**Comment by pjnovas** [comment]
@andrewimm 

So after I pasted the code I thought I could create the Entity in another way, instead of removing the props, create it with the id and then setting only the values and it worked fine:

```javascript
createMembers(members){
    return members.map( member => {
      let m = new TeamMember({id: member.objectId});
      m.set({
        displayName: member.displayName,
        isAdmin: member.isAdmin
      });
   });
}
```

Do you know why?, I'm closing the issue cause the problem was how I was creating the entity but I'd like to know why was my error if you have time (please mention me, so I get the notificacion if you answer)

Thanks for your time!

**Comment by andrewimm** [comment]
Minor note: Objects created with `toJSON()` do not contain the `__type` or `className` properties; these are only created by the private API method `_toFullJSON()`, so you shouldn't need to delete these properties. Additionally, object creation with an `id` attribute is supported, so I'm not sure you need any of your object manipulation.

Anyways, I'm sorry, but I still can't get this to reproduce. Here's the code I'm running, interpreted from what you describe:
```js
var TeamMember = Parse.Object.extend('Member');

var members = [
  new TeamMember({ count: 1 }),
  new TeamMember({ count: 2 }),
  new TeamMember({ count: 3 }),
];

Parse.Object.saveAll(members).then(() => {
  var json = [];
  console.log('Generating JSON...');
  members.forEach((m) => {
    var j = m.toJSON();

    // Note that
    if (j.objectId) {
      j.id = j.objectId;
      delete j.id;
      delete j.className;
      delete j.createdAt;
      delete j.updatedAt;
      delete j.__type;
    }
    // Print out the JSON objects
    console.log(j);

    json.push(j);
  });

  console.log('\nCloning objects...');
  var objs = [];
  json.forEach((j) => {
    var obj = new TeamMember(j);
    console.log(obj.id, obj.attributes);
    objs.push(obj);
  });

  console.log('\nSaving all objects...');
  return Parse.Object.saveAll(objs);
}).then((success) => {
  console.log('success');
}, (err) => {
  console.log('Error!');
  console.log(err);
});
```

And a sample output:
```
Generating JSON...
{ count: 1, objectId: 'wS2t9kgZ0T' }
{ count: 2, objectId: 'iHrn23CLkJ' }
{ count: 3, objectId: '6BD9bhQDUJ' }

Cloning objects...
wS2t9kgZ0T { count: 1 }
iHrn23CLkJ { count: 2 }
6BD9bhQDUJ { count: 3 }

Saving all objects...
success
```

**Comment by andrewimm** [comment]
@pjnovas walked through the entire chain Parse.Object.extend, through instance creation. Can't figure out where className would be carried through to the attributes of the object.

**Comment by pjnovas** [comment]
@andrewimm yeah it's weird, I tried to figure it out but didn't come up with the trouble.
I don't wanna take more of your time, I really appreciate your help, thanks again!
