### ISSUE TITLE
Not able to update object on PARSE when it added from iOS platform

### ISSUE THREAD

**Issue by akshayaher** [ParsePlatform/Parse-SDK-JS#157]
I have tried to update Parse object from Parse CloudCode function. I want to update status_id for one particular entry whose objectId is "vZveFx3KcP”. Whenever i call following function no entry gets updated. but whenever i added manual entry or entry from Android device it gets updated without any issue. For iOS i am using latest Parse version "1.11.0". I got this issue only to those entries who gets added by iOS platfrom.

Can any one Please explain where i am going wrong. I am new to javascript programming so let me know if you need additional information from me. You can check my code below. I have tried calling cloud function from Parse API console.

Parse.Cloud.define("freshFunction", function(request, response) {

           var GameScore = Parse.Object.extend("Booking");
           var query = new Parse.Query(GameScore);
           query.equalTo("objectId", "vZveFx3KcP");
           query.first({
                      success: function(results) {

                      alert("Successfully retrieved " + results.length + "user_id");

                      results.set("status_id", 2);
                      results.save();
                      response.success();
                      },
                      error: function(error) {
                      alert("Error: " + error.code + " " + error.message);
                       response.error();
                      }
                      });

           });

I am updating these entries from cloud code. I am able to fetch and update those entries from iOS platform. But those entries are not updating when we call them from cloud code. In cloud code i am getting success message but in reality its not at all updated. This happens to entries who are added from iOS platform. For android and manual entry function works fine.
Can anyone face the same issue ? Let me know if you need additional info from me. I have also added this issue on Parse iOS SDK Github. https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/723#issuecomment-169077787

Thanks in Advance,
Akshay Aher.

**Comment by andrewimm** [comment]
The issue is probably due to the fact the `save()` is an asynchronous process -- when you call `response.success()`, the outstanding request to save the object is immediately cancelled. You need to wait until the save succeeds before you can respond.
