### ISSUE TITLE
Docs incorrectly characterize how Parse.Promise.when callbacks work

### ISSUE THREAD

**Issue by braker1nine** [ParsePlatform/Parse-SDK-JS#158]
Since #115 was reverted, the corresponding docs changes in #116 should be reverted as well. At least until that code can make it's way back into the project.

**Comment by homburg** [comment]
+1 was expecting #115 behavior from docs. Looking forward to 1.7

**Comment by fatuhoku** [comment]
For anyone else wondering how to get 1.7 behaviour (where `Parse.Promise.when(arrayOfPromises)` returns an array of results) on 1.6.x, you can use `arguments` (inspired by http://stackoverflow.com/a/24870523/590767):

```js
            var returnParsePromiseWhenArgumentsListAsResultsForParseJSSDKVersion1_6_14 = function () { return arguments };

            someFunctionThatReturnsAnArrayOfPromises()
                .done(returnParsePromiseWhenArgumentsListAsResultsForParseJSSDKVersion1_6_14)
                .done((results) => {
                    //  Do something with results.
                    done();
                });
```
