### ISSUE TITLE
Why is the default query limit 100 and not 1000?

### ISSUE THREAD

**Issue by cfoulston** [ParsePlatform/Parse-SDK-JS#159]
I keep running into missing data issues because of this default limit of 100.

If I don't want to limit my queries (most of the time), why do I need to specify this maximum?
If I do want to limit my queries, then I should explicitly define the limit.

I understand that 1000 is the absolute maximum, and that fact is always in the back of my mind. But it seems strange to me that a default limit exists. Is there a reason why?

**Comment by TylerBrock** [comment]
Probably because the default batch_size for a cursor in MongoDB is 100 objects or 4mb, whichever comes first. On Parse because the object size limit is 128kb this means you always hit the 100 object default batch size before 4mb.

**Comment by cfoulston** [comment]
Well that's a shame.

**Comment by TylerBrock** [comment]
Why not just edit the file and change the default? It's all open source.
