### ISSUE TITLE
License and patent packaging should be included in the website- and cdn-hosted SDK releases

### ISSUE THREAD

**Issue by yupferris** [ParsePlatform/Parse-SDK-JS#16]
Currently the only available licensing information in these single-file releases is a notice describing that the license/patent grants are included in the root dir of the source tree, and no such source tree exists in those distributions. As an end-user, this feels like I need to also include those files in the source tree of the projects that consume the library, even when the rest of the project is not covered by these same terms. Because of this ambiguity the only legally safe option I have is to not include this vital piece of code in my source distributions. However, injecting the actual license and patent information into the single-file distributions instead of the notice that's there now would fix this.

**Comment by andrewimm** [comment]
Following 6fc89d9c5236ef3de5e7004ee5499ca518179b59, builds will include a link back to this repo

We'd rather not ship extra bytes if we don't have to.

**Comment by yupferris** [comment]
Thanks!
