### ISSUE TITLE
local time push notification from cloud code

### ISSUE THREAD

**Issue by xaksis** [ParsePlatform/Parse-SDK-JS#162]
JS sdk converts time to UTC... is there anyway i can send local time push notifications from cloudcode using the JS sdk?

```javascript
Parse.Push.send({
    where: query,
    push_time: "2012-11-14T17:00:00",
    data: {
 	           alert: "some message here!"
 	    }
    }, { success: function() { 
 			  // success!
 	}, error: function(err) { 
 	    status.error("something went wrong");
 	} 
 });
```

**Comment by andrewimm** [comment]
If you specify the time as a string without a timezone, like you have above, it should be sent as a local time zone push.

**Comment by xaksis** [comment]
Thankyou for responding @andrewimm . After playing around with it a bit more, it seems like the problem is in setting push_time rather than executing it. Here's an example scenario where I'm seeing this problem: 
* Let's say it's 6pm in new york and in cloudcode, I try to set a push for an hour later (7pm): *2016-01-09T19:00:00*
* Since in GMT at 6pm newyork time we have already passed 7pm, (it's 12 am next day already) the code thinks I'm trying to set a date in the past.

**Comment by peterdotjs** [comment]
@xaksis the scenario you specified should work just fine. The push will be sent to the devices in the local time - regardless of time zone. As long as you don't specify the time zone in the `push_time` value it will be considered as a `local time zone` delivery.

**Comment by xaksis** [comment]
hmm, maybe I'm not explaining this right. 
- Lets say I have two users one from Japan and one from Alberta, Canada. 
- My job which sets off at 6pm new york time, sets a local push ( without timezone ) for an hour later at 7pm for all users. 
- For the user in Alberta, this push is still valid... since their 6pm hasn't come yet. 
- however for my user in Japan, it's already past 7pm for today. 
The desired behavior here (at least for me) would be to trigger the push for the users that are still in the valid timezones. However, what I'm observing is that any time that is in the past for GMT is being considered a push in the past and is being rejected. 
Hope this makes sense...?

**Comment by andrewimm** [comment]
If a time might be valid for some local users, but it's not being processed, that's a backend issue. Either way, there's no bug here related to the JS SDK, so I'm closing this out. Feel free to follow up with the official Parse service bug reporting channels.
