### ISSUE TITLE
Error message TypeError: Cannot read property 'prototype' of undefined ->  var sessionQuery = new Parse.Query(Parse.Session);

### ISSUE THREAD

**Issue by animepauly** [ParsePlatform/Parse-SDK-JS#163]
I used to be able to query the user session counts after they login, but now I keep getting this error basically saying Parse.Session is undefined. I can't find anything in the documentation that changed so not sure why this is throwing an error now. Here is the simple query that is failing.
```javascript
Parse.Cloud.define("getNumberOfUserSessions", function (__request, __status)
{
  console.log("getNumberOfUserSessions called for "+__request.user.id);
  var __user = __request.user;
//Having issues with Parse.Session, trying this for now.
  var __sessionQuery = new Parse.Query(Parse.Session);
  __sessionQuery.equalTo("user", __user);

  return __sessionQuery.count().then(function (__numberOfSessionsInt)
  {
    // Set the job's success status
    console.log("getNumberOfUserSessions was a success! "+__numberOfSessionsInt);
    __status.success(__numberOfSessionsInt);
  }, function(error)
  {
    // Set the job's error status
    __status.error("Uh oh, something went wrong with getNumberOfUserSessions...Code:"+error.code+"::"+error.message);
  });
});
```

**Comment by wangmengyan95** [comment]
Hi @animepauly, could you tell us
1. What version of Parse JS SDK do you use in your cloud code? 
2. The exception happens in this line `var __sessionQuery = new Parse.Query(Parse.Session);` and the exception message is `Parse.Session` is not defined?

**Comment by animepauly** [comment]
1. I am using the JS SDK in CloudCode only and that version prints out as 3.0.2 in my terminal. 
2. Parse.Session seems to be returning undefined

**Comment by andrewimm** [comment]
There is no such version as 3.0.2, how are you reporting the version?

**Comment by andrewimm** [comment]
3.0.2 is the version of the Parse CLI tool -- to print out the version of the JS SDK, use `parse jssdk` on your computer, or print out `Parse.CoreManager('VERSION')` in your cloud code.

**Comment by animepauly** [comment]
Sorry about that. I am using JS SDK 1.3.5 in the Parse CLI

**Comment by andrewimm** [comment]
`Parse.Session` was not implemented until version 1.4.0

**Comment by animepauly** [comment]
I have been using this for months so please don't close and dismiss this. This just started throwing errors. If it truly is a version problem, how do I update the JS SDK for Parse cloud code?

**Comment by andrewimm** [comment]
The Parse CLI controls which version of the SDK is used in your cloud code environment.

From the directory for your parse app:
`parse jsssk --all` lists the SDK versions available
`parse jssdk X.Y.Z` sets the SDK version to use, where `X.Y.Z` is a valid SDK version.
On your next `parse deploy`, it will be set for your cloud code app.

**Comment by animepauly** [comment]
That fixed the issue. Thanks. Not sure how my js sdk got reverted then on cloud code.
