### ISSUE TITLE
Nativescript support

### ISSUE THREAD

**Issue by Quaggie** [ParsePlatform/Parse-SDK-JS#165]
As soon as I require the parse SDK on nativescript it doesn't compile because parse uses localstorage, which isn't included in Nativescript.

Any solution to this? 
The workaround I did was commenting out the `getItem()` and `setItem()` from `StorageController.browser.js`

```javascript
'use strict';

var _interopRequireDefault = require('babel-runtime/helpers/interop-require-default')['default'];

var _ParsePromise = require('./ParsePromise');

var _ParsePromise2 = _interopRequireDefault(_ParsePromise);

module.exports = {
  async: 0,

  getItem: function getItem(path) {
    // return localStorage.getItem(path);
  },

  setItem: function setItem(path, value) {
    try {
      // code..
    } catch (e) {
      // Quota exceeded, possibly due to Safari Private Browsing mode
    }
  },

  removeItem: function removeItem(path) {
    //localStorage.removeItem(path);
  },

  clear: function clear() {
    //localStorage.clear();
  }
};
```
This is working for me but some people may actually use localStorage.

**Comment by andrewimm** [comment]
The Parse SDK makes each of its components modular and swappable -- the most common use case is for using specialized Storage Controllers on different platforms. In the current codebase, you'll see 3 different implementations: one for the browser, one for Node, and one for React Native.

If you don't want to use the storage controller for any type of persistence (installation ids, user sessions), you can include `StorageController.default.js` in your app, and load it at run time. This would look something like:

```js
const DefaultStorageController = require('./StorageController.default.js');
Parse.CoreManager.setStorageController(DefaultStorageController);
```

however, if you wanted to implement your own Storage controller that uses whatever storage system Nativescript exposes, you could write that, using the ones we provide as inspiration.

You'll find that for most cases, the `parse` npm module runs fine, but it's designed for web browsers, just as `parse/node` is designed for node.js and `parse/react-native` is designed for React Native.

**Comment by Quaggie** [comment]
Oh, thanks Andrew.
I changed 
`_CoreManager2['default'].setStorageController(require('./StorageController.browser'));`
to 
`_CoreManager2['default'].setStorageController(require('./StorageController.default.js'));`
In Storage.js and all seems to work. 
Thanks again for the fast response.
