### ISSUE TITLE
Is it possible to query only objects that the current user has write permission?

### ISSUE THREAD

**Issue by gfpacheco** [ParsePlatform/Parse-SDK-JS#167]
Imagine the usual user-organization role system, where each user can be part of more than one organizarion (role).

Add a Resource class, that belongs to one organization (it's ACL only allows writing from that role).

How can I query all Resources that the current user has write permission?

**Comment by andrewimm** [comment]
It is not possible to query by ACL, so this is not possible without adding some extra field to query on.
