### ISSUE TITLE
Check for array values in Parse.Query

### ISSUE THREAD

**Issue by devfelipereis** [ParsePlatform/Parse-SDK-JS#168]
Hello!

I have an array of colors and I have an user that also have an array of colors. I want to know if it's possible to check if user's array have at least one value of my array. If so, I want to get the user.

Both are array of strings. 

Thanks!

**Comment by peterdotjs** [comment]
@devfelipereis you can take a look here: https://parse.com/docs/js/guide#queries-queries-on-array-values and https://parse.com/docs/js/guide#queries-compound-queries
