### ISSUE TITLE
Node package missing PATENTS file in package root dir

### ISSUE THREAD

**Issue by yupferris** [ParsePlatform/Parse-SDK-JS#17]
Similar to #16, but in this case there IS actually a source tree, and one of the two files mentioned by the per-file licensing information is there (LICENSE), but the patent grants are missing.

**Comment by andrewimm** [comment]
Our response to #16 is 6fc89d9c5236ef3de5e7004ee5499ca518179b59
We'll link back to this repo from all compiled sources.

Appreciate the PR for npm, though. I'll accept it now.

**Comment by yupferris** [comment]
Thanks, problem solved :)
