### ISSUE TITLE
relation query returning correct objects but with wrong classname/model

### ISSUE THREAD

**Issue by ethandt92** [ParsePlatform/Parse-SDK-JS#174]
I have 2 custom classes, Profile and File

I run this query

```
return Parse.User.currentAsync((user) => {
var q = user.get('profile').relation('portfolio').query()
return q.find()
})
```

portfolio is a ```relation<File>``` column

logging the items returns ```[ { className: 'Profile', _objCount: 13, id: '8NJWHiZ0Qk' } ]```

the object is correct and i can get the data if i do the usual ```item.get('field')```

but I extended Parse.Object so I have a File model with a custom getField() function that does some additional checks and cannot use that function because it thinks it is a Profile object

**Comment by andrewimm** [comment]
What version of the SDK are you using? An error similar to this was resolved in 1.6.13 or 1.6.14, if I remember correctly.

**Comment by ethandt92** [comment]
1.6.14

**Comment by ethandt92** [comment]
I temporarily fixed it by doing a ```user.get('profile').fetch()```

```
return Parse.User.currentAsync((user) => {
return user.get('profile').fetch()
})
.then((profile) => {
var q = profile.relation('portfolio').query()
return q.find()
})
```

i am not sure why fetching the profile fixed it

**Comment by ethandt92** [comment]
i fixed it another way that doesn't require a fetch by setting the targetClassName directly
```
let profile = user.get('profile')
let r = profile.relation('portfolio')
r.targetClassName = 'File'
let q = r.query()
```

**Comment by andrewimm** [comment]
So when the object isn't fetched, the code doesn't know what class name to use for the relation query. If the object is fetched, it does, which explains the divergent behavior. Let me dig into this further.

**Comment by andrewimm** [comment]
#179 should fix this

**Comment by jesperbruunhansen** [comment]
This problem has been bugging me for a while, as well.
Impressed you found how to "fix" it, @ethandt92 

Looking forward to release of fix.
