### ISSUE TITLE
relation query stopped working

### ISSUE THREAD

**Issue by arcman77** [ParsePlatform/Parse-SDK-JS#175]
I can test the relations in the database console when I am logged into parse, but when I try to do a relational query on an object from my server it returns nothing. This code worked before and I haven't changed it. The list that I am console logging is empty.
    
    query.first().then(
        function (object) {
          var tempRelation  = object.relation("tempAlgos");
          tempRelation.query().find().then(
            function (list){
              console.log(" list: ",list);
            },
            function (error){
              console.log("error:");
              console.log(error);
            }
          )//end tempRelation.query().then()
        },
        function (error)  {
          console.log(error)
         }
     );//end object .then()

**Comment by Quaggie** [comment]
Hello, @arcman77 . I've had similar problemas before, and from what I see you aren't returning anything and parse only deals with Promises.

This should probably work:
```javascript
return query
.first()
.then( function (object) {
    return object
        .relation("tempAlgos")
        .query()
    .find()
    .then( function (list){
        console.log(" list: ",list);
    }).then( null, function (error){
      console.log("error:");
      console.log(error);
  });
}).then( null, function (error)  {
    console.log(error)
});
```

**Comment by arcman77** [comment]
That syntax doesn't fix the issue either, but thank you very much for your prompt response. So I've realized theres a bit more context to add here. I've now realized that this particular relational query ("tempAlgos") is the only one that doesn't work. And earlier I made the mistake of trying to upload a different class object to the TempAlgos table - is it possible to break the table that way?

**Comment by Quaggie** [comment]
Actually, if a column doesn't exist on that table (class) it just creates it with the type it came along with. There isn't a way to "break" a table like that.
Maybe sending more code for us to help? (:

**Comment by arcman77** [comment]
Okay, in every route that queries for a user's tempAlgos, the results have now all been coming back as an empty array where as before it was populated with the objects I'm expecting. I don't understand why all of these routes stopped working at the same time, which led me to believe it was on Parse's end. 

    var express    = require('express');
    var router     = express.Router();
    var CryptoJS   = require("crypto-js");
    var gateKeeper = require('./gateKeeper');
    var Parse      = require('parse/node');
    var AES        = require("crypto-js/aes");
    var SHA256     = require("crypto-js/sha256");
    var SHA3       = require("crypto-js/sha3");
    var session    = require('client-sessions');
    var needle     = require('needle');
    
    var roughSizeOfObject = require('./getAlgoNames').roughSizeOfObject
    function aesDecrypt(string,key){
      var decrypted       = AES.decrypt(string, key);
      var decryptedString = CryptoJS.enc.Utf8.stringify(decrypted);
      return decryptedString;
    }

    function aesEncrypt(string,key){
      var encrypted       = AES.encrypt(string,key);
      var encryptedString = encrypted.toString();
      return encryptedString;
    }

    function sha3(string){
      var hashedString = SHA3(string).toString();
      return hashedString;
    }

    //Parse initialization
    var parseSecret1 = "HeyaHeyaHeya";
    var parseSecret2 = "WhatsGoinOn";
    Parse.initialize(parseSecret1, parseSecret2);
    //Parse initalization END

    function getUserAlgo(req,res,next){
       console.log("getUserAlgo req.body: " + JSON.stringify(req.body));
       var requestType = "getAlgoFiles";
       var User        = Parse.Object.extend("UserC");
       var query       = new Parse.Query(User);
       var response    = req.body;
       console.log("hufterAPI: ",req.body);
        var username = aesDecrypt(req.body.username, "SuperSecret");
        query.equalTo( 'username', username )
        query.first().then(
          function (object) {
            console.log("LOGIN: Successfully retrieved user" + object.get("username"));
            var accessToken = object.get('accessToken');
            var user         = {};
            user.accessToken = accessToken;
            user.username    = object.get('username');
            user.email       = object.get('email');
            var session_id   = aesEncrypt(user.username, "SuperSecret");
        
            var tempRelation = object.relation("tempAlgos");
            tempRelation.query().find().then(
                function (list){
                  console.log("hufterAPI: list: ",list); //list is empty now  :(
                  if (list.length == 0){  //the user has no uploaded algos
                    req.algo = false
                  }
                  else{ 
                    list.forEach(function (algo){
                      if(req.body.filename == algo.get("name")){
                        var encryptedAlgo = algo.get("encryptedString");
                        var key = "SuperSecret";
                        var algoFile = aesDecrypt(encryptedAlgo,key);
                        req.body.algo = algoFile;
                        req.body.lang = algo.get("fileType");
                        return;
                      }
                    });
                  }
                  req.user = user;
                  req.session.user = user;  //refresh the session value
                  req.session.user.session_id = session_id;
                  res.locals.user  = user;

                   console.log("req.session size: "+ roughSizeOfObject(req.session));
                   var hufter_domain = "hufter.herokuapp.com";
                   var backtest      = '/backtest';
                   var protocol      = req.body.protocol;
                   var algo          = req.body.algo;
                   var data = {algo: algo,"startDate": req.body.startDate,"endDate": req.body.endDate, "symbols": req.body.symbols, "lang": req.body.lang };
                   data = JSON.stringify(data);
                   data = aesEncrypt(data,"SuperSecret");
                   data = encodeURIComponent(data);
                   var fullQuery = protocol + "//" + hufter_domain + backtest + "?data="+data;
                   console.log("hufter API query: "+fullQuery);
                   new Promise(function (resolve, reject){
                      var request = needle.get(fullQuery,
                        function(err, response, body){
                          res.send(response.body)
                        }
                      );
                      resolve(request);
                    }).then(function (response){
                    });
                },
                function (error){
                  console.log( "line 90 hufterAPI users-algos error: "+error);
                  next();
                }
              );//end relation-then function
          },//end query user success function
          function (error) {
            console.log(" line 100 hufterAPI.js LOGIN-Error: " + error.code + " " + error.message);
            next();
          }
        ); //end query-first user
      return;
    }


    router.post('/',function (req,res,next){
      new Promise(function(resolve,reject){
        resolve(getUserAlgo(req,res,next))
      });
    });//router post-end

    module.exports = router;
What's weird is that I can add to the tempAlgos table and verify it on the Parse DB console, and even check which users they belong to, but its just these queries that won't work.

**Comment by Quaggie** [comment]
Did these queries stop working before you added any native promises? 
I don't know how parse handles Native & Parse promises together, but I'd recommend only dealing with Parse Objects as much as possible as they return a unique type.
What I'd do is add return statements before every query and log everything as much as possible, because other than that your code looks fine to me. :(

**Comment by arcman77** [comment]
Well thats the thing, this has been working for a long time, and I've even reverted back to commits as far back as a week when everything worked fine. I'm seriously considering just making a new table TempAlgos2

**Comment by Quaggie** [comment]
Yeah, or just test out a simple relation query in another JS file connecting to tempAlgos and see if that actually is the problem.

**Comment by arcman77** [comment]
So without changing anything - short of tossing in a few console.log() statements - the very same code started working for a different user. Then when I tried logging in with yet another user account, it broke again.

**Comment by Quaggie** [comment]
So if it works sometimes I guess it's not a Parse SDK problem. Check deeply into the sessions and authentication beforehand.

**Comment by andrewimm** [comment]
Agree that this is not an SDK problem. I'm guessing it's related to ACL permissions in some way, since it works for some users and fails for others. Feel free to continue the discussion here, but I'm closing this issue.

**Comment by arcman77** [comment]
If any of you has some time later today, I'd love the chance to use google hangouts or skype very quickly to show you the behavior I'm encountering. I've found that:
1. The issues are actually independent of the user (contrary to what I said earlier)
2. my tempAlgo queries only return 1 object, all other objects that get uploaded to the TempAlgo table are never returned in any query to the TempAlgo table. 
3. The one object that does get returned is an object that had been on that table for some time now, and I can't tell why its the only one that's getting returned - all other objects on that table have exactly the same fields filled out in the same way.

**Comment by Quaggie** [comment]
Yeah, sure. Send me your hangouts account so we can fix this (:

**Comment by arcman77** [comment]
Just sent you an email, thanks!
