### ISSUE TITLE
moving here the ESLint plugin to Parse

### ISSUE THREAD

**Issue by oriSomething** [ParsePlatform/Parse-SDK-JS#176]
hi!
while i worked at HappySale i've created a plugin for ESLint that made it easier for beginners to avoid some of the pitfalls of Parse. HappySale thankfully moved the repo to my account since i was the one who actually created and maintained the repo. sadly, since in my new job i won't use Parse, i would prefer this repo get the love it needs and not be neglected. i think **here** it's be much appropriate place.

[the link to the repo](https://github.com/oriSomething/eslint-plugin-parse)

**Comment by peterdotjs** [comment]
Hey @oriSomething, thanks for reaching out and for contributing to the Parse community with the linter plugin. I'll check with the rest of the team if it makes sense for us to take ownership of the repo as well as any legal implications.

**Comment by oriSomething** [comment]
it seems irrelevant because of [this announcement](http://blog.parse.com/announcements/moving-on/)
