### ISSUE TITLE
Parse::UserCannotBeAlteredWithoutSessionError after updating Object

### ISSUE THREAD

**Issue by VasiliDarozhkin** [ParsePlatform/Parse-SDK-JS#177]
Hello,

I try to update object using
```object.set(key, value);
object.save();```

The object has a field createdBy with pointer to User who created this object. 
after calling save() method there is a request to https://api.parse.com/1/batch
with PUT request with data of user who created the object. Then I get error ```Parse::UserCannotBeAlteredWithoutSessionError```
so I can't update the object.
Object has public read/write permission.

What should I do?

Thanks in advance!

**Comment by peterdotjs** [comment]
@VasiliDarozhkin have you tried using the Master Key? A post that explains what you're likely facing: https://parse.com/questions/users-editing-other-users-in-javascript-sdk

**Comment by VasiliDarozhkin** [comment]
Hi peterdotjs,

The trick is I don't try to change other Users. I try to update regular Parse.Object, which ACL and CLP are Public Read/Write permissions.
So this update doesn't affect the User, as I understand

**Comment by VasiliDarozhkin** [comment]
If User who created this object updates it, all works

**Comment by wangmengyan95** [comment]
Hi @VasiliDarozhkin, when we save a ParseObject, we save all its dirty children first and then the ParseObject itself. In your case, you do not change the `createdBy ` field but you get that error?

**Comment by VasiliDarozhkin** [comment]
Hi!
Yes, I change only one property which is boolean like 
``` object.set('isApproved', true);```
and then
``` object.save() ```
Last one causes PUT request with email and username of User who is in createdBy field (I don't update this field) and then get the error

The same code in Cloud works fine.

Thank you

**Comment by wangmengyan95** [comment]
Glad it works!

**Comment by VasiliDarozhkin** [comment]
Oh, but it does not work when I run it in the browser using Javascript SDK

**Comment by VasiliDarozhkin** [comment]
So issue is not really closed
