### ISSUE TITLE
Uncaught Invariant Violation: traverseParentPath(…): Cannot traverse from and to the same ID, ``

### ISSUE THREAD

**Issue by gfpacheco** [ParsePlatform/Parse-SDK-JS#178]
Would you please take a look at this: http://stackoverflow.com/questions/34914922/uncaught-invariant-violation-traverseparentpath-cannot-traverse-from-and ?

I'm facing an issue and I think one of these three libraries could be causing it: redux-form, material-ui and parse.

**Comment by andrewimm** [comment]
The invariant is not related to the Parse SDK, and there is not a single Parse method in the stack trace you mention. I'm going to close this task, as there is no identifiable issue with SDK code.

**Comment by gfpacheco** [comment]
You're right, but if I remove the parameter from the `object.save` call everything works fine. Doesn't it mean anything?

**Comment by andrewimm** [comment]
What version of the SDK are you using? Is A+ compliance enabled on Parse Promise?

I can't really comment without more knowledge about how the object in question is being constructed and manipulated. I wish I could be of more help, but I'm no Redux expert. If the object already existed, and no parameters were passed to the save call, it'd just be a no-op and return an empty resolved Promise.

**Comment by andrewimm** [comment]
I suggest you replace the save() call with native Promises for debugging. Toggling whether it is resolved or rejected may help you find the bug.

**Comment by gfpacheco** [comment]
Thanks for the interest in helping.

I'm using SDK v1.6.14.

The object is an existing ParseObject that was queried previously.

I already tried using native promises, but the result was the same.

If I keep the `save` parameters, but they didn't change compared to the previous values, the error doesn't happen. If I change any of the values, I get the error (and if re-submit the form is "clean" and I get no error).

**Comment by gfpacheco** [comment]
I really appreciate you help, I'm keep trying to find out whats happening, I tried to contact the other libs collaborators to help me. I'll let you know if I ever find the error.

**Comment by nishankkumar1994** [comment]
I am also facing this issue when i am trying to 'react-resizable-component' library. Can anybody help me out this.

**Comment by HyperDunk** [comment]
@nishankkumar1994 were you able to resolve this issue for using react-resizable-component?

**Comment by seiji619** [comment]
@nishankkumar1994 why not just create an issue on its own repo?
