### ISSUE TITLE
Adding object of different class to relation between user and another class breaks table 

### ISSUE THREAD

**Issue by arcman77** [ParsePlatform/Parse-SDK-JS#180]
var User         = Parse.Object.extend("User");
var user         = new User( );  /// pretend this user is already saved in Parse DB
var A              = Parse.Object.extend("A");
var B              =  Parse.Object.extend("B");
var relationA  = user.relation("as");

var b = new B( ); //pretend b is already saved in Parse DB as well
relationA.add(b);

Relational queries on table A will not work properly now -sometimes come back as empty or usually only containing a single object when there should be many in an array.

**Comment by andrewimm** [comment]
This is unavoidable. When the full content of `user` has not been fetched, there is no way to know what type the relation is. By adding the `B` type to the relation without saving, you tell the client that the type of the relation is `B`, which is the information it uses to fetch the body of the relation. Closing this, as users should not expect this to be supported behavior.

**Comment by arcman77** [comment]
I'm sorry I wasn't clear, but I'm not asking for support with this, I'm asking that an error be raised instead of letting this code execute. It was purely by mistake, but it'd be nice if this mistake doesn't allow you to ruin your table.

**Comment by andrewimm** [comment]
It doesn't actually ruin your table, it only confused the current client and makes incorrect queries. If you attempted to save the relation after adding the `B` object, it would fail with an error message, just like you're asking for.
