### ISSUE TITLE
Array fields seem to show something weird instead of parse objects

### ISSUE THREAD

**Issue by yaalaa** [ParsePlatform/Parse-SDK-JS#188]
Cloud Code

I've got a class `A` which has field `list` of array type.
`list` is maintained by Cloud Code functions.
My function adds to `list` instances of `Parse.User`.
My function loads `list` in the following manner:
```
var q = new Parse.Query(A);
q.include("list");
q.find().then(...)
```

Sometimes, or more precisely for certain records, my function gets `list` filled with something other than `Parse.User` objects and, in turn, fails.
I'm used to get the errors like this:
`Result: TypeError: Object #<Object> has no method 'getUsername'`

_Expected:_
array fields should keep the Parse objects properly

_Actual:_
array field might keep something weird instead of the Parse object previously added and saved to the field.

**Comment by yaalaa** [comment]
Adjusted description.

**Comment by peterdotjs** [comment]
@yaalaa can you give an example of one of the "weird" non `Parse.User` objects that gets returned in `list`?

**Comment by yaalaa** [comment]
`{"objectId":"blablabla"}` usually

**Comment by peterdotjs** [comment]
Have you attempted to fix this invalid data? And if so do you see it again after querying? We had an issue with the beta dashboard data browser where some objects were getting changed to {"objectId":"someId"} but has since been fixed and was only with the web beta dashboard. We have not had any issues like this with the SDK.

**Comment by yaalaa** [comment]
Yep, I've just fixed arrays. No more invalid array for now, but.. maybe it's not over yet.
If you're interested of, I'd say the bad data was created about two weeks ago.
Glad to her the issue had already been fixed.
Will monitor my app's data for a while, of course.

**Comment by peterdotjs** [comment]
@yaalaa that's good to hear. Feel free to open if you run into it again.

**Comment by yaalaa** [comment]
It has happened again.
