### ISSUE TITLE
Support for TwitterUtils?

### ISSUE THREAD

**Issue by davidchang** [ParsePlatform/Parse-SDK-JS#191]
Analogous to FacebookUtils, this is a feature request for support for TwitterUtils. This isn't a huge blocker for me, but if someone were to implement it, I'd definitely use it!

(I'm currently using Parse without leveraging Users and ACL and instead just created my own User class since I chose to avoid the hassle of figuring out how to transform my Twitter authenticated response into a Parse user.)

**Comment by andrewimm** [comment]
We can't implement TwitterUtils, since Twitter doesn't provide a client-side web login mechanism, the way FB does.
