### ISSUE TITLE
Parse.User.existed() always returns false in Cloud Code

### ISSUE THREAD

**Issue by emkman** [ParsePlatform/Parse-SDK-JS#196]
in afterSave for a User `existed()` always returns false, causing code to run on every save that is intended only for new users.

Example code:
```
Parse.Cloud.afterSave(Parse.User, function(request) {
  var user = request.user;
  console.log(user.existed()); //always false
}

```

Returns false after the user is created and then continues to return false when updating the user, by changing the email for instance. This is functionality that had worked as expected previously. Verified with Cloud Code set to JS SDK 1.5.0 and 1.6.14 cc @andrewimm

**Comment by emkman** [comment]
seems similar or duplicate of https://developers.facebook.com/bugs/1675561372679121/ which was marked fixed

**Comment by Psvetly** [comment]
Parse JavaScript SDK Version: 1.6.14.
The same is for me in beforeSave. isNew() always returns true
```
Parse.Cloud.beforeSave("RMEvent", function(request, response) {
    Parse.Cloud.useMasterKey();
if (!request.object.isNew())
{
    response.success();
}
else
{
    response.error("Event already exists");
}
}
```
And existed() always returns false:
```
Parse.Cloud.beforeSave("RMEvent", function(request, response) {
    Parse.Cloud.useMasterKey();
if (request.object.existed())
{
    response.success();
}
else
{
    response.error("Event already exists");
}
}
```
Tried both! Everything was working for months without changes, and now I see this.
A week before release, guys!

**Comment by Psvetly** [comment]
I apologize. Can confirm that the CloudCode works as expected for me, the problem was hiding dipper in my code. Thank you for your time!
