### ISSUE TITLE
Parse.Object.clone() is broken for Parse.User

### ISSUE THREAD

**Issue by TylerBrock** [ParsePlatform/Parse-SDK-JS#198]
Hey everyone,

I'm trying to user Parse.User with react/redux but having trouble because react/redux are unable to detect when a change happens to my user model via a shallow comparison. The problem is that Parse.User.current returns a reference to the same object.

I've tried to copy the object in my reducer by using `Parse.User.current().clone()` but `sessionToken` is read only so I get the following error message when I attempt to do so:

```
Error: Cannot modify readonly attribute: sessionToken
```

The constructor for Parse.Object just calls set for all attributes passed in but that doesn't work for sessionToken (as can be seen above). Any thoughts on this?

Also, somewhat obviously, trying to manually "clone" the object using `new Parse.User(Parse.User.current().attributes)` also fails in the same way.

**Comment by TylerBrock** [comment]
I got around it by doing this gross bit of code:

```js
var currentUser = Parse.User.current();
var attrs = Object.assign({}, currentUser.attributes);
delete attrs['sessionToken'];
var copy = new Parse.User(attrs);
copy.id = currentUser.id;
```

This makes react trigger a re-render successfully in case anyone else runs into this.

Would be happy to take a stab at adding support for Parse.User to `Parse.Object.copy()` though if people want.

**Comment by andrewimm** [comment]
We should probably just override `clone()` for Parse.User

**Comment by TylerBrock** [comment]
Yeah I agree.

**Comment by andrewimm** [comment]
Better yet, use `this.constructor.readOnlyAttributes()` as a blacklist in `clone()`, to work with any subclass.

**Comment by TylerBrock** [comment]
Yeah, except I'd like it if the session token WAS set in the clone.

**Comment by andrewimm** [comment]
Ah. So do you really want a clone? `clone()` produces an unsaved copy (no objectId, attributes have just been `set`). Seems like you just want another instance of the same object, with everything in place.

**Comment by TylerBrock** [comment]
Right. I was, perhaps incorrectly, assuming `clone()` did that. If the object you are cloning was saved then I figured the clone would also be saved in so far that they both would have real id's instead of local ids.

**Comment by andrewimm** [comment]
Resolved in 1.7.1

**Comment by nsarafa** [comment]
@andrewimm when you say this issue is "Resolved in 1.7.1" are you referring to the Parse .net SDK? If so, I'm running into this issue with our web app as the [Nuget package](http://www.nuget.org/packages/parse), as well as [Parse' .net repo](https://github.com/ParsePlatform/Parse-SDK-dotNET) are still listed at 1.7.0

I have limited experience with .net and aren't sure how to work around the issue

**Comment by andrewimm** [comment]
@nsarafa this Github repo and issue are about the JS SDK, not the .NET one. The .NET SDK is located at https://github.com/ParsePlatform/Parse-SDK-dotNET

**Comment by nsarafa** [comment]
@andrewimm my apologies. Got the SDKs. I'm running into this precise issue and this seems to be the only reference to it. My package.json is set to `"parse": "~1.8.0"` and i'm not sure how i'm encountering this error considering it was squashed months ago

**Comment by andrewimm** [comment]
The error mentions a server error, so I assume that you're actually talking about running Parse code within `parse-server`. Are you running cloud code? If so, can you look in your `node_modules/parse` folder for the value of `version` in `package.json`? That's the version that `parse-server` is using.

**Comment by nsarafa** [comment]
@andrewimm running 2.2.7

**Comment by andrewimm** [comment]
Sorry, I meant the version of the `parse` sdk running alongside your parse server. It'll be at `node_modules/parse/package.json`
