### ISSUE TITLE
Parse.Object.save return doesn't contains "__type"

### ISSUE THREAD

**Issue by laullon** [ParsePlatform/Parse-SDK-JS#199]
Hi,

I have this cloud function:

```javascript
Parse.Cloud.define("newPhoto", function (request, response) {
    var Photo = Parse.Object.extend("Photo");
    var p = new Photo();
    p.set("caption", 'tururu');
    p.save().then(function (np) {
        response.success(np);
    });
});
```

The 'np' object doesn't have the "__type" property, so it can be translated to a PFObject on my IOS app.

This happened we I deploy my app on a local Parse-server instance.
Please take a look of this bug: https://github.com/ParsePlatform/parse-server/issues/112

**Comment by andrewimm** [comment]
This is not an issue with the JS SDK -- the return type for save() is a Parse Object, which the server code needs to explicitly convert to the over-the-wire representation with `._toFullJSON()`.

**Comment by laullon** [comment]
Ok,

I know how to solve this when I return this:
`response.success(np);`

But no if I return something like this:
`response.success({ photo : np });`
or any other object that contains a ParseObject.

Any suggestion @andrewimm ?

**Comment by andrewimm** [comment]
I believe parse-cloud-express needs to be rewritten to use the `encode` function from the JS SDK.

However, you can encode any of your server responses today by calling `Parse._encode(value)`, so your code example becomes `response.success(Parse._encode({ photo: np }));`

**Comment by laullon** [comment]
Thanks @andrewimm I did solve the problem...

I even made a pull request to parse-server
https://github.com/ParsePlatform/parse-server/pull/252
