### ISSUE TITLE
Add browser dist files to npm

### ISSUE THREAD

**Issue by simonbengtsson** [ParsePlatform/Parse-SDK-JS#20]
It would make life easier when working on projects not using browserify (or similar) if the browser dist files were published to npm. If I understood your build process correctly it could be accomplished by adding a `.npmignore` file with your current `.gitignore` content sans the dist folder ie:

    # .npmignore file
    coverage
    lib
    node_modules
    test_output
    *~
    .DS_Store

**Comment by andrewimm** [comment]
Can you explain why you need a built copy for your unit tests? We would like to avoid shipping bundled versions of the SDK in npm module, as this can encourage antipatterns. Are you running them in a browser, or in node?

Sounds like you could use the latest version of our SDK available from our Downloads page, or from our CDN: www.parsecdn.com/js/parse-latest.js

Merging this issue into #26

**Comment by simonbengtsson** [comment]
With npm 3 more people will use npm as a front end package manager. Sure people could continue downloading the sdk from the website but it feels a bit dated. I ended up writing my own script compiling the sdk with browserify.
