### ISSUE TITLE
What is the difference between these two include file?

### ISSUE THREAD

**Issue by RadianSmile** [ParsePlatform/Parse-SDK-JS#201]
In mu nodejs server, what is the difference between the two command ? 

```var Parse = require('parse');```

vs 

```var Parse = require('parse/node');```

**Comment by mohan999** [comment]
First one is for use in the browser, bundled with browserify or requirejs.

Second one is for use with node on the server.

**Comment by TylerBrock** [comment]
We share a lot of parse code on our back-end server, our front-end, and
also react native. We made a library so that you just require 'parse-shim'
on any platform and it does the right thing.

https://www.npmjs.com/package/parse-shim

**Comment by RadianSmile** [comment]
I just can't figure it out  the functionality differences. No matter which require way I use in node.js backend, they seems the same thing. Besides codes are bundled or not, are there more differences between the two? If not, I think there could be more differences.

Situation that Parse has released its server source. Maybe Parse-server could then do request dirrect into mongodb instead of the httprequest way ( normally through Parse.serverURL). Maybe, I guess, the change could save some request time or more.

Thanks for reply! 
By me, a rookie.

**Comment by andrewimm** [comment]
The `parse` package is the one designed for client applications. It uses the native XMLHttpRequest object to talk to the Parse API, uses LocalStorage to save InstallationIDs and Config caches, and has single-instance object mode disabled by default (If I have two instances of the same object, updating one updates the other, as they're backed by the same data. This helps keep UIs synchronized.)

The `parse/node` package is designed for server usage, in a shared-memory environment. It uses a polyfill of XHR, uses an in-memory map for the Storage API, and automatically enables single-instance mode to be memory safe. It also disables functionality that's unsafe in shared-memory environments, like the "current user" concept.

The division also allows us to continually divide the different SDKs down the road. For instance, I'm currently playing with replacing the XHR polyfill in node with something more optimized for the server (A RESTController that keeps connections open to the API, and avoids reallocating resources so often.
