### ISSUE TITLE
Limit on OR queries result in lost of that parameter

### ISSUE THREAD

**Issue by RafaRuiz** [ParsePlatform/Parse-SDK-JS#202]
Hello.

I'm trying to declare a 
`var query1 = new Parse.Query("Class");`
and
`var query2 = new Parse.Query("Class");`

then they have different parameters, and I set:
`query1.setLimit(20);`
`query2.setLimit(4);`
`var queryFinal = Parse.Query.or(query1, query2);`

and the result is a 100 objects array.
What am I doing wrong?

**Comment by andrewimm** [comment]
From [the documentation](https://parse.com/docs/js/guide#queries-compound-queries):
"Note that we do not, however, support GeoPoint or non-filtering constraints (e.g. near, withinGeoBox, limit, skip, ascending/descending, include) in the subqueries of the compound query."

The simplest reason being that limits and other structures don't make sense inside OR queries. OR queries are for combining the "select" state of the DB query. It indicates that the results are interchangeable. If you're expecting two different result sets, then you should be issuing two different queries in parallel, and using `Parse.Promise.when()` to handle them when they're both completed.
