### ISSUE TITLE
Stale data on client when fields are deleted on server.

### ISSUE THREAD

**Issue by drew-gross** [ParsePlatform/Parse-SDK-JS#205]
If an object is fetched on the client, then a field from that object is deleted on the server, and then the object is retrieved via Parse.Query(...).get(id), the object will still have the field that was deleted on the server. This requires single instance mode to be enabled.

**Comment by andrewimm** [comment]
#206 should resolve this

**Comment by andrewimm** [comment]
I might want to add some extra internal integration tests as well

**Comment by andrewimm** [comment]
Resolved in 1.7.1
