### ISSUE TITLE
problem using parse promises

### ISSUE THREAD

**Issue by rajujin1** [ParsePlatform/Parse-SDK-JS#21]
Hi All,
I want to execute the following scenario:-
1) Check if the object with ID exist in class data
Does not exist:---Create the new entry in the database
Exists :---Update some of the fields based on the input params
2)After saving send the push notification

Below is my code:

query.first().then(function(results) {
// Create a trivial resolved promise as a base case.
var promise = Parse.Promise.as();

            AnsPtr = results.get("AnsPtr");
            //Max 10 Answers can be stored after that the answer will be overwritten.
            AnsPtr = AnsPtr % 10;
            console.log("new query succcess i got ansptr--"+AnsPtr);
            return promise;
}).then(function(){ //Saving the content in the database
            if(request.params.Answer != null )
            {
              Answer    = request.params.Answer;
              listing.set("Answer_"+AnsPtr, Answer);
              // Increment the current value of the quantity key by 1
              listing.increment("AnsPtr");
          console.log("save  contetnt failure i got ansptr--"+AnsPtr);
            }
    listing.save(null).then(function(listing) {
            // The save was successful.
            console.log("I saving");
            }, function(error) {
            // The save failed.  Error is an instance of Parse.Error.
    });
 }).then(function(){
     console.log("I am final succcess");
 });
My Expectation:--
"12 new query succcess i got ansptr--"+AnsPtr);
"34--save contetnt failure i got ansptr--"+AnsPtr);
"56--I saving");
"78-I am final succcess");

Actual behavior:
"12 new query succcess i got ansptr--"+AnsPtr);
"34--save contetnt failure i got ansptr--"+AnsPtr);
"78-I am final succcess");
"56--I saving");

Please point me in case i misunderstood promises or missed something..

-Rajender Jindal

**Comment by stanleyw** [comment]
The existing behavior is correct.  "I saving" will not be printed until the save is actually completed.  While the browser is waiting for that save to complete, it continues to execute the next code section.

You may have meant to write this instead:

      ...
      // Start the save operation
      console.log("I saving");
      return listing.save(null);
    }).then(function(listing) {
      // The save was successful.
      console.log("I am final success");
    }, function(error) {
      ...
    });

You can read more about Promises at https://www.parse.com/docs/js/guide#promises

**Comment by rajujin1** [comment]
Hi There,
Aplogise for the delay..
Stanley thanks a lot for the reply...
For the time being i have found the alternative way to solve my purpose.
Will try as suggested by Stanley.

You can close this issue...
-Thanks and Regards,
Rajender Jindal
