### ISSUE TITLE
[Parse Server] clientKey is optional if using Parse Server

### ISSUE THREAD

**Issue by hramos** [ParsePlatform/Parse-SDK-JS#210]
A client key does not need to be configured in order to deploy a Parse Server. The Parse JavaScript SDK's Parse.initialize() method, however, requires a client key to be passed in. This parameter should be made optional.

**Comment by andrewimm** [comment]
Actually, I just walked through the network path for the SDK, and it looks like the parameter is already optional from an operational perspective

**Comment by hramos** [comment]
Yes, I think you can initialize the SDK with a blank string as the client key, but having a initialize() method that does not even have that parameter would make for nicer Getting Started examples.

**Comment by andrewimm** [comment]
So, is this just a docs / docblock change? `initialize('x')` is the same as `initialize('x', undefined)`, which is supported / doesn't throw. Unlike the other platforms, I don't think we need a change here.

**Comment by andrewimm** [comment]
Updated in 9095e346edd06632cc755fafd377d930b81762df :)
