### ISSUE TITLE
Call cloud function, _SessionToken is not send to server

### ISSUE THREAD

**Issue by flessard** [ParsePlatform/Parse-SDK-JS#214]
In 1.7.1 (Browser version), if you call a cloud function, the _SessionToken is not send to server. 
Work fine in 1.6.14

**Comment by andrewimm** [comment]
Can you provide code?

**Comment by flessard** [comment]
` Parse.User.logIn("user@company.com", "1234").then(function(){
	 return Parse.Cloud.run('test', {})
 })`

And look the Request Payload in Chrome, no _SessionToken.

**Comment by andrewimm** [comment]
Just ran it with the built version of 1.7.1 from the releases page of this github repo, it worked fine. Are you sure your current user actually has a session token?

**Comment by flessard** [comment]
Sorry i found the bug, is in my app. Sorry about this !
