### ISSUE TITLE
Issue with request.user (returning null always)

### ISSUE THREAD

**Issue by sprabs** [ParsePlatform/Parse-SDK-JS#215]
I am not sure if others are facing the same issue, but we are currently in the process of moving our Cloud Code from being hosted on parse.com. When we are deploying the Cloud Code to our hosted parse-server, we seem to be having issues with accessing current user data. As per the documentation, we have changed all Parse.User.current() calls to request.user. However, we are getting the following errors: 

Uncaught internal server error. [TypeError: Cannot read property 'get' of null] TypeError: Cannot read property 'get' of null
    at Object.fetchTrendingEntities (/var/app/current/cloud/main.js:2606:33)

Can we not do something like this: request.user.get("favoriteTeams") or request.user.id?

Our main.js file has functions that have nested promises in them. We would like to pass information about the current user (i.e., objectId, favorite teams, etc...) to the internal methods for processing. That's where it's failing.

**Comment by andrewimm** [comment]
This sounds like a Parse Server issue, and not related to the JS SDK in any way.
