### ISSUE TITLE
Parse and Backbone

### ISSUE THREAD

**Issue by drbarto** [ParsePlatform/Parse-SDK-JS#217]
If I understand correctly, ParseJS abandoned its Backbone origins mainly for political reasons -- i.e. to push Facebook's React framework. Now in the light of the latest, uh, development in the relation between Facebook and Parse, I wonder if there are any plans to get Parse back on the Backbone track. 

Or, if this is not the case, are there any extensions that can bring back some of the nicer Backbone features (collections, events, ...) to Parse?

**Comment by andrewimm** [comment]
I can assure you that the choice to abandon Backbone was not political in any way, but a calculated decision we made after interviewing many of our developers and their use cases. It wasn't a move to push people towards React, but a move towards the current world of JS frameworks; Angular, Ember, and React. I'm sorry you got that impression, but the call would have been the same regardless of our affiliation with FB. Having an SDK that was explicitly tied to a single framework wasn't a great decision looking forwards, and we wanted our library to be framework-agnostic.

Many of the decision points were stated when we released 1.6, but I'll reiterate them here.
In 2012, Backbone was unquestionably the most popular framework for JS frontend applications, MVC was the most popular application structure, and so the JS SDK was designed to be a drop-in replacement for Backbone's Model. Fast forward to today: the face of JS applications has changed. Today, we feel that two-way data binding and treating each object as its own pub/sub channel is a pattern that overcomplicates application development. Regardless of whether people use Angular, Ember, or React, they're adopting single-direction data flows to dramatically simplify application architecture. We've focused our future SDK work on embracing that pattern, and we believe that it's the most responsible path forward. Obviously, building each of these integrations is a lot of work, so we hoped the community would pick up some of the work in binding the SDK to their favorite frameworks.

**Comment by drbarto** [comment]
Ok, got it. Many thanks for the detailed explanation! I'm new to ParseJS, so I was not aware of these considerations you made prior to 1.6.

Concerning the second part of my question: I think others might also have had problems with the removal of Backbone features from Parse, so I'd be very thankful for any hint on libs, extensions etc. which can be used to get back some of these features.
