### ISSUE TITLE
Changing version to 1.7.0 gives "script error" without details

### ISSUE THREAD

**Issue by mmahmood** [ParsePlatform/Parse-SDK-JS#218]
I am trying to upgrade to version 1.7.0. I simply change the version in config/global.json to 1.7.0 and deploy app. It gives me error "script error" without any details. I have done "parse update". It says that I am already on the latest cli version 3.0.2.  Version 1.6.14 is working fine for me.

**Comment by andrewimm** [comment]
I'm not sure that 1.7.0 has been deployed to cloud code. If you want to use more modern features, you should be looking to migrate your cloud code to your own servers before the hosted service shuts down next year.

**Comment by mmahmood** [comment]
This is strange. I could not understand why certain things behaved differently in my hosted Parse app, than on my local Parse server, and I was told by support that I need to upgrade to v1.7.0. I tried to do that on my hosted/ running app so that whenever we migrate, it's a simple process with minimal code changes, and you are telling me it's not possible. Anyways, thanks.

**Comment by andrewimm** [comment]
We want to encourage people to move away from the hosted service, so it will not be getting any of the new benefits found in newer SDKs.
You can run an external cloud code server today without migrating your data, by leveraging webhooks. That would allow you to run your code externally without moving your data.
