### ISSUE TITLE
Is there a typescript definition file ?

### ISSUE THREAD

**Issue by zhouhao27** [ParsePlatform/Parse-SDK-JS#220]
I'm wondering if there is a .d.ts file for parse-sdk-js?

**Comment by andrewimm** [comment]
Nope, not at the moment. We use Flow for typechecking, and there's no easy way to generate Typescript definition files from that. It's a lot of work to maintain something by hand, but we'll look into adding this in the future.

**Comment by zhouhao27** [comment]
ok, thanks.
