### ISSUE TITLE
Multi Instance

### ISSUE THREAD

**Issue by RobertNNms** [ParsePlatform/Parse-SDK-JS#221]
Hi,

I have 2 apps running on the same server, and I get the same instance of my vars Parse and ParseDev.
An idea how to fix this?

Thanks
Robert

--------------------------------------
My code:
Parse = require('parse/node'),
ParseDev = require('parse/node');
	
Parse.initialize(PARSE_APPID_KEY_PROD, PARSE_JS_KEY_PROD, PARSE_MASTER_KEY_PROD);
Parse.serverURL = PARSE_SERVERURL_PROD;	
Parse.Cloud.useMasterKey();

ParseDev.initialize(PARSE_APPID_KEY_DEV, PARSE_JS_KEY_DEV, PARSE_MASTER_KEY_DEV);
ParseDev.serverURL = PARSE_SERVERURL_DEV;	
ParseDev.Cloud.useMasterKey();

var cParse = Parse; // Parse or ParseDev --> Same instance

var _installation = cParse.Object.extend("_Installation");
var query = new cParse.Query(_installation);
query.equalTo("deviceType", "ios");
query.find({
	success: function(results) {
	console.log(results.length);
	for (i = 0; i < results.length ; i ++) {
		var object = results[i];
		console.log(object.get('firstname'));
	}
},
	error: function(error) {
		alert("Error: " + error.code + " " + error.message);
	}
});

**Comment by andrewimm** [comment]
The JS SDK as-is does not support multi-instance, since it's ultimately designed for client apps. You should ask on the Parse-Server repo. I know they're working on a solution for this.
