### ISSUE TITLE
OAuth example

### ISSUE THREAD

**Issue by oallouch** [ParsePlatform/Parse-SDK-JS#222]
Hi,

I'm a little lost here. I don't really understand how to use the parse-server OAuth capabilities.
Do you have any code snippet to show me how to log in using that feature.

Thx in advance,

Olivier Allouch
www.illicotravel.com

**Comment by andrewimm** [comment]
Issues regarding Parse-Server should be posted on the repo of that project. This repository is for the JS client SDK.

**Comment by oallouch** [comment]
Exactly. 
I'm just looking for an example on how to login using Google (or Twitter...) using the js sdk. 
Do I have an OAuth library?

**Comment by andrewimm** [comment]
Your question is more about oauth than the JS SDK. If you have an oauth token, you can send that to your server and get a user back, assuming your server is set up to handle that. Nothing in the JS SDK explicitly supports oauth in any way.

**Comment by oallouch** [comment]
Ok, thx
I have old parse articles, but I'm digging in the parse-server code to understand it better.

**Comment by flavordaaave** [comment]
@oallouch Have you managed to get oAuth working using the JS SDK? I'm currently trying to authenticate new Users using the new capabilities (twitter, google, linkedin etc.) offers.
