### ISSUE TITLE
Import issue with TypeScript

### ISSUE THREAD

**Issue by flavordaaave** [ParsePlatform/Parse-SDK-JS#224]
I'm using the SDK within an ionic 2 / Angular2 Project written in TypeScript.
To use Parse I installed the SDK using npm and then import it using the following statement:
```
import {Parse} from 'parse';
```
I can then use Parse as expected in my class e.g.
```
export class User {
  constructor() {}

  getUser(): Parse.User {
    return Parse.User.current();
  }
}
```

As mentioned, this is working without errors in the browser but TypeScript is complaining with this message:
`Module '"parse"' resolves to a non-module entity and cannot be imported using this construct.`

**Comment by andrewimm** [comment]
From what I can guess, I assume Typescript is trying to find the 'default' export on the parse module, which does not exist.

You may want to try the following:
```js
import * as Parse from 'parse';
```

If that fails, blame Typescript. I found a bunch of these errors in my quick search. The easiest way is to stop using ES6-style imports and just `const Parse = require('parse');`

**Comment by tennysonp** [comment]
Hey Andrewimm. I am having the same issue. But import * as Parse from 'parse'; does not work.
