### ISSUE TITLE
Missing file in version 1.8 and breaks React Native app.

### ISSUE THREAD

**Issue by 5amfung** [ParsePlatform/Parse-SDK-JS#231]
No problem with 1.7 but as soon as I switch to 1.8, I got the following error.  ```ParseLiveQuery.js``` is not there.

```
Unable to resolve module events from /Users/foo/src/myapp/node_modules/parse/lib/react-native/ParseLiveQuery.js: Unable to find this module in its module map or any of the node_modules directories under /Users/node_modules/events and its parent directories
```

**Comment by andrewimm** [comment]
cc @peterdotjs 

Either we need to add node's `events` explicitly to `package.json` as a dep, or fork the code using build flags and import RN's `EventEmitter` module.

**Comment by andrewimm** [comment]
1.8.1 explicitly imports the `events` package. I ran it against a fresh RN app, and it worked. Let me know if you have any more issues!

**Comment by 5amfung** [comment]
I actually discovered the issue after I removed the whole node_modules and ```npm install``` again from my project.  Not sure what I'm missing.

**Comment by joevo2** [comment]
not working on 1.9 need help event emitter not found

**Comment by andrewimm** [comment]
@joevo2 can you provide more information on your error? A stack trace would be helpful.

Additionally, does it work with 1.8.5, but fail with 1.9.0?

**Comment by joevo2** [comment]
Here is the stack traces 

`Unable to resolve module events from /Users/Joel/Projects/AwesomeProject/node_modules/parse/lib/browser/EventEmitter.js: Unable to find this module in its module map or any of the node_modules directories under /Users/node_modules/events and its parent directories

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.

RCTFatal + 104
-[RCTBatchedBridge stopLoadingWithError:] + 1138
__25-[RCTBatchedBridge start]_block_invoke_2 + 65
_dispatch_call_block_and_release + 12
_dispatch_client_callout + 8
_dispatch_main_queue_callback_4CF + 714
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
__CFRunLoopRun + 2073
CFRunLoopRunSpecific + 488
GSEventRunModal + 161
UIApplicationMain + 171
main + 111
start + 1
0x0 + 1
`

**Comment by andrewimm** [comment]
@joevo2 please see the comment I made on your post in the FB group. You should be doing `require('parse/react-native')`, not `require('parse')`.

I'm trying to design a way to warn the user when they use the wrong version of the SDK on RN.

**Comment by joevo2** [comment]
Thanks a lot! Appreciate the help!   
  

  
  
  
  

  
  
>
