### ISSUE TITLE
Where to download the latest version?

### ISSUE THREAD

**Issue by zhouhao27** [ParsePlatform/Parse-SDK-JS#237]
The version in cdn is 1.6.14 instead of 1.8.1. Where should I download it? Thanks.

**Comment by peterdotjs** [comment]
We'll have the latest version on CDN soon there was an issue in our pipeline that was just resolved.

**Comment by zhouhao27** [comment]
Thanks.

**Comment by petek157** [comment]
Am I doing something wrong, or is it still 1.6.14 on the CDN and website.  Somehow I have 1.7.1 currently and see that there is a new version yet can find it anywhere.  Please advise.

**Comment by zhouhao27** [comment]
It's still old version in CDN. You can download the source code and build the latest sdk by yourself.
