### ISSUE TITLE
Problem to use latest js sdk

### ISSUE THREAD

**Issue by zhouhao27** [ParsePlatform/Parse-SDK-JS#238]
I build the JS SDK by running **build_releases.sh**. Then copy the parse-latest.js from dist folder to my js folder in public folder. And add to my index.html like this:

`<script src="js/parse-latest.js"></script>`

I got the following error message:

> parse-latest.js:7 Uncaught Error: Cannot find module 'events' 
> app.bundle.js:34066 ORIGINAL EXCEPTION: ReferenceError: Parse is not defined

Then I tried to install from npm by running: **npm i parse --save**. But I don't know where to add `var Parse = require('parse');`

If I added it in my index.html file like this:

```
  <script>
    var Parse = require('parse');
  </script>
```

I got the error message:

> (index):51 Uncaught ReferenceError: require is not defined
> TypeError: Cannot read property 'initialize' of undefined

My app is running well if I use parse from cdn: `<script src="http://www.parsecdn.com/js/parse-latest.js"></script>` But the version is still 1.6.14.

Can anybody help ? Thanks.

**Comment by zhouhao27** [comment]
If there any sample code for starter? I tried the parse-js-blank by using the latest parse sdk. I got the same problem:

> Uncaught Error: Cannot find module 'events'
> index.html:43 Uncaught ReferenceError: Parse is not defined

But if I used back 1.6.14, everything's fine. Anything changed? Can you add explanation in README.md? Thanks.

**Comment by peterdotjs** [comment]
We're using events.eventEmitter to support liveQueries which is resulting in your error. I'm looking into why 'events' is showing up as undefined in the during the build for parse-latest. For now please use 1.6.14.

**Comment by zhouhao27** [comment]
@peterdotjs Great. Thanks.

**Comment by zhouhao27** [comment]
Is there any sample application to use JS SDK? I got 

> Cannot find name 'require'.

In my javascript:

`var Parse = require('parse');`

**Comment by abbasdawood** [comment]
@zhouhao27 why dont you try using the bower module if you are using this for front end development? This is pretty good - https://github.com/rabidaudio/bower-parse

@peterdotjs any fix on the events module yet? For me 1.7.1 (pre livequery JS SDK) is working fine

**Comment by peterdotjs** [comment]
@abbasdawood the events module is resolved in 1.8.2

**Comment by abbasdawood** [comment]
Works perfectly well thanks!

*Abbas Dawood*

**Comment by ivansifrim** [comment]
I have the same issue but it seems that 1.8.2 is no longer an option:

Available versions in https://github.com/rabidaudio/bower-parse.git: 1.8.1, 1.8.0, 1.7.1 ....

@abbasdawood , any thoughts?

**Comment by abbasdawood** [comment]
hi @ivansifrim I'm on 1.8.3 and its working as expected. I see you're using the bower package, take the source directly from Parse JS SDK (download via npm or download source). You can use the js / minified js in the dist directory.

Will have to tell @rabidaudio to include 1.8.3 in the bower package if you need bower only

**Comment by ivansifrim** [comment]
@abbasdawood - Yep, I'm using bower Thanks for the quick response.

**Comment by rabidaudio** [comment]
Thanks for the heads up. 1.8.2 is now on bower

**Comment by camdagr8** [comment]
Is this broken in 1.9.2? I seem to have the same error in this version.
