### ISSUE TITLE
requiring unknown module "parse"

### ISSUE THREAD

**Issue by mihir-harbinger** [ParsePlatform/Parse-SDK-JS#239]
![screenshot from 2016-03-23 12 20 02](https://cloud.githubusercontent.com/assets/17466938/13977744/92594a50-f0f1-11e5-929e-72dc06f3b95e.png)

package.json

```
{
  "name": "IOT",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "parse": "^1.8.1",
    "parse-react": "^0.5.1",
    "react": "^0.14.7",
    "react-native": "^0.22.2",
    "react-native-vector-icons": "^1.3.2"
  }
}

```

Why am I getting this error?

**Comment by andrewimm** [comment]
Parse 1.8.1 is not compatible with `parse-react`. This is stated on the `parse-react` repo. You should use `1.6.14` if you wish to still use `parse-react`, which is in the process of being replaced with a Redux-oriented solution.

**Comment by xphaul** [comment]
#267 @andrewimm hi i am having the same issue . and i have the parse-react 1.6.14 on my package.json
