### ISSUE TITLE
Error code is not right, why?

### ISSUE THREAD

**Issue by dudunato** [ParsePlatform/Parse-SDK-JS#241]
I have a cloud function (beforeSave) and I'm validating if a collection is returned empty, if so, I would throw an error telling the user that he already have something in there. It's all working ok, the only problem is that instead of returning me error.code 142 it's returning 141, is anything wrong with my code?

`
query = new Parse.Query('List');
    query.equalTo('property', list.get('property'));
    query.equalTo('type', 'change_of_occupancy');

    query.find({
      success: function(lists) {

        if (lists.length > 0) {
          response.error('You already have one change of occupancy list registered!'); // I can see this message on response, but it's 141 instead 142 ??
        } else {
          response.success();
        }

      },
      error: function(error) {
        console.error("Got an error " + error.code + " : " + error.message);
        response.error(error);
      }
    });
`

**Comment by dudunato** [comment]
The funny thing is that it was working before the migration, now that we have a self hosted parse-server it's happening...

**Comment by andrewimm** [comment]
Probably an issue with `parse-server`, not the SDK. This repo is reserved for issues related to the SDK, so I'm closing this.

**Comment by maleksalem** [comment]
@dudunato Can you please let me know how did you resolve the error code 141 issue in parse server?
I am having the same issue and I am not able to resolve it.
Thanks

**Comment by dudunato** [comment]
Well, I didn’t really resolved it.
I just ignored it in my code assuming that this is not JS error.

-- 
@dudunato

On 18 de maio de 2016 at 09:57:18, Malek Salem (notifications@github.com) wrote:

@dudunato Can you please let me know how did you resolve the error code 141 issue in parse server?
I am having the same issue and I am not able to resolve it.
Thanks
