### ISSUE TITLE
usage of console-timestamp causes object save to go into infinite loop

### ISSUE THREAD

**Issue by sud80** [ParsePlatform/Parse-SDK-JS#245]
console-timestamp uses colors library which extends String prototype. This causes the save to go into infinite loop.

Basically traverse function in unsavedChildren.js does not handle string seperately. It goes into following loop:
  for (var k in obj) {
    if (typeof obj[k] === 'object') {
      traverse(obj[k], encountered, shouldThrow, allowDeepUnsaved);
    }
  }

Since it iterates over all keys, and String is extended by colors, it goes into infinite loop. Can we handle string seperately or only iterate over the own properties (not sure if this has other implications)?

**Comment by andrewimm** [comment]
The issue introduced by `colors` overriding the string prototype should have been resolved in a previous version.
