### ISSUE TITLE
Parse.User.resetPassword

### ISSUE THREAD

**Issue by andresgarza** [ParsePlatform/Parse-SDK-JS#247]
The current way of resetting passwords (submitting a form, waiting for browser refresh/redirect) feels very 2004 :).

It would be great if the SDK also provided a method for resetting the password in a more "modern" way. Something along the lines of:

```js
Parse.User.resetPassword(token, username, newPassword).then(function (user) {
     // Password successfully reset
}).catch(function (error) {
     // Something went wrong
});
```

This would in turn give us developers the flexibility to handle passwords resets any way we want to.

**Comment by andrewimm** [comment]
I think you misunderstand the `resetPassword` function. It's designed for the "I'm locked out of my account" scenario, which send an email to the user with a reset link.

The thing you describe already exists. If you're already authenticated, you can just reset the password by saving a new value to it:
```js
myUser.save({password: 'newPassword'}).then((u) => {
  // password has been changed
})
```

**Comment by andresgarza** [comment]
@andrewimm I was suggesting this for the "I'm locked out of my account scenario" so that instead of actually having to submit form (for those of us with custom reset password pages), we could choose to do this in a more "AJAX-y" way. One advantage of this is avoiding the pesky "Do you want to submit this form again?" alerts.

This is why in my example I was passing the token and the username (which we would typically get from urlParams from the password reset link)

**Comment by andrewimm** [comment]
But where does that token come from? The entire point of sending it to the email is to confirm that the user owns the account in question.

**Comment by andrewimm** [comment]
Ultimately, this sounds like a request more suited to parse-server. If you wanted to implement the behavior you describe, it could be handled by a custom cloud code function. You don't need to use the provided password reset functionality -- any program authenticated with the master key can overwrite the password field.
