### ISSUE TITLE
Need algorithm used to calculate crypt passwords

### ISSUE THREAD

**Issue by marktyers** [ParsePlatform/Parse-SDK-JS#248]
After exporting the data from parse I need a way to handle login in my replacement API. This is only possible if I can reproduce how the passwords are encrypted otherwise users won't be able to log in!

**Comment by andrewimm** [comment]
The classic Parse platform uses Bcrypt, as does the open source `parse-server`.

That said, this is not an issue related to the JS SDK in any way, so I'm closing this out.

**Comment by marktyers** [comment]
Please can you direct me to the appropriate channel. Just knowing it uses crypt is not sufficient and without this knowledge porting data from the Parse platform is pointless.

**Comment by andrewimm** [comment]
It's a standard Bcrypt hash. This code from parse-server shows how it's generated / compared: https://github.com/ParsePlatform/parse-server/blob/master/src/password.js
