### ISSUE TITLE
Error when logging in from Facebook Messenger in-app browser

### ISSUE THREAD

**Issue by tristanbbq** [ParsePlatform/Parse-SDK-JS#250]
Using `Parse.FacebookUtils.logIn()` works fine for all browsers except iOS Facebook Messenger in-app browser.

Steps to reproduce:
- Open Web application from a link in iOS Facebook Messenger. App will open successfully in the in-app standalone browser instead of Safari mobile browser.
- Log in using `Parse.FacebookUtils.logIn()`

Expected behavior:
Logs in successfully as it does on all other browsers

Actual behavior:
Error: `251: Parse::InvalidSessionError`.

**Comment by andrewimm** [comment]
Interesting. I don't have any insights off the top of my head, but I'll investigate.

**Comment by tristanbbq** [comment]
@andrewimm Thanks. I'm trying to debug as well. 

Do you have documentation about how to setup `Parse-SDK-JS` to run locally? I tried usual `npm link` flow but got following error:
```
ERROR in /Users/tristan/dev/ParsePlatform/Parse-SDK-JS/index.js
Module not found: Error: Cannot resolve module 'react/lib/ReactMount' in /Users/tristan/dev/ParsePlatform/Parse-SDK-JS
```

**Comment by andrewimm** [comment]
Running the following should set everything up for a dev version:
`npm install`
`npm run build`
`npm link`

**Comment by andrewimm** [comment]
Two things to check:
First, does a normal Parse.User.logIn work in the in-messenger webview
Second, does running logOut before your logIn help? It's possible that you have an token in localstorage that's being marked as invalid when the request to auth with FB goes to the Parse server. If this is the case, we'll need some extra logic to clear all existing current-user data before attempting to auth.

**Comment by tristanbbq** [comment]
@andrewimm: 
- Parse.User.logIn: let me give it a try.
- logOut before logIn: Tried it already, does not help for this case.

**Comment by tristanbbq** [comment]
@andrewimm: so I checked your two points above:
- Parse.User.logIn in the in-messenger webview: Works fine
- Logout before Login: Does not help

**Comment by tristanbbq** [comment]
@andrewimm great, thanks for following up! 
this is quite an annoying one, as users can't login on my app if they come from a messenger in-app link 😞  - Hope we figure it out!

**Comment by tristanbbq** [comment]
@andrewimm got more details about the issue:
Facebook authentication returns a different facebook ID when it's logged in from iOS Safari mobile browser than with the iOS Messenger in-app browser:
https://github.com/ParsePlatform/Parse-SDK-JS/blob/master/src/ParseUser.js#L98

For example, for my personal facebook:
- From iOS Safari mobile, FB ID = 10152841431716507
- From iOS Messenger in-app browser: FB ID = 634836506

I'm not 100% familiar with facebook id's, but both seem to be valid, as:
- https://www.facebook.com/10152841431716507
- https://www.facebook.com/634836506
both redirect to my account.

Problem is with different ID, log in returns the error specified previously: `251: 251: Parse::InvalidSessionError`

**Comment by tristanbbq** [comment]
Interesting. 
Issue is FB.Login returns different user id from messenger in-app browser. I believe it's returning app scoped ID, and that's what's causing issue with `Parse.FacebookUtils.logIn`.
```
FB.login(function(response) {
      if (response.authResponse) {
        alert('ID: ' + response.authResponse.userID);
      } else {
        console.log('User cancelled login or did not fully authorize.');
      }
});
```

**Comment by andrewimm** [comment]
I worried it might be something like this.

The first ID is an app-specific ID. If you create an app on FB and log in, you get back an ID that is unique to you and the app, like this one.
The second ID is your universal FBID, the one that all other app-scoped ones link to.

There may not be a lot we can do here. I'll ping the team that works on messenger for iOS and see if they have any ideas.

**Comment by tristanbbq** [comment]
@andrewimm thanks, FYI, I raised this issue in facebook developers platform:
https://developers.facebook.com/bugs/1708828602735075/

**Comment by tristanbbq** [comment]
Additional detail: I just tried in the Facebook in-app browser, and it worked fine. FBID was the correct app-specific ID.
So it's really only in Messenger in-app browser that the FBID returned is wrong.

**Comment by andrewimm** [comment]
Since this is an issue related to the FB JS SDK and the Messenger in-app browser, there does not appear to be any specific problem tied to the Parse SDK. I'm closing out this issue, but I've subscribed to the FB Developers bug, out of sheer curiosity here.

**Comment by tristanbbq** [comment]
Sounds good, thanks @andrewimm :+1:

**Comment by brandonkruse** [comment]
Hey guys - having this problem as well. Thanks for looking out! Did you ever get the problem resolved @tristanbbq ?
