### ISSUE TITLE
"LiveQuery.on is not a function" on React Native 0.23.1

### ISSUE THREAD

**Issue by frantic** [ParsePlatform/Parse-SDK-JS#255]
Parse v1.8.2
React Native v0.23.1

FWIW I'm not using LiveQueries inside the app, just `require('parse/react-native')`.

![image](https://cloud.githubusercontent.com/assets/192222/14446569/6304668e-000c-11e6-81c4-e389fa239214.png)

**Comment by andrewimm** [comment]
Added the alias to `addListener` in 1.8.3.

**Comment by xcarpentier** [comment]
Hello @andrewimm,
Is it possible to use livequery in RN ?
