### ISSUE TITLE
Receiving Error 159 when trying to run cloud job

### ISSUE THREAD

**Issue by KapoorKarn** [ParsePlatform/Parse-SDK-JS#256]
This might be my specific app, so this might not be the right place (if not, i can delete this).  I am continually getting a  Error 159.  Not sure how to fix this.
![screen shot 2016-04-12 at 9 40 26 am](https://cloud.githubusercontent.com/assets/8741243/14461927/a00d341c-0092-11e6-90be-af64e3474505.png)

**Comment by carleek** [comment]
I am getting this too, when I get no results from a simple query.

**Comment by andrewimm** [comment]
Unfortunately, github issues on this repo are reserved for bugs or problems related to SDK code. I'm closing this out, since this appears to be a problem related to the legacy hosted platform.
