### ISSUE TITLE
Request failed; 60-111 Peer certificate cannot be authenticated with given CA certificates; Connection refused

### ISSUE THREAD

**Issue by jq095143** [ParsePlatform/Parse-SDK-JS#264]
My app, NUM App uses Parse.Cloud.httpRequest to authenticate users (an encoded string is passed in the header).  However, yesterday I noticed the following error was being returned when I this HTTPRequest was fired.

_Request failed; 60-111 Peer certificate cannot be authenticated with given CA certificates; Connection refused _

I haven't made any recent modifications to the code that handles this request so it appears to be a certificate issue of some kind.

**Comment by andrewimm** [comment]
Sorry, but issues on this GitHub repo are only for bugs in the JS SDK. Problems related to the platform, including the legacy Cloud Code product, can't be addressed here.
