### ISSUE TITLE
requiring unknown module "./lib/react-native/ParseReact.js".

### ISSUE THREAD

**Issue by xphaul** [ParsePlatform/Parse-SDK-JS#267]
![screen shot 2016-04-27 at 3 34 26 pm](https://cloud.githubusercontent.com/assets/12995157/14844926/94695288-0c8d-11e6-8bdb-767355c7f223.png)

package.json

![screen shot 2016-04-27 at 3 37 01 pm](https://cloud.githubusercontent.com/assets/12995157/14844969/e85372fc-0c8d-11e6-9e76-3c70b65d2442.png)

I have the same issue #239  and my parse-react is 1.6.14 . I am stuck with this error .

**Comment by andrewimm** [comment]
Looks like there was a packaging issue with the latest version of Parse+React. I'll try to rebuild it and publish a new version as 0.5.2.

That said, because this is an issue with Parse+React, not the JS SDK, I'm closing this issue.

**Comment by xphaul** [comment]
@andrewimm thanks

**Comment by andrewimm** [comment]
Published. That should resolve the issue, sorry for the mix-up.

**Comment by xphaul** [comment]
@andrewimm it works fine now thank you very much

**Comment by stage88** [comment]
Hi guys, I am getting something similar, with latest version of RN. Can you please help?

```
package.json:
  "parse": "^1.9.1",
  "react": "15.3.1",
  "react-native": "0.33.0", 
```

![image](https://cloud.githubusercontent.com/assets/9906800/18606045/b6929404-7ce6-11e6-8bef-5404c125757d.png)

![image](https://cloud.githubusercontent.com/assets/9906800/18606029/5c19e37e-7ce6-11e6-83a0-5e4ec4cecd5e.png)

**Comment by stage88** [comment]
If I down-grade to 

```
"react": "15.2.1",
"react-native": "^0.31.0",

```

everything works fine.

**Comment by playma** [comment]
@stage88 I meet the same problem and down-grade to solve it, thx

**Comment by playma** [comment]
Any one know why it is broken

**Comment by etamity** [comment]
**## i have same error, please help.**

"parse-dashboard": "~1.0.8",
    "parse-server": "~2.2.22",
    "react": "15.3.2",
    "react-native": "0.34.1",
    "react-native-code-push": "~1.14.6-beta",
    "react-native-elements": "^0.6.0",
    "react-native-vector-icons": "^2.1.0",

![simulator screen shot 3 oct 2016 21 42 00](https://cloud.githubusercontent.com/assets/3015181/19053785/4f626b3a-89b4-11e6-811d-308080d87761.png)
