### ISSUE TITLE
SSL and LiveQuery?

### ISSUE THREAD

**Issue by cheesykyle** [ParsePlatform/Parse-SDK-JS#271]
I've secured my app with SSL and everything is working as expected, aside from LiveQueries. I'm accessing my parse-server from an SSL webpage as well and receive the following error from the web console:

`https://example.com/ was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://example.com/parse'. This request has been blocked; this endpoint must be available over WSS`

So I assume this is a simple matter of LiveQueries not creating a secure WebSocket connection and providing the correct protocol. Is this something that is being worked on, or how can I ensure I have access to the live query protocol behind ssl.

Thanks!

**Comment by cheesykyle** [comment]
I've fixed this client-side for the meantime by replacing with the following at line 3653 in parse-latest.js
```javascript
if (!liveQueryServerURL) {
        var tempServerURL = _CoreManager2['default'].get('SERVER_URL');
        var protocol = 'ws://';
        if (tempServerURL.indexOf('https') === 0) {
          protocol = 'wss://'
        }
        var host = tempServerURL.replace(/^https?:\/\//, '');
        liveQueryServerURL = protocol + host;
        _CoreManager2['default'].set('LIVEQUERY_SERVER_URL', liveQueryServerURL);
      }
```

**Comment by andrewimm** [comment]
Want to submit a PR for this?

**Comment by cheesykyle** [comment]
PR Submitted!
