### ISSUE TITLE
LiveQuery doesn't do anything on Cordova

### ISSUE THREAD

**Issue by Tyler-Darby** [ParsePlatform/Parse-SDK-JS#275]
In my Cordova app, I have a simple chat system that uses livequeries to retrieve messages.

When testing the app in the browser (Chrome) it works perfectly fine. 
When building the app and running it on device, nothing happens.

Upon inspecting the console, there are no errors at all, in fact, I even manually created an entire new subscription in the console and everything executes perfectly, except that nothing happens when the livequery is fufilled. 

I can send a message to my test user on the browser and the livequery retrieves it fine, but when I reply, the livequery simply doesn't execute on my device. 

I don't think this is a cordova issue, because cordova has websocket support and there is no reason it shouldn't work there. socket.io even has a whole page of documentation for cordova that requires no special configuration which leads me to believe that it is an issue with Parse.

**Comment by Tyler-Darby** [comment]
Probably related: I just tested in Safari (desktop) as well, and I am getting the same behavior. No errors, but no results either.

Both browsers support websockets:
http://caniuse.com/#feat=websockets

**Comment by Tyler-Darby** [comment]
Ah, it is an error with Safari. 

There is a check in parse that says
```js
typeof WebSocket === 'function'
```
but in Safari WebSocket is an object.
#266 fixes this but it doesn't seem to be merged yet.

**Comment by andrewimm** [comment]
Just released 1.8.4 with the changes from #266!
