### ISSUE TITLE
Handling Exceptions with Promises/A+ 

### ISSUE THREAD

**Issue by JeremyPlease** [ParsePlatform/Parse-SDK-JS#280]
I've been running into some problems with uncaught exceptions not being reported in nested promises. I know that Promises/A bubbles up exceptions and Promises/A+ catches them, but I can't find a way to handle the caught exception.

To demonstrate, I've removed all Parse queries/saves and broken it down into a purely promise based example:

	var promise1 = new Parse.Promise();

	console.log(1);
	promise1.then(function(r) {
	  console.log(2);
	  var promise2 = new Parse.Promise();
	  promise2.then(function() {
	    console.log(3);
	    doesNotExist.go(); // this should cause an exception
	  });
	  promise2.resolve();
	  return promise2;
	}).then(function(r) {
	  console.log(4);
	}, function(e) {
	  console.log('error handler');
	  console.log('error', e);
	});

	promise1.resolve()

I would expect the output to be `1,2,3,error handler`, but instead it is `1,2,3,4` with no errors reported anywhere.

If I call `Parse.Promise.disableAPlusCompliant()` then I get the `Uncaught ReferenceError: doesNotExist` error.

So, my question is: **how can I handle uncaught exceptions with nested A+ promises?**

Thanks!

**Comment by andrewimm** [comment]
When errors occur, it's like returning a rejected Promise from the function they occur in. In your example, `promise2` is one Promise, and `promise2.then(...)` returns a _different_ Promise. That is the promise that gets rejected with your error.

In your case, `promise2` has two separate callbacks: the one that logs 3, and the one that logs 4. You can consider them running in "parallel," printing 4 does not wait for printing 3 to be resolved. What you really want to be doing is returning the Promise returned by `promise2.then()`, eg:

```js
console.log(1);
promise1.then(function(r) {
  console.log(2);
  var promise2 = new Parse.Promise();
  var promise3 = promise2.then(function() {
    console.log(3);
    doesNotExist.go(); // this should cause an exception
  });
  promise2.resolve();
  return promise3;
}).then(function(r) {
  console.log(4);
}, function(e) {
  console.log('error handler');
  console.log('error', e);
});
```

Sorry if that's a bit confusing, you can only read the word "promise" so many times before going a bit cross-eyed 😉

**Comment by JeremyPlease** [comment]
Thanks for the reply, @andrewimm. 

I think the key concept for me to remember here is that `.then(...)` returns a different promise and thus errors need to be handled on that promise.

So many "promises"... if you stare hard enough it doesn't even look like it's spelled correctly anymore 😝
