### ISSUE TITLE
ParseLiveQuery.js : currentUser.sessionToken ??

### ISSUE THREAD

**Issue by hakimdja** [ParsePlatform/Parse-SDK-JS#282]
Hi,
File: ParseLiveQuery.js  on line 75 

 return ParsePromise.as(currentUser ? currentUser.sessionToken : undefined);
should be
 return ParsePromise.as(currentUser ? currentUser.getSessionToken() : undefined);

thanks

**Comment by andrewimm** [comment]
Thanks for catching this. I've given the ParseLiveQuery code some cleanup to fix this, and bring it closer to the rest of the codebase, coding style-wise. I've also added tests for some standard cases. I'll attempt to release it as 1.8.6 later.

**Comment by hakimdja** [comment]
ok, good work
thanks
