### ISSUE TITLE
How could I use Parse-SDK-JS to point to my own Parse server

### ISSUE THREAD

**Issue by tomtomtong** [ParsePlatform/Parse-SDK-JS#283]
I have built a self-hosted Parse server. How could I connect my front-end html to this server?

**Comment by pungme** [comment]
Parse.serverURL = "http://yourserver.com/parse"

**Comment by sirnacnud** [comment]
It would be nice if the documentation was updated to mention this variable. Neither the [Javascript SDK Guide](http://parseplatform.github.io/docs/js/guide/) or [API Reference](https://parseplatform.github.io/Parse-SDK-JS/api/) mention it. I had to hunt though the github issues to find this post. Configuring the Javascript SDK for your parse-server is a integral step in setting up the Javascript SDK.
