### ISSUE TITLE
[Parse JavaScript SDK v1.6.14] query.select() with multiple pointers/includes

### ISSUE THREAD

**Issue by Tom951** [ParsePlatform/Parse-SDK-JS#284]
[Parse JavaScript SDK v1.6.14]
Hi,

Let's say I have a "match" class, with a "team1" pointer pointing to a "team" class, with a "name_label" pointer pointing to a "label" class.

In my query on a "match", if I include for instance team1 on which I include name_label:

query.include(["team1.name_label"]);

Then if I want to "select" the columns I want in the response, I need to add "className" and "__type" for each "object", else I lose the get() methods:

query.select("team1.className", "team1.__type", "team1.name_label.className","team1.name_label.__type", "team1.name_label.en_US");

so that I can call:

result[i].get("team1").get("name_label").get("en_US");

I guess this is a bug, as className and __type should be returned by default (like what is done for createdAt, updatedAt, objectId).

**Comment by andrewimm** [comment]
neither `className` nor `__type` are fields in the database, so `select`ing them won't do anything. Can you be more specific about the actual bug? You say you lose the get() methods?

Also in general, outdated versions of the SDK aren't supported. If you can reproduce the bug on the latest release, we'll look into it, but 1.6.14 is pretty old at this point.

**Comment by Tom951** [comment]
if I dont add:

query.select("team1.__type", "team1.name_label.className" (etc...) ); 

then I don't see in the JSON response coming back from Parse Server the __type and className fields.
And then, doing something like this result[i].get("team1") is undefined (and I can reach team1 with result[i].team1).

**Comment by andrewimm** [comment]
I see. So you're saying that if you include `include` and `select` on a query, the server doesn't send back the full object?

Honestly, I had no idea nested dot-notation was supported on `select` keys. Anyways, this sounds like a Parse-Server bug, not a JS SDK bug. The SDK just faithfully reproduces whatever query you've constructed on the client. It doesn't determine what comes from the server. File an issue on https://github.com/parseplatform/parse-server

**Comment by weiweitoo** [comment]
Hi there, I encounter the same problem, what is the solution?

**Comment by dplewis** [comment]
@weiweitoo That is proper behavior. Try to add `merchant` in your select. If this doesn't work, please open a separate issue.
