### ISSUE TITLE
User.logOut()   no fail success callbacks

### ISSUE THREAD

**Issue by mrt123** [ParsePlatform/Parse-SDK-JS#286]
We have success/fail callbacks for signUp() and logIn() but not for logOut()
other BAAS like hoodie will have: 
```
hoodie.account.signOut()
  .done(redirectToHomepage)
  .fail(showError);
```

We could have: 
```
        Parse.User.logOut( {
            success: redirectToHomepage,
            error: showError
        });
```

**Comment by andrewimm** [comment]
Parse.User.logOut() returns a Promise. If any step fails (fetching the current user, deleting the current user on disk, talking to the server to destroy the session token), the promise will be rejected.
