### ISSUE TITLE
Parse promise bug

### ISSUE THREAD

**Issue by GuichiZhao** [ParsePlatform/Parse-SDK-JS#295]
Parse have their own promise implementation which introduce bug in v1.8.5
I said this because the problem do not occur in older vision
In RESTController.js `installationIdPromise.then` can not work in some case,I logged out installationIdPromise as
```
ParsePromise
_rejected: false
_rejectedCallbacks: Array[0]
_resolved: true
_resolvedCallbacks: Array[0]
_result: Array[1]
"a91f4dca-873e-10c3-6839-1ea2f868ccb1"
length:1
__proto__: Object
```
next `installationIdPromise.then` can never continue
This problem happen only when I click a button which trigger a cloud function.I look through the cloud code and it turned out thing goes wrong with installationIdPromise
But the promise object look exactly the same as 'good one',so I suppose the problem lies in the then method of the implementation  

Promise is the cornerstone of the whole parse project ,please fix it !!! 

kind regards

**Comment by andrewimm** [comment]
Can you provide an example of actual code that doesn't work as intended?

**Comment by andrewimm** [comment]
Or, can you provide a test case that reliably reproduces an error? We have a pretty thorough set of unit tests which check our implementation against both the Promises/A and Promises/A+ specs: https://github.com/ParsePlatform/Parse-SDK-JS/blob/master/src/__tests__/ParsePromise-test.js

**Comment by GuichiZhao** [comment]
Could you provide your email address ? I can send the whole project to you and you just need to switch between parse v1.6.4 and parse v1.8.5 , reinstall node_module,the problem will appear

**Comment by GuichiZhao** [comment]
Or I can try to create a minimal version of the project which can reproduce the bug

**Comment by andrewimm** [comment]
Sorry, I can't take the time to look at an entire project and find the bug for you. If you can find a minimal case that reproduces the bug, that is best.

Between v1.6.4 and v1.8.5, the default behavior changed from Promises/A compliance to Promises/A+ compliance. This should only affect the way Errors are handled, but you might want to see if your code works after running `Parse.Promise.disableAPlusCompliant()`

**Comment by GuichiZhao** [comment]
OOOOps,it works !!!!!!!
I have spend several days on this !!!!
