### ISSUE TITLE
[Bug] Parse in nodejs is not throwing runtime error inside Parse.Query.get()

### ISSUE THREAD

**Issue by warrenca** [ParsePlatform/Parse-SDK-JS#297]
I was trying to debug my code for a while and thought it's my problem, but when I tried to cleanup all my logic to isolate the issue inside the Parse.Query.get() callback, I found out it's not throwing all of the runtime errors. Check my example below

```
    var Parse = require('parse/node');
    Parse.initialize(process.env.APP_ID, process.env.JS_KEY);

    var userQuery = new Parse.Query("User");
    userQuery.get("XhmDC123wh").then(function (user) {
        // askjkf fasljkfsa /* will throw a runtime error */
        console.log(undefinedvariablehere); /* WILL NOT throw a runtime error and it will stop here */
        console.log(user.get("username"));
    });
```

So the workaround I tried that worked is wrap the callback on a try/catch, but I don't find this solution necessary because you'll do a lot of parse query and you shouldn't wrap your callback in a try/catch unless it's necessary. I think it should be fixed in the core parse library. Also, a JS linter would be very helpful here but it will still not solve the problem either and not all people will use linter anyway.

```
    userQuery.get("XhmDC123wh").then(function (user) {
        try {
            // will throw undefinedvariablehere not defined
            console.log(undefinedvariablehere);
            console.log(user.get("username"));
        } catch (e) {
            console.log(e.message);
        }
    });
```

Is there a better solution to it? Is this an existing error? ty

Tried in NodeJS v5.9, v4.2, Parse v1.7.1
Edit: Same issue in Parse v1.8.5

**Comment by andrewimm** [comment]
This is how JavaScript Promises work. If an error is thrown within the body of a Promise, it doesn't bubble up to the top scope. Instead, it returns a new rejected Promise. You can read more on the topic here: http://www.html5rocks.com/en/tutorials/es6/promises/#toc-error-handling

When dealing with Promises, it is considered a best practice to end the chain of `.then()` calls with a single `.catch()` to handle any exceptions that may have occurred in the chain.

```
var userQuery = new Parse.Query("User");
userQuery.get("XhmDC123wh").then(function (user) {
    throw new Error('!');
}).catch(function(err) {
  // err === the error above
});

**Comment by warrenca** [comment]
Nice! this is working, thanks a lot!
