### ISSUE TITLE
Same Pointer ID but different _obJCount

### ISSUE THREAD

**Issue by benishak** [ParsePlatform/Parse-SDK-JS#304]
# Env
ParseServer (Selfhosted) 2.2.9
Parse SDK 1.8.5

# Problem
I try to find a row that equal a pointer in a class, but the query returns nothing ```undefined``` but I can see it really exists in Data browse, i tried to figure out what is happening by printing the two objects and got the following

```
o -> { ...., className: "books", _objCount: 34, id: 'EWdsfwXX3'}
{ ...., className: "books",  _objCount: 2, id: 'EWdsfwXX3' }
```

the difference here is only in _objCount, so when I do something like this it wont work

```
query.equalTo("book", o).first().then(
    function(book){ console.log(book) // print undefined }
)
```

why is this happening??

**Comment by andrewimm** [comment]
_objCount is a local property that is not reflected in the database. It's only used to differentiate between different instances of an object on the server. If you fetched an object twice, you would have two objects in your app's memory with different `_objCount`s, but this would not affect any pointer queries.

Are you sure that o is an instance of a Parse.Object? If it's the JSON form, that would explain why your equalTo query is failing. Additionally, you can simply use `equalTo('book', o.id)` for pointer queries.
