### ISSUE TITLE
Parse.User.logIn can resolve the request with null

### ISSUE THREAD

**Issue by mbt-jeremy-r** [ParsePlatform/Parse-SDK-JS#316]
A thing that just bitten me is that a lot of Parse JS SDK function seems to be able to resolve their Promises, but return invalid/null result.

Two example I can provide right now are Parse.User.LogIn, which on non existant user, return null instead of a error:

       Parse.User.logIn(username, password).then(
		(user) => {
			if(!user) {
				callback('No user found'); //If you don't check here, user could be null
			} else {
				callback(null, user);
			}
		},
		(error) => {
			callback(error.error, null);
		}
	);

Another example is searching throught users, which return a empty array if no match are found:

        let query = new Parse.Query(Parse.User);
	query.equalTo("username", user.email);
	query.find().then(
		(users) => {
			if(users.length === 0) {
				callback('Non existent user');
		        } else {
                                callback(null, user[0]);
                        }
               },
               (error) => {
                        callback(error);
               }
       );

I could be misunderstanding how promises work, but that doesn t really feel like the intended use. User not found / No data should reject the promise, or the documentation should make clear that in the cases X, Y or Z, like nothing found, the promise will be resolved and the develloper is responsible for handling thoses errors.

If it matter, I am using the node.js SDK.

**Comment by andrewimm** [comment]
The second case is completely by design. I'll start there, since it demonstrates how Promises should be used.
If you make an arbitrary query to a database, returning an empty result set is not an error -- the request succeeded, AND there were no results to show. The error case is for scenarios where the network failed, authentication failed, or the server produced an error.

You are correct about login though, it should not return null if login "succeds." I'll trace through that and see if I can reproduce the issue.

**Comment by andrewimm** [comment]
I can't find a way that the returned promise chain would resolve to a `null` value. Can you provide code that reproduces this?

**Comment by andrewimm** [comment]
Additionally, just to test this, I attempted a log in with a user that did not exist, and it rejected with an error as expected.

**Comment by mbt-jeremy-r** [comment]
It seems I confused the issue I had with `Query` and `Login`, I can't reproduce the error on my side.
I ll be more careful about that in my next issues.
