### ISSUE TITLE
live query sync function

### ISSUE THREAD

**Issue by lifeisfunny** [ParsePlatform/Parse-SDK-JS#320]
Do we have a live query sync function like fire base?   If not , how could we implement one?

**Comment by andrewimm** [comment]
Here is all the information on Live Queries: http://blog.parse.com/announcements/parse-server-goes-realtime-with-live-queries/

**Comment by lifeisfunny** [comment]
Ok. So it does not sync the difference when reconnect. Am I right ?

**Comment by andrewimm** [comment]
I am not sure I understand. Can you describe the scenario in greater detail?

Also note that I did not implement the livequery feature, so it is the one part of the SDK I am not intimately familiar with.
