### ISSUE TITLE
Possible Caching issue in JS SDK

### ISSUE THREAD

**Issue by rubencodes** [ParsePlatform/Parse-SDK-JS#323]
I'm on JS SDK v1.9.0. I have two Parse function endpoints, a 'setter' and a 'getter'. To illustrate the issue I'll use the User class as an example, though I encountered the issue on a different class.

I found that when I called the 'setter' API removing an attribute (let's say, for instance, setting 'firstName' to null on the user), calling my 'getter' API afterwards seemed to be returning the object as it was before I made the change. 

I figured this was a server issue, until I looked into Chrome's Network panel, and found that the 'getter' API was returning the object I expected, with the attribute removed as expected. I put in some print statements immediately after calling `Parse.Cloud.run`, and noticed that what was printing out did not match the Network panel. Specifically, I took note that, while fields that did exist both before and after the change seemed to be updated as expected (for example, updatedAt), *when a field that used to have a value the previous time I called the API was then set to null, the result returned by `Parse.Cloud.run` retained the old value*. It's important to note that the API returned correct results after refreshing, and when simply /changing/ a value. It was only when /removing/ a value by setting it to null that this issue arose.

**Comment by andrewimm** [comment]
What's the version of your Parse Server?

In early versions, there was no way to differentiate between a field being deleted and a field being reset. The absence of a field could represent that not all fields had been fetched (ie, through a `select` option on a query, or that it had explicitly been deleted.
I believe this was changed recently on Parse Server, and that explicitly-deleted fields are passed back to the client as `Delete` ops.

**Comment by rubencodes** [comment]
We were able to fix it hackily by doing `JSON.parse(JSON.stringify(result))` just before returning from the server. I checked with our backend engineer, and he says our version of ParseServer is about a month or so old, so we'll be updating ASAP to see if that fixes the issue.

**Comment by doender** [comment]
I also experience this caching, even with the Parse service, so I think it's related to the JS library.

**Comment by andrewimm** [comment]
@doender if performing `object.revert()` fixed it, it's because you had unsaved changes applied to the object.

Under the hood, each object field is constructed from two pieces of data: the last-known server value, and any local changes that have not been saved yet. If you `.get()` the attribute value, it will calculate the response by applying the unsaved change to the server data.

If you called `.set()` on a field but did not save it, then calling `.get()` will always return your unsaved value, regardless of how the server data changes underneath.

**Comment by NicksonYap** [comment]
It's now 2018 and this behavior is not well documented
It's documented here: https://parseplatform.org/Parse-SDK-JS/api/v1.11.1/Parse.Object.html#revert
But the guide has not mention of it at all
https://docs.parseplatform.org/js/guide/ 
it only mentions object.fetch()

How can the docs be improved?

**Comment by flovilmart** [comment]
The docs are open source and each section has a link to edit the docs. You can edit them on your own

**Comment by oallouch** [comment]
@NicksonYap it's very easy to edit the docs directly on github. I can be a nice first PR.

**Comment by NicksonYap** [comment]
https://github.com/parse-community/docs/pull/555
