### ISSUE TITLE
Parse.Cloud.httpRequest causing app to hang, no warnings or errors

### ISSUE THREAD

**Issue by dailenspencer** [ParsePlatform/Parse-SDK-JS#329]
The following code causes my javascript app to hang. Any ideas why? Ive looked through the documentation and github issues but cant seem to find anything. Thanks 

` Parse.Cloud.httpRequest({ url: profilePhoto.url() }).then(function(response) {
        console.log(response.buffer);
      });`

**Comment by andrewimm** [comment]
`Parse.Cloud.httpRequest` is not part of the Parse SDK, but part of the libraries provided in Cloud Code by the Parse Server. If you're still using Parse hosted services on www.parse.com`, you should follow up with them; if you're using Parse Server, you should file a bug report with them.
