### ISSUE TITLE
How does javascript sdk manage sessions and installation id?

### ISSUE THREAD

**Issue by jiawenzhang** [ParsePlatform/Parse-SDK-JS#330]
I know in Android SDK, installation_id is created the first time app is installed and launched and that installation_id does not change until user delete the app and re-install it.

For a website client using Javascript sdks, how is installation_id created? There is no concept of app install and uninstall for a web client. Is a new installation_id created every time user logs in?

**Comment by andrewimm** [comment]
installationId and the current user are saved in localStorage and persisted between each time the application is accessed. Think of the installationId like the web cookies that keep you logged into various websites, but a bit more long-lived. It only gets erased when the user or the browser explicitly clears browser data, so it should live a long time.

**Comment by benishak** [comment]
@andrewimm can you show me where is this handled in code?

**Comment by ganeshkbhat** [comment]
@benishak nice. even i was looking for the same. @andrewimm where is this handled in the code? even I am looking for this. what was the version of the Parse-SDK-JS at the tome of the question by @jiawenzhang on Aug 17, 2016?
