### ISSUE TITLE
Distinct query function

### ISSUE THREAD

**Issue by 5amfung** [ParsePlatform/Parse-SDK-JS#332]
With mongodb supporting [distinct](https://docs.mongodb.com/v3.0/reference/method/db.collection.distinct/) from version 3 and above, I wonder if there's anything technical in Parse JS SDK that would prevent implementing it.

I'm not familiar with parse js sdk.  If anyone doesn't mind pointing out which file to start, I don't mind looking into it and work for a PR.

**Comment by andrewimm** [comment]
The JS SDK is simply a piece of client code that talks with a RESTful Parse API. It knows nothing about databases or mongo. You'd need to implement this functionality in Parse Server. You should start there, and then once the feature is supported on the backend, you can implement support for the correct calls in the Query implementation of each of the client SDKs.
