### ISSUE TITLE
Help with Parse.Object.saveAll()

### ISSUE THREAD

**Issue by miracle7** [ParsePlatform/Parse-SDK-JS#333]
Hello :)

We are in the final steps of migrating from Parse.com to self hosted Parse-Server going live next week.
We are hosting it using Heroku and mLab.

I am wanting to refactor some code that used to call Parse.Object.save() on each 'score' in a list to reduce the amount of calls to our database by updating them all and then calling Parse.Object.saveAll(), so the final code would look something like this:

```
var submittedScores = request.params.scores;

var allScoresQuery = new Parse.Query('LeaderboardScore');
allScoresQuery.equalTo('user', user);

allScoresQuery.find().then(
function (serverScores)
{
    var pushPromises = [];
    var scoresToSave = [];

    // update or create scores on server
    for (var i = 0; i < submittedScores.length; i++)
    {
        var scoreFound = false;

        for (var j = 0; j < serverScores.length; j++)
        {
            // If a match is found
            if(submittedScores[i].id == serverScores[j].id)
            {
                // Set new best time
                serverScores[j].set('bestTime', submittedScores[i].bestTime);
                scoresToSave.push(serverScores[j]);

                // Send push notification to users friends
                pushPromises.push(alertFriends(request.user, newTime));

                // Stop searching
                scoreFound = true;
                break;
            }
        }

        // Create score if not submitted
        if(!scoreFound)
            scoreToSave.push(createNewScore(submittedScores[i]));
    }

    return Parse.Promise.when(Parse.Object.saveAll(scoresToSave), pushPromises);
}).then(
function (savedScores, pushResults)
{
    response.success(savedScores);
},
function (errors)
{
    response.error(errors);
});
```

However it seems that Parse.Object.saveAll does not return a Parse.Promise, instead it only supports a backbone callback object? I find this strange since almost every other function I have been using returns a Promise, and I have seen examples of people using `return saveAll(objects)` online.

JS API Documentation:
https://parseplatform.github.io/Parse-SDK-JS/api/classes/Parse.Object.html#methods_saveAll

Source Code:
https://github.com/ParsePlatform/Parse-SDK-JS/blob/03d14a068511a47a4f0922d36190de3d133b4880/src/ParseObject.js#L1282

I have tried something like this at the end of the function to work around it, but it seems sub-optimal as I have to finish sending push notifications before saving instead of doing the operations at the same time, and also I don't know how to get a backbone callback to work with the sessiontoken option I usually pass into Parse.Object.save():

```
    return Parse.Promise.when(pushPromises);
}).then(
function (pushResults)
{
    Parse.Object.saveAll(scoresToSave,
    {
        success: function(savedScores) { response.success(savedScores); },
        error: function(error) { response.error(error); },
        sessionToken: user.getSessionToken()
    });
},
function (errors)
{
    response.error(errors);
});
```

If anyone could advise me of what I am doing wrong or how I can do this better I would really appreciate it :)

**Comment by andrewimm** [comment]
`saveAll` definitely returns a Parse Promise. The issue in your code is that `Parse.Promise.when()` takes an array of Promises – `saveAll` already does the grouping of the promises for you and only returns a single promise. You can ignore the `when` bit of your code, and it should work better.

**Comment by miracle7** [comment]
Ahh okay, that would be the problem then, thanks.

Could the documentation/comments be updated to reflect what saveAll returns?

At the moment it seems to imply that there is no return value, could have saved me a lot of time.
