### ISSUE TITLE
how to create a ParseObject from json string and parse a ParseObject to json

### ISSUE THREAD

**Issue by linpf870208** [ParsePlatform/Parse-SDK-JS#337]
i want to parse a ParseObject to json string ,but i got a error "Cannot create a pointer to an unsaved ParseObject"
my code like this:

let ParagraphIns = Parse.Object.extend('ParagraphIns');
let paragraphIns = new ParagraphIns();

let Video = Parse.Object.extend('Video');
let video = new Video();

paragraphIns.set('output', video);
console.log('paragraphIns to json: ', JSON.stringify(paragraphIns));

paragraphIns.toJSON() get same error

**Comment by andrewimm** [comment]
What is your goal?

Here's the problem: to represent *in JSON* the idea that `paragraphlns` has a field that points to `video`, we need to create an object of the form `{__type: 'Pointer', className: 'Video', objectId: '...'}`
If `video` is not saved, this object cannot be created in a way that the backend can understand. To JSON stringify the association, you'll first need to ensure that `video` is saved.

**Comment by linpf870208** [comment]
@andrewimm 
OK, got it! 
my goal is convert a JSON string to a ParseObject.  i know that parse sdk has a method "fromJSON", when i create a ParseObejct by fromJSON,then save the object . i find that it can't act as expected. the result saved in mongodb hasn't any attribute. why ?

**Comment by linpf870208** [comment]
@andrewimm 

code like this
let json = {
    __type: 'Object',
    objectId: 'myid',
    name: 'John',
    className: 'Item',
    a: {
      __type: 'Object',
      className: 'Inner',
      b: 'somekey'
    }
};

json.name = 'haha';    

let obj = Parse.Object.fromJSON(json);
obj.save()....

**Comment by Simone-cogno** [comment]
I also tried to convert Parse.Object in json and save back to the server but seems to not work.
```
 //Get the object from the server
 var Home = Parse.Object.extend("Home");
 var query = new Parse.Query(Home);
 query.get("qaTGFbSkTi").then(function(home){
      var json = home.toJSON();
      json.area=234; // modify the json
      console.log(json); // Json correctly modified
      //home.set(json); // same if I use set() or save()
      home.save(json).then(function(res){ // save the modifications
          console.log(res);
       },function(err){
        console.log(err); //{code: 111, message: "This is not a valid Object"}
      });
      var object = Parse.Object.fromJSON(json);
      object.save().then(function(g){ // does not work
        console.log("passato");
        console.log(g); 
      },function(err){
        console.log(err);
      })
});
````
Json object is in the following format:
````
{
    "updatedAt": "2016-10-23T16:01:27.875Z",
    "createdAt": "2016-10-22T16:08:16.772Z",
    "volume": 180,
    "year": 1980,
    "area": 234,
    "windows": 7,
    "people": 1,
    "city": "Bern",
    "Owner": {
        "username": "test",
        "ACL": {
            "*": {
                "read": true
            },
            "OAhrAzI7HV": {
                "read": true,
                "write": true
            }
        },
        "updatedAt": "2016-10-01T14:46:16.438Z",
        "createdAt": "2016-08-08T18:39:38.834Z",
        "mqttPassword": "1231231",
        "mqttUsername": "FGTCG",
        "mqttServer": "xx",
        "name": "xx",
        "lastName": "xx",
        "location": "xx",
        "city": "xx",
        "email": "xxx@gmail.com",
        "isCoupled": false,
        "sessionToken": "r:d2f6a362d9fa1c97bc071299f1f420cc",
        "objectId": "OAhrAzI7HV",
        "__type": "Object",
        "className": "_User"
    },
    "objectId": "qaTGFbSkTi"
}
```
