### ISSUE TITLE
Using Parse SDK with Ionic 2 / Angular 2

### ISSUE THREAD

**Issue by steinroe** [ParsePlatform/Parse-SDK-JS#338]
I want to use Parse as my Mobile Backend in my Ionic 2 App. I can not get the sdk-import done.

I tried two approaches:
+ I followed the instructions in [this gist](https://gist.github.com/ciesielskico/f35a325d7509a6fe9178dc6377d97017)
Here it seems like modifying the scripts task in the gulpfile.js causes overwriting it:
```
gulp.task('scripts', function(){
  return copyScripts(
   { src: [
     'node_modules/angular2/bundles/angular2-polyfills.js', 
     'node_modules/parse/dist/parse.min.js'] 
   });
});
```
The zone.js, Reflect.js and es6-shim.min.js does not get copied now.

+ I tried the given approach [here](https://www.npmjs.com/package/parse) and after searching about the issue with require I found [this](https://forum.ionicframework.com/t/how-to-require-xyz-in-ionic2-angular2/42042/4) article. 
So I tried it with an Injectable:
```

import { Injectable } from '@angular/core';
import { Http } from '@angular/http';
import 'rxjs/add/operator/map';

import {Parse} from 'parse';

@Injectable()
export class ParseService {
private parse;
  constructor(private http: Http, parseLib: Parse) {
  	this.parse = parseLib;
  }

}
```
Sublime throws 
"module 'parse' has no exported member 'Parse'" 
and the cli throws 
"Error TS2307: Cannot find module 'parse'".

What I am trying to archive is using the sdk in Ionic 2. I installed typings for parse, too.

**Comment by cleever** [comment]
This Gist is very strange.
You don't need to change your gulpfile, nor Index.html.

Install parse normally with npm
`npm install parse --save`
Install parse typings
`typings install dt~parse --global --save`

That's all!

On your .ts files you can use parse like this:

```
import parse = require('parse');
let Parse = parse.Parse;
```


Initialize your app Parse app in the app.ts constructor:

```
constructor(platform: Platform) {
    Parse.initialize('key1', 'key2');
    Parse.serverURL = 'https://domain.com/parse';
}
```

**Comment by steinroe** [comment]
This does not work for me. But I found another solution.
After installing the package and the typings, I opened the index.js of the node-module ionic-gulp-scripts-copy and added  `'node_modules/parse/dist/parse.min.js'` to the `defaultSrc` array.
Then, in my index.html, I included the script above the cordova.js.
Now I just need to `declare var Parse: any;` in every Component I want to use the SDK in. 
For example, in my app.ts:

```
import {Component} from '@angular/core';
import {Platform, ionicBootstrap} from 'ionic-angular';
import {StatusBar} from 'ionic-native';
import {TabsPage} from './pages/tabs/tabs';

import{LoginPage} from './pages/login/login';
declare var Parse: any;

@Component({
  template: '<ion-nav [root]="rootPage"></ion-nav>',
})
export class MyApp {

  private rootPage: any;
  private parse;
  constructor(private platform: Platform) {
    //this.rootPage = TabsPage;
    this.rootPage = LoginPage;
    platform.ready().then(() => {
      console.log("Platform ready!");
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();

      Parse.initialize('myStartUp', 'someKey');
      Parse.serverURL = 'http://localhost:1337/parse';
    });
  }
}

ionicBootstrap(MyApp);
```

I do not think this is the way it should be used, but in the end I can use the SDK pretty easy and without much lines of implementation code.
