### ISSUE TITLE
LiveQuery: _this3.resolve is not a function?

### ISSUE THREAD

**Issue by mattrothenberg** [ParsePlatform/Parse-SDK-JS#346]
Howdy! I've built an app using Parse and [Ionic Framework](http://ionicframework.com/), and I've run into an issue around Parse's Live Query feature.

In one of my controllers, I'm creating a subscription like so:

```
let query = FriendRequestService.countActiveFriendRequests();
let subscription = query.subscribe();

subscription.on('create', (frq) => {
// business logic here...
});
```

While my business logic is being executed as intended, I'm getting the following error in the console. And I can't seem to track down where it's coming from. Any insights that might help put me on the right track? I'm using *Browserify* + *Babelify* to transpile all of my Angular code. 
```
TypeError: _this3.resolve is not a function
```

Thanks!

**Comment by mattrothenberg** [comment]
On deeper inspection, this is the block of code from `parse.js` where `_this3` is created

```
subscribe: function subscribe(query) {
    var _this3 = this;

    var subscriptionWrap = new _EventEmitter2['default']();

    getLiveQueryClient().then(function (liveQueryClient) {
      if (liveQueryClient.shouldOpen()) {
        liveQueryClient.open();
      }
      var promiseSessionToken = getSessionToken();
      // new event emitter
      return promiseSessionToken.then(function (sessionToken) {

        var subscription = liveQueryClient.subscribe(query, sessionToken);
        // enter, leave create, etc

        subscriptionWrap.id = subscription.id;
        subscriptionWrap.query = subscription.query;
        subscriptionWrap.sessionToken = subscription.sessionToken;
        subscriptionWrap.unsubscribe = subscription.unsubscribe;
        // Cannot create these events on a nested way because of EventEmiiter from React Native
        subscription.on('open', function () {
          subscriptionWrap.emit('open');
        });
        subscription.on('create', function (object) {
          subscriptionWrap.emit('create', object);
        });
        subscription.on('update', function (object) {
          subscriptionWrap.emit('update', object);
        });
        subscription.on('enter', function (object) {
          subscriptionWrap.emit('enter', object);
        });
        subscription.on('leave', function (object) {
          subscriptionWrap.emit('leave', object);
        });
        subscription.on('delete', function (object) {
          subscriptionWrap.emit('delete', object);
        });

        _this3.resolve();
      });
    });
    return subscriptionWrap;
  }
```

**Comment by ChrisGrant** [comment]
@mattrothenberg Did you manage to figure out what was causing this? I'm having the same issue with an Angular 2 app but can't seem to fix it.

**Comment by mattrothenberg** [comment]
@ChrisGrant I _think_ my problem stemmed from the fact that I was somehow pulling in a transpiled/minified version of the Parse JavaScript SDK into my project. When I pulled in the _real_ source, the error magically disappeared). Does that help

**Comment by ChrisGrant** [comment]
@mattrothenberg Thanks for the reply so quickly! I'm not pulling in the minified version, if I log out `query.subscribe` in the console, I get:

`function() {
      var controller = _CoreManager2.default.getLiveQueryController();
      return controller.subscribe(this);
}`

**Comment by paulovitin** [comment]
I got the same here. @ChrisGrant you find a solution for this?

**Comment by ChrisGrant** [comment]
@paulovitin Nope. Tried for a while but can't see what I'm doing wrong and I can't get it to work. Can you reopen this please @mattrothenberg ?

**Comment by mattrothenberg** [comment]
@ChrisGrant Can you perhaps link to your project so we can see what's going on?

**Comment by ChrisGrant** [comment]
Afraid not, it's not publically available right now :( 

@paulovitin have you got an example you can share? 

I can try to reproduce it sometime soon, but quite busy over the next few weeks!

**Comment by ChrisGrant** [comment]
@mattrothenberg It's been a while, but I'm back to this project and having the same issue. Did you manage to fix it?

**Comment by ChrisGrant** [comment]
@mattrothenberg @paulovitin I've managed to get it working using the advanced live query API, which is a little more work. It would still be good to know why the standard API doesn't work though.

**Comment by mattrothenberg** [comment]
@ChrisGrant I managed to resolve this issue by _not_ using a transpiled version of the Parse SDK, and rather pulling in the source directly.
