### ISSUE TITLE
Request time out and ACL issues

### ISSUE THREAD

**Issue by sumitmukhija** [ParsePlatform/Parse-SDK-JS#354]
We have been getting a lot of ACL and timeout issues since today morning. Anyone else facing the same issue?

**Comment by neowill2013** [comment]
Yes, I'm also getting the same issue

**Comment by andrewimm** [comment]
This GitHub repo is for the JavaScript SDK, not the Parse.com hosted service. Issues should be reserved for bugs with client code, not problems with Parse.com.
By this point in time, we also encourage everyone to be far along in the process of migrating off of Parse.com's hosted services, as described here: http://parse.com/migration
