### ISSUE TITLE
Request time out error

### ISSUE THREAD

**Issue by neowill2013** [ParsePlatform/Parse-SDK-JS#355]
Since morning I'm getting request time out error on parse.com

**Comment by andrewimm** [comment]
This GitHub repo is for the JavaScript SDK, not the Parse.com hosted service. Issues should be reserved for bugs with client code, not problems with Parse.com.
By this point in time, we also encourage everyone to be far along in the process of migrating off of Parse.com's hosted services, as described here: http://parse.com/migration
