### ISSUE TITLE
anyway to retrict fields using select(keys) on included objects

### ISSUE THREAD

**Issue by pjainusr** [ParsePlatform/Parse-SDK-JS#359]
Hi

I would like to restrict fields returned in Parse.Query with included objects e.g.

 var gameScore = Parse.Object.extend("gamescores");
 var query = new Parse.Query(gameScore);
 query.include("players");
**query.select("score", "players"."playername");** 
query.equalTo("objectId", "as11212121");

how can i make this work?

thanks
Pankaj

**Comment by andrewimm** [comment]
This is not supported by the server at this time. If you want to do advanced filtering of an object, you should use a cloud function, which will give you better control of what you send back.
