### ISSUE TITLE
Uncaught TypeError: this.validate is not a function

### ISSUE THREAD

**Issue by datatypevoid** [ParsePlatform/Parse-SDK-JS#361]
When trying to register a user with `Parse 1.9.2` and passing along some optional attributes, I get `parse-1.9.2.js:4986 Uncaught TypeError: this.validate is not a function`.

A simplified version of what I am attempting to do is this:

```
function registerUser(user) {

  var attrs,
      registration;

  // Store extra registration attributes
  attrs = { email: user.email };

  // Run the `Parse.User.signup` function` passing in the expected data.
  registration = Parse.User.signUp(user.email, user.password, attrs);

  // If the registration promise resolves successfully...
  registration.done(function(newUser) {
    // . . .
  });

  // If the registration promise fails...
  registration.fail(function(error) {
    // . . .
  });
};
```

It looks like this is where the problem is in `Parse`:

<img width="448" alt="48da62af6a7582345e5051d3fe9c9f18" src="https://cloud.githubusercontent.com/assets/10481547/19620654/e483c660-9836-11e6-8919-d6a8d0e1dca6.png">

Full error:

`
parse-1.9.2.js:4986 Uncaught TypeError: this.validate is not a functionvalue @ parse-1.9.2.js:4986value @ parse-1.9.2.js:9459wrappedResolvedCallback @ parse-1.9.2.js:6529value @ parse-1.9.2.js:6460(anonymous function) @ parse-1.9.2.js:6534wrappedResolvedCallback @ parse-1.9.2.js:6529(anonymous function) @ parse-1.9.2.js:6590runLater @ parse-1.9.2.js:6574value @ parse-1.9.2.js:6589wrappedResolvedCallback @ parse-1.9.2.js:6533value @ parse-1.9.2.js:6460(anonymous function) @ parse-1.9.2.js:6534wrappedResolvedCallback @ parse-1.9.2.js:6529value @ parse-1.9.2.js:6460wrappedResolvedCallback @ parse-1.9.2.js:6539value @ parse-1.9.2.js:6460(anonymous function) @ parse-1.9.2.js:10730wrappedResolvedCallback @ parse-1.9.2.js:6529value @ parse-1.9.2.js:6460wrappedResolvedCallback @ parse-1.9.2.js:6539value @ parse-1.9.2.js:6460wrappedResolvedCallback @ parse-1.9.2.js:6539value @ parse-1.9.2.js:6460(anonymous function) @ parse-1.9.2.js:6534wrappedResolvedCallback @ parse-1.9.2.js:6529value @ parse-1.9.2.js:6460xhr.onreadystatechange @ parse-1.9.2.js:10257
`

**Comment by datatypevoid** [comment]
This was due to an error in my understanding of the `Parse.User.signUp()` method when using promises. Not an issue.

**Comment by datatypevoid** [comment]
Argh, nevermind. It is apparently an error, whether by my doing or not. This is what I have now:

```
function registerUser(user) {

  var attrs,
      registration,
      newParseUser;

  // Create new `Parse` `User` object.
  newParseUser = new Parse.User();

  // Display our loading spinner.
  $ionicLoading.show();

  // Store extra registration attributes in `Object`
  attrs = { optionalAttr: 0 };

  // Set username on the `Parse` `User` object
  newParseUser.setUsername(user.email);

  // Set password on the `Parse` `User` object
  newParseUser.setPassword(user.password);

  // Set email on the `Parse` `User` object
  newParseUser.setEmail(user.email);

  // Run the `Parse.User.signup` function` passing in the expected data.
  registration = newParseUser.signUp(attrs);

  // If the registration promise resolves successfully...
  registration.done(function(newUser) {
    // . . .
  });

  // If the registration promise fails...
  registration.fail(function(error) {
    // . . .
  });
};
```

**Comment by datatypevoid** [comment]
Resolved, this was due to the way I was saving the user later on down the line.

**Comment by phoenixsachin** [comment]
i also facing this issue

Error: Uncaught (in promise): TypeError: this.validator is not a function
TypeError: this.validator is not a function
    at FormControl.AbstractControl._runValidator (http://localhost:8100/build/vendor.js:28545:38)
    at FormControl.AbstractControl.updateValueAndValidity (http://localhost:8100/build/vendor.js:28499:53)
    at new FormControl (http://localhost:8100/build/vendor.js:29017:15)
    at FormBuilder.control (http://localhost:8100/build/vendor.js:33011:16)
    at FormBuilder._createControl (http://localhost:8100/build/vendor.js:33077:25)
    at http://localhost:8100/build/vendor.js:33053:43
    at Array.forEach (<anonymous>)
    at FormBuilder._reduceControls (http://localhost:8100/build/vendor.js:33052:37)
    at FormBuilder.group (http://localhost:8100/build/vendor.js:32973:46)
    at new SignupPage (http://localhost:8100/build/main.js:34:38)


i cant find what iss the problem .
please help.

**Comment by flovilmart** [comment]
@phoenixsachin it’s unlikely your issue is related to this one, as initially this one has been closed as the original user reported a mis usage of the SDK. Also, there’s nothing in your trace that indicates it’s related to this SDK.
