### ISSUE TITLE
Migration from cloud code JSSDK 1.4 to 1.9.2 (newest)

### ISSUE THREAD

**Issue by doodyparizada** [ParsePlatform/Parse-SDK-JS#363]
I want to migrate my app from the hosted parse to the self hosted parse-server.
My current cloud code is based on JSSDK 1.4.
I need to upgrade to 1.7 to use parse-server.
This repo only has releases from 1.6.4. Are there any release notes for versions 1.4 till 1.6.4 that I can look at?

**Comment by andrewimm** [comment]
I've copied all past release notes [to the wiki on this repo](https://github.com/ParsePlatform/Parse-SDK-JS/wiki/Legacy-Release-Notes)

**Comment by doodyparizada** [comment]
thanks!
