### ISSUE TITLE
Reference to object isn't updated after query the referenced object

### ISSUE THREAD

**Issue by gfpacheco** [ParsePlatform/Parse-SDK-JS#376]
Suppose the following:

- `ClassA` has an array of `ClassB` objects (`arrayOfBs`)
- `ClassB` has a pointer to `ClassC` object (`pointerToC`)
- I need the `ClassC` object inside the `beforeSave` of the `ClassA`

This is what I tried:

```javascript
Parse.Cloud.beforeSave('ClassA', (req, res) => {
  const a = req.object;
  const bs = a.get('arrayOfBs');
  new Parse.Query('ClassB')
    .include('pointerToC')
    .containedIn('objectId', bs)
    .find()
    .then((bsFound) => {
      console.log(bsFound[0].get('pointerToC')); // logs the ClassC object
      console.log(bs[0].get('pointerToC')); // logs undefined

      console.log(bs[0]); // ParseObject { className: 'ClassB', _objCount: 4, id: 'JEHtYTPtt5' }
      console.log(bsFound[0]); // ParseObject { className: 'ClassB', _objCount: 13, id: 'JEHtYTPtt5' }
    });
});
```

Why is that the `ClassB` objects found are different (not the same JS Object) from the ones referenced by `a`?

**Comment by gfpacheco** [comment]
Any help on this?

**Comment by gfpacheco** [comment]
Guys?! Can you tell me if this is a real issue? Is there any workaround I can use for now?!

**Comment by andrewimm** [comment]
This behavior is intended. When you're executing in a cloud function, objects don't automatically update when they are fetched again from a separate query. This is to maintain memory safety: if you were executing two cloud functions on the same object simultaneously, you would not want changes in one to be reflected in the other. This behavior is also true of any node.js application.

If you have an object and want to update it to the latest version, you can call `.fetch()` on it to guarantee it gets the latest fields. You could rewrite your function like so to get the latest version of each:

```
Parse.Cloud.beforeSave('ClassA', (req, res) => {
  const a = req.object;
  const bs = a.get('arrayOfBs');
  // Wait on all bs to fetch
  Parse.Promise.all(bs.map((b) => b.fetch()).then(() => {
    // use the updated bs array
  });
});
```

**Comment by gfpacheco** [comment]
I get the memory safety concern. But there's no way to use `fetch` and `include` together, right? In that case I'll have to do:

```javascript
Parse.Cloud.beforeSave('ClassA', (req, res) => {
  const a = req.object;
  const bs = a.get('arrayOfBs');
  // Wait on all bs to fetch
  Parse.Promise.all(bs.map(b => b.fetch()).then(() => {
    return Parse.Promise.all(bs.map(b => b.get('pointerToC').fetch()));
  }).then(() => {
    // Now I can use all the references I have
  });
});
```

And things get exponentially worse when C has another pointer or array of objects that needs to be included.
