### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by VolvoOlympian** [ParsePlatform/Parse-SDK-JS#38]
I am querying some data using the JS SDK. It has been working for me however today when I run it again I get no data returned but the following in console:
`XMLHttpRequest cannot load https://api.parse.com/1/classes/MyClass. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.0.108:8100' is therefore not allowed access. The response had HTTP status code 502.`

But I have changed nothing in my code or on the Parse core...

**Comment by JacobCorlett** [comment]
Same problem.

**Comment by VolvoOlympian** [comment]
When does this start happening to you?
By the way, Parse.com's service status is now `Investigating - We are experiencing elevated error rates for some applications. `
I wonder if that is related to the problem.

**Comment by JacobCorlett** [comment]
I wasn't in the office, By my colleagues have said around 1 - 2 hours ago. 90% of queries are failing by the look of it.

No code of the app has been changed in a good few weeks.

**Comment by VolvoOlympian** [comment]
I see, for me even a simple query(not nested or with any "where"s) fails for most of the time.

**Comment by JacobCorlett** [comment]
I think it must be down too Parse.com's service status as Now even loading data directly through there interface isn't working for me. So I doubt this is a JS SDK error and just there side.

**Comment by VolvoOlympian** [comment]
Yes, their backend is not working for me now either...

**Comment by JacobCorlett** [comment]
Working. Must have been that service error.
