### ISSUE TITLE
Prevent "require('parse/node') instead" warning on server side rendered applications.

### ISSUE THREAD

**Issue by fdidron** [ParsePlatform/Parse-SDK-JS#383]
Hi,

I'm currently building a React application using Parse as the backend. The application is server side rendered, so on the initial render (happening on the server side) the process logs the following warning (as per this [line](https://github.com/ParsePlatform/Parse-SDK-JS/blob/2956decbe54f2cf6d2c17ff1b4d8db98327410d6/src/Parse.js#L33)):
```
It looks like you're using the browser version of the SDK in a node.js environment. You should require('parse/node') instead.
```
One solution to prevent that would be to check in the same line if a process.env variable exists, for example `process.env.SSR !== true`.
Happy to send a PR if this makes sense.

**Comment by andrewimm** [comment]
Sure, I can understand there are cases where the warning isn't useful, and should be capable of being hidden.
`SSR` sounds a bit too obscure, let's be verbose with process.env.SERVER_RENDERING and just check its truthiness (so users can run `SERVER_RENDERING=1 node server.js`). Happy to accept a PR.

**Comment by fdidron** [comment]
PR done !

**Comment by johhansantana** [comment]
btw, when I try to do `import Parse from 'parse/node'` I get dependency error
<img width="387" alt="screen shot 2017-02-08 at 6 15 20 pm" src="https://cloud.githubusercontent.com/assets/9933887/22759917/964e7388-ee2a-11e6-912f-176d378fe75c.png">

**Comment by andrewimm** [comment]
@johhansantana those are all modules that ship as part of Node.js, and none of them are dependencies of Parse. You should look at your other code to see what's attempting to pull them in.
