### ISSUE TITLE
Huge dependencies chain (filesize)

### ISSUE THREAD

**Issue by neophob** [ParsePlatform/Parse-SDK-JS#398]
Hi

I checked the largest dependencies of my project:

```
6.9M	/app/node_modules/core-js
1.0M	/app/node_modules/babel-runtime
1.9M	/app/node_modules/parse
```

`parse` requires `babel-runtime`, which requires `core-js`. I would like to create a parse sdk version without babel-runtime dependency to save space on the target device. 

whats the reason for using babel-runtime? the library can used on most recent node platform? are there other advantages?

**Comment by andrewimm** [comment]
If you're employing any kind of minification when deploying your app, these files don't actually take up nearly as much space as you see here. The node_modules dir might be large, but I can't think of a scenario where you'd actually deploy that code, uncompiled, to a device. But even if that's still too much for you, we offer precompiled versions of the SDK, which are available on the releases page of this repo, or within the /dist/ directory of the npm module.

The reasons for using it are a) to allow some of the more complex syntax of the SDK to run on a wide variety of platforms (FF and IE are supported going very far back), and b) to ensure that any polyfilling doesn't get duplicated and take up extra disk space – if your project also uses babel to compile, your project will only ever import the runtime package once.

Hope that addresses your concerns.

**Comment by neophob** [comment]
thanks @andrewimm for the update, however I guess there is a misunderstanding. I'm talking about a node project where the node_modules is not touched, so all dependencies from the packages.json file are installed unmodified. So the parse js sdk uses about 10mb mainly because of the babel runtime dependency. so my question is, are there any options to deploy a minified parse js sdk to npm, which has support for node > 4.0?

10mb sounds maybe not huge, if you want to use parse on a constraint device it makes quite a difference though.
