### ISSUE TITLE
query.select() is ignored with version 1.6.4

### ISSUE THREAD

**Issue by neolution** [ParsePlatform/Parse-SDK-JS#41]
In the following code the "query.select" will be ignored with version 1.6.4, but works in version 1.5.0.
```js
var Objekt = Parse.Object.extend("objekt");
var query = new Parse.Query(Objekt);
query.select("title");
query.find({
  success:function(results) {
for (var i = 0; i < results.length; i++) {
      var object = results[i];
      console.log(object.id + ' - ' + object.get('title'));
    }
  }
});
```

**Comment by wangmengyan95** [comment]
Hi @neolution, I do not quite get your point. What do you mean by will be ignored?
Ideally, your code should always print the id and title. You mean in 1.5.0 it works fine but in 1.6.4 you can not see the title?

**Comment by neolution** [comment]
@wangmengyan95 : Yes, with 1.6.4 I always get all fields from the class although I set **query.select("title");**. With 1.5.0 I only get the "title" => this is the expected behaviour,

**Comment by andrewimm** [comment]
@neolution can you look at the actual network request back-and-forth to api.parse.com, and copy any relevant information here?

You should see a payload go out with the `"keys"` field set -- this is where we send the data from calling `.select()` on a query. Then, take a look at the response, and see if the server is actually sending all the data back.
JS SDK 1.6 features single instance objects -- that is, any two instances of the same object share the same attributes in memory. If you had a full copy of an object locally, and then queried for another copy of it, the new copy would be inflated with all the locally known fields. `.select()` is useful for reducing the number of bytes sent over the wire, but we intentionally don't create an object with fewer attributes.

**Comment by neolution** [comment]
@andrewimm : You are right. If I previously run the query without `query.select(..)` and afterwards I set `query.select("title")` and run the same query again all fields are available.
But if I first run `query.select("title")` then I only get the selected keys.

Thank you for your help. I could not read this out of the documentation.
