### ISSUE TITLE
Parse 1.6.X does not return values for all columns on query.find

### ISSUE THREAD

**Issue by sewillia** [ParsePlatform/Parse-SDK-JS#42]
I tried to use Parse.1.6.2 and 1.6.4 today but found the when calling query.find.., objects were returned with only the classname and objectId info. All other columns were absent. Eg.

var Plan = Parse.Object.extend("Plan");

var query = new Parse.Query(Plan);
    query.equalTo("user", Parse.User.current());
    query.find({
        success: function(allPlans) {
            console.log(allPlans);
           ...
        },
        error: function(err1, err2) {
            console.log(err1,err2);
        }
    });

In the success callback the collection printed to the console only contains objectId and className keys.

Is this a bug with the newer versions of this SDK or am I missing something?

**Comment by andrewimm** [comment]
The objects have all of their attributes, they just won't show up on a console.log.

Attributes are available as a map on a non-enumerable value, `.attributes`. If you do the following, you should see the attributes for each object:
```js
allPlans.forEach(function(plan) {
  console.log(plan.attributes)
});
```

You'll notice that in versions prior to 1.6, console.log printed out a bunch of noise and information that complicated debugging (such as listing each object as type `c`). The new response to console.log is designed to be more straightforward.

**Comment by sewillia** [comment]
I am more than a little late but thank you!
