### ISSUE TITLE
adding the ability to listen to changes of the current user on different browser tabs

### ISSUE THREAD

**Issue by oriSomething** [ParsePlatform/Parse-SDK-JS#45]
on older versions (`Parse JS SDK <= 1.5.0`), i've used this hack (in the browser):
```js
// Detect Parse session change in another tab
const STORAGE_KEY = `Parse/${Parse.applicationId}/currentUser`;

addEventListener('storage', function({ key, storageArea }) {
  if ((storageArea === localStorage) && (key === STORAGE_KEY)) {
    Parse.User._currentUser = null;
    Parse.User._currentUserMatchesDisk = false;
    Parse.User._currentAsync()
      .fail(Parse.Promise.as)
      .then(function() {
        // ··· dispatch changed event if needed
      });
  }
}, false);

```

i think this ability can be useful for everyone, because it's nice when an app reacts to a session change in all tabs instead of seeing outdated version in another tab.

i think it this ability need a proper API rather than workaround. i understand it's also a tricky thing to implement because of the different platforms, but i can be possible if we extend `ParseUser` class and `SessionController`.

the ~~bug~~ feature of `storage` event is that it only dispatches when the change happened on another tab's / window's `Storage` object. what make this feature easier to apply.

**Comment by ljs19923** [comment]
@oriSomething 7years later I have the same problem. Do you know if something has been created? or I have to use this workaround
