### ISSUE TITLE
Error on Before Save and After Save at cloud code

### ISSUE THREAD

**Issue by manishnath** [ParsePlatform/Parse-SDK-JS#46]
Using this code on beforeSave and afterSave methods, saves a blank row with no data :
```javascript
Parse.Cloud.beforeSave(Parse.Object.extend("Look"), function(request,response) {
	 // Set up to modify user data
 	alert("Calling before save for look");

	//For Expiring a look when look marked rejected
	for (var i in request.object.dirtyKeys()) {
		 	alert("Calling before save for look 1");

  		var dirtyKey = request.object.dirtyKeys()[i];
  		alert("dirty key for look aftersave"+dirtyKey);
 		if(dirtyKey == "eventState" && request.object.get("eventState") == 2){
 			//Also expire this look
 			request.object.set("expired",true);
 			alert("Look expired");
			
			var pushQuery = new Parse.Query(Parse.Installation);
 			var userIdQuery = new Parse.Query(Parse.User);
			var message = "Your look has been rejected by the event administrator.";
			var fromUser=request.object.get("fromUser");
			
			userIdQuery.equalTo("objectId", fromUser);

			pushQuery.matchesQuery('user', userIdQuery);
			Parse.Push.send({
					where: pushQuery,
					data: {
						alert: message,
						type:"lookRejected"
					}
			}, {
				success: function() {
					alert("Push went successfully For Look Rejection!");
				},
				error: function(error) {
					alert("Error executing: " + error.code + " " + error.message);
				}
			});

 		}
 	}

 	response.success();

});


Parse.Cloud.afterSave(Parse.Object.extend("Look"), function(request) {
	 alert("Calling before save for look");

	var userId = request.object.get("fromUser");
	var inappropriate = request.object.get("inappropriate");
	var like = request.object.get("likes");
	var dislike = request.object.get("dislikes");
	var pushQuery = new Parse.Query(Parse.Installation);
	var userIdQuery = new Parse.Query(Parse.User);
	var message = "The results are in! See what people think of your latest look.";
	var typeObj="like";
		 alert("Calling before save for look 1");

	if(typeof dislike != "undefined"){
		like = like + dislike;
	}
	userIdQuery.equalTo("objectId", userId);
	userIdQuery.equalTo("lookResponse", like);

	
//	if(typeof inappropriate != "undefined" && inappropriate != '' && inappropriate){
//		message = "Your look has been marked inappropriate!!";
//		typeObj="inappropriate";
//	}else{
//		userIdQuery.equalTo("lookResponse", like);
//		message = "Hey! your looks are fetching likes!"
//		typeObj="like";
//	}

		 alert("Calling before save for look 2");

	pushQuery.matchesQuery('user', userIdQuery);
	Parse.Push.send({
			where: pushQuery,
			data: {
				alert: message,
				type:typeObj
			}
		}, {
			success: function() {
				alert("Push went successfully!");
			},
			error: function(error) {
				alert("Error executing: " + error.code + " " + error.message);
			}
	});


});
```

**Comment by wangmengyan95** [comment]
Hi @manishnath, thanks for your code snippet. Is it possible for you to figure out which part of your code does not work? If not, could you copy paster your logs? Thanks.

**Comment by manishnath** [comment]
Hello Mengyan,
The problem is that when I uncomment the beforesave method it does not give
any logs. This is happening only on Ios and not Android whereas both are
following same saving pattern. The issue is in the beforesave method only -
but even if I comment the entire method , it does not work.
I hope that gives you something to work with.
Regards,
Manish

**Comment by wangmengyan95** [comment]
Hi @manishnath, it is very helpful for us to know the `beforeSave` does not work well in your case. But it seems you do lots of stuffs in `beforeSave`, like loop `dirty keys`, do `ParseQuery` and send pushes. Is it possible for you to tell use which part of the `beforeSave` does not work?

**Comment by manishnath** [comment]
Hey , Thanks for responding. The issue is that this code is working for
Android but not for iOS. Both platforms are using same query mechanism.
Using this same code in afterSave works beautifully. Also I am unable to
print any logs so cant pin point where the problem lies :(

On Wed, Oct 14, 2015 at 1:36 AM, Mengyan Wang <notifications@github.com>
wrote:

> Hi @manishnath <https://github.com/manishnath>, it is very helpful for us
> to know the beforeSave does not work well in your case. But it seems you
> do lots of stuffs in beforeSave, like loop dirty keys, do ParseQuery and
> send pushes. Is it possible for you to tell use which part of the
> beforeSave does not work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParsePlatform/Parse-SDK-JS/issues/46#issuecomment-147836852>
> .
>



-- 
MANISH NATH

**Comment by wangmengyan95** [comment]
Hi @manishnath, 
1. What do you mean you can not print any logs? If `alert` does not work, could you try to replace `alert` with `console.log` to see what happens?
2. It seems your cloud code does not return any value to clients, so what do you mean this code is working for Android but not for iOS? Android can receive the push but iOS can not?

**Comment by manishnath** [comment]
1. It works when I put the same code in afterSave
2. When I put this code in beforeSave  - The same code works when a save
query is made from Android but not from iOS
I can check by putting console.log

On Wed, Oct 14, 2015 at 11:26 PM, Mengyan Wang <notifications@github.com>
wrote:

> Hi @manishnath <https://github.com/manishnath>,
> 1. What do you mean you can not print any logs? If alert does not work,
> could you try to replace alert with console.log to see what happens?
> 2. It seems your cloud code does not return any value to clients, so what
> do you mean this code is working for Android but not for iOS? Android can
> receive the push but iOS can not?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParsePlatform/Parse-SDK-JS/issues/46#issuecomment-148135773>
> .
>



-- 
MANISH NATH
