### ISSUE TITLE
Parse.Config in Cloud Coude

### ISSUE THREAD

**Issue by Neilpoulin** [ParsePlatform/Parse-SDK-JS#49]
I don't seem to be able to get my Config object when calling Parse.Config in cloud code. I understand that the .get() method is asynchronous, and so may not be retrieved at the time of an HTTP request, but I figured I should be able to make a Config object a class variable, and set it on the success callback of the get() method. 

From my testing, I don't seem to ever hit my callback (success or error) when calling Parse.Config.get()

Is this intended behavior? I am able to manage my Config object in client-side Javascript with no problems.

**Comment by andrewimm** [comment]
Can you please provide an example of code that does not work as intended?
