### ISSUE TITLE
include bug

### ISSUE THREAD

**Issue by swilli40** [ParsePlatform/Parse-SDK-JS#51]
toJSON has different implementations giving expanded include (correct) and non expanded include (not correct)

>>>>   json[attr] = (0, _encode2['default'])(attrs[attr], false, true);
(https://parse.com/docs/downloads  -- also the version i think is working in parse hosting)

means that pointers are not expanded, but NPM version of parse is

>>>>   json[attr] = (0, _encode2['default'])(attrs[attr], false, false);
(https://github.com/ParsePlatform/Parse-SDK-JS)

above works in local debug but on cloud it breaks....

key: 'toJSON',
            value: function toJSON() {
                var json = {};
                var attrs = this.attributes;
                for (var attr in attrs) {
                    if ((attr === 'createdAt' || attr === 'updatedAt') && attrs[attr].toJSON) {
                        json[attr] = attrs[attr].toJSON();
                    } else {
                        json[attr] = (0, _encode2['default'])(attrs[attr], false, true);
                    }
                }
                var pending = this._getPendingOps();
                for (var attr in pending[0]) {
                    json[attr] = pending[0][attr].toJSON();
                }

                if (this.id) {
                    json.objectId = this.id;
                }
                return json;
            }

**Comment by andrewimm** [comment]
This was a temporary bug that was fixed in 1.6.6, which is the current version on the repo. We only just finished this, and it takes some time to deploy to our downloads page and the cloud code environment. Please follow issue #32, where we'll be posting when 1.6.6 has been rolled out to the cloud code fleet.
