### ISSUE TITLE
URL's not available through JS API

### ISSUE THREAD

**Issue by yarnball** [ParsePlatform/Parse-SDK-JS#52]
I am using the Javascript API to enable users to share an object from the app. This creates a sharable link.

What is failing? 

It doesn't receive the "link" column/data (which is a string). All other columns come through fine (such as files, numbers, and other strings). Here is  a sample of my site linking to an object in Parse- http://www.stashdapp.com/products/#/SpFc5SvaQR

Is there a trick with Parse and sharing URL's?

My HTML is fine, I"ve pasted my javascript is here http://pastebin.com/wp0n4tNm

**Comment by wangmengyan95** [comment]
Hi @yarnball, I test your URL with my ParseObject and it works fine. So do you get any exception or error message when do the query?

**Comment by yarnball** [comment]
Was a markup error on my part- thanks. Closed
