### ISSUE TITLE
Unable to login using js sdk

### ISSUE THREAD

**Issue by chocstarfish** [ParsePlatform/Parse-SDK-JS#53]
I was trying to login a user using following code from the [docs](https://parse.com/docs/js/guide#users-logging-in):
```
<script src="http://www.parsecdn.com/js/parse-latest.js"></script>
```
```
Parse.User.logIn("myname", "mypass", {
  success: function(user) {
    // Do stuff after successful login.
  },
  error: function(user, error) {
    // The login failed. Check error to see why.
  }
});
```
The server returned 404 and the response was
```
{"code":101,"error":"invalid login parameters"}
```
I also found out that the [sample todo app](http://todolist.parseapp.com) also has this issue.

Is there anything wrong with the login service?

**Comment by wangmengyan95** [comment]
Hi @chocstarfish, this exception means your username or password is incorrect, could you make sure this user exists in your data browser?

**Comment by chocstarfish** [comment]
Thank you @wangmengyan95 ! I in fact used the wrong credentials, but it would be easier to understand if the server return a more specific error message. Closing this.

**Comment by rayfranco** [comment]
Digging up this issue because I had the same struggle, the guide leads us wrong. There is no `user` parameter passed to the callback (which makes sense) so you should just do this:

```javascript
error: function(error)
```

instead of:

```javascript
error: function(user, error)
```
