### ISSUE TITLE
Issues retreiving cached cookie in IE 10 and below

### ISSUE THREAD

**Issue by shane935** [ParsePlatform/Parse-SDK-JS#54]
I am getting the following error on IE10 and below when I attempt to retrieve a cashed user object or make any parse query

Object doesn't support property or method 'fromJSON'

the issue seems to be coming from line 832 in ParseUser.js 

```
var current = ParseUser.fromJSON(userData);
```

**Comment by shane935** [comment]
I have been doing some debugging this morning so here is a little more information.

The issue appears in version 1.6.* I fixed it by moving back to 1.5.0

the *fromJSON* method is not being added to the **ParseObject prototype** I noticed that by moving the *fromJSON* object further up the *_createClass(ParseObject, [{...* array It began to appear on the **ParseObject prototype**

**Comment by andrewimm** [comment]
Hmm, sounds like it might be an issue with the Babel compilation. I'll have to spin up a windows VM and take a look

**Comment by rubencodes** [comment]
Having the same issue here, any progress?

**Comment by andrewimm** [comment]
Due to https://github.com/babel/babel.github.io/blob/862b43d/docs/advanced/caveats.md#classes-10-and-below

I've rewritten `ParseUser.fromJSON` to `ParseObject.fromJSON` and tests continue to pass. It'll be released in 1.6.14

**Comment by andrewimm** [comment]
Released 1.6.14
