### ISSUE TITLE
dotted includes not returning from toJSON

### ISSUE THREAD

**Issue by swilli40** [ParsePlatform/Parse-SDK-JS#55]
1.6.6 resolves the problem with includes, but dotted includes such as myObject.createdUserRef does expand myObject, but doesn't expand createdUserRef pointer. extension of bug #32

**Comment by andrewimm** [comment]
I believe this is fixed in da47720683c1f76caec207e1eec45357030b3595

**Comment by swilli40** [comment]
Don't think it's fixed.
