### ISSUE TITLE
Saving a new ParseObject at another object's beforeSave() retriggers that other object's beforeSave resulting to an infinite loop

### ISSUE THREAD

**Issue by mkpazon** [ParsePlatform/Parse-SDK-JS#58]
I have 2 classes named Item and Notification.

In Item's beforeSave() I check if there is a new relation added to it called "queue" if there is then I create a new Notification object with one of its fields points to that Item. This results to an infinite loop wherein  Item's beforeSave() is called multiple times creating several Notification objects in the database.

**Comment by andrewimm** [comment]
This sounds like an implementation issue, not an issue with the SDK. beforeSave triggers are simply guaranteed to run whenever an object is saved, with the opportunity to modify or prevent the save operation. I'm not sure this falls in the scope of the SDK.

I'd like to know, though, how you'd like your cloud code to behave in the scenario you outlined.

**Comment by mkpazon** [comment]
I don't see at what point the Item#beforeSave is triggered again. I am simply creating a Notification object which saves a field Pointer<Item> to it whenever a relationship "queue" is created.

I am expecting the following flow:
1. Item#beforeSave() is triggered because of a new relation "queue" will be created
2. Still in Item#beforeSave(), create a Notification object storing other objects including the Item object
3. Item#beforeSave should not be called again
