### ISSUE TITLE
Maximum call stack size exceeded error after upgrading from 1.5.0 to 1.6.2

### ISSUE THREAD

**Issue by jasonhutchens** [ParsePlatform/Parse-SDK-JS#6]
ref: https://developers.facebook.com/bugs/1478633002464123/

We have just upgraded from 1.5.0 to 1.6.2. ParseUser has a pointer to a Profile for that user, and the Profile has a pointer back to the ParseUser it belongs to. When the user logs out and logs back in again (i.e. you call `Parse.User.logIn(...)` and then `Parse.User.logout` and then `Parse.User.logIn(...)` again), we get this error:

![screen shot 2015-09-22 at 09 21 52](https://cloud.githubusercontent.com/assets/38485/10009174/6ecd977e-610b-11e5-9c46-3f31de95839b.png)

What's happening is that when `Parse.User.logIn` is called, `setCurrentUser` calls `user.toJSON()`. The first time this happens, `encode` is called on the `Profile` pointer in the user object, and this encodes the `Profile` object by returning `value.toPointer()`. However, when I log out and log back in with the same user, this doesn't happen, because when `getState` is called for the `Profile` object,  both the `objectCache` and `serverData` elements of the state object contain values. So when `encode` is called on the `Profile` pointer, `value._getServerData()` returns some content, and so it isn't encoded using `value.toPointer()`. This is where the fatal recursion kicks off.

I can work around this issue by calling `Parse.Object._clearAllState()` after `Parse.User.logOut`. Can you advise whether this work-around is sufficient for us to upgrade to 1.6.2, or would there be potential undesirable side-effects?

**Comment by andrewimm** [comment]
Calling `_clearAllState()` is risky, since it will essentially un-fetch all objects. I'm actively looking into this.

**Comment by andrewimm** [comment]
Should be fixed with #7

**Comment by jasonhutchens** [comment]
:+1: thanks @andrewimm, we look forward to the next release :)
