### ISSUE TITLE
React Native save - object not updated in storage

### ISSUE THREAD

**Issue by bogdantmm92** [ParsePlatform/Parse-SDK-JS#62]
I'm using Parse/react-native library.

Steps:
I do some modifications to current user:
```
user.set("visible", value);
return user.save();
```
Parse.User.current() and Parse.User.currentAsync() are correctly updated.
In Data Browser the change is also updated.

I do a force close of the app, and when I enter again and fetch Parse.User.curretAsync(), the changes I previously made are gone.

Let me know if you need more informations to reproduce. Thanks!

**Comment by andrewimm** [comment]
I'm merging this into #65 as it doesn't only affect RN apps. Please continue the discussion there.
