### ISSUE TITLE
Relation data not retrieved in subquery

### ISSUE THREAD

**Issue by estock** [ParsePlatform/Parse-SDK-JS#63]
I have the following code

```
for (var i = 0; i < events.length; i++) {
                  var event = results[i];
                  var relation = event.relation("Artists");

                  var query3 = relation.query();
                  query3.find({
                    success: function(results) {
                      console.log("Successfully retrieved " + results.length + " results.");
                      if(results.length >0)
                      {

                      }
                    },
                    error: function(error) {
                      console.log("Error: " + error.code + " " + error.message);

                    }
                  });
                } // End For Loop
```

events is returned from the another query, eveything works, but the relation object that is retrieved, is always empty (length 0). I think this is a bug in the code ... I'm using the latest SDK in Node

**Comment by wangmengyan95** [comment]
Hi @estock, I test with ParseObject A contains a relation to another ParseObject B. I query ParseObject A first and then use the relation query to query ParseObject B. It works fine.
So in your case
1. Could you tell me how do you get the `events`?
2. Could you repo this bug by using our REST api?
