### ISSUE TITLE
How to return array of Parse Objects instead of array of pointers in Cloud Code?

### ISSUE THREAD

**Issue by d370urn3ur** [ParsePlatform/Parse-SDK-JS#67]
I perform a query and get an array of parse objects. But when I try to return them using response.success(results), they get converted into just pointers. Here is the log just before I call response.success(results):
```
[{
      "ans1Goals": 1,
      "ans2Goals": 2,
      "ansSpectators": 21400,
      "createdAt": "2015-10-05T11:00:38.447Z",
      "position": 1,
      "updatedAt": "2015-10-27T10:18:55.294Z",
      "objectId": "39QCu6oTBx"
    }]
```

and this is what I receive from calling response.success(results):
```
    [{
      "__type": "Pointer",
      "className": "Answers",
      "objectId": "39QCu6oTBx"
    }]
```
Why is this happening?  On the client side, iOS and Android, we need the parse objects, otherwise with the pointers we will have to make another request to fetch the data.  I don't want to return JSON because we have subclassed parse objects in iOS and Android and this should happen automatically, just like when we make queries directly from the clients.  Having to parse JSON into ParseObjects defeats the purpose of subclassing in the first place.  Thanks for any insight!

**Comment by wangmengyan95** [comment]
Hi @d370urn3ur, we do not send the nested ParseObject's full data to cloud code. In order to get the data of the nested ParseObject, you have to do a query or fetch. The result you get from cloud code is pretty similar to the result you get from ParseQuery. We represent nested ParseObject as pointer and you have to fetch or query it in order to use it.

**Comment by roddylindsay** [comment]
in the JS SDK 1.5.0 you could call `object._toFullJSON(["HACK"])` which would include the complete object and any nested children.  Haven't tried it on 1.6.

**Comment by d370urn3ur** [comment]
@wangmengyan95 I'm not worried about nested objects now.  I want an array of top level parse objects.  Let's say I have an object Car like
```
{
"objectID": "1234",
"color": "red",
"className": "Car",
"__type": "Object"
}
```
 If I do a query and get all of the Car objects in the database, the results of this query should be an array of Car parse objects.  So what you're saying is that if I call response.success(carResults), then I should receive an array of Car Parse Objects at the client.  Specifically for iOS a Car subclass of PFObject.  But that is not what is being sent by response.success(carResults).  Instead of
```
[ { 
"objectID": "1234"
 "color": "red"
"className": "Car",
"__type": "Object"
} ]
```
```
I get this:
[{
"objectID": "1234",
"className": "Car",
"__type": "Pointer"
}]
```

So if I want to get the information for this object, I have to call fetch.  It's not normal, I am performing one request to get an array of objects and then a request for each object to fetch the rest of the data.  request.success() is modifying the carResult and converting the objects into pointers.  I don't know if its supposed to work like that or not, it seems like a bug to me.  This kind of workflow doesn't make any sense, the goal is to minimize the number of network requests.

**Comment by andrewimm** [comment]
Which version of the SDK are you using with Cloud Code? There was an issue with this, but it has since been resolved.

**Comment by d370urn3ur** [comment]
I was on latest, so theoretically 1.6.7.  I manually specified 1.6.7 just in case, and now it is working.  I don't know what latest is pointing to but that seems to have been the problem.  Thanks you guys for your help!
