### ISSUE TITLE
Parse Server SSL Error on query.find calls

### ISSUE THREAD

**Issue by arethtapslots** [ParsePlatform/Parse-SDK-JS#68]
I am getting a connection refused error when making a find query with the NodeJS parse-sdk npm module. See error below:

   ParseError {
     code: 107,
     message: 'Received an error with invalid JSON from Parse: Error: connect ECONNREFUSED 54.88.70.3:443\n  at Object.exports._errnoException (util.js:874:11)\n  at exports._exceptionWithHostPort (util.js:897:20)\n  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)\n' },

When I put 54.88.70.3 in a browser there appears to be an SSL error.

Here is another:
   ParseError {
     code: 107,
     message: 'Received an error with invalid JSON from Parse: Error: connect ECONNREFUSED 54.210.169.69:443\n  at Object.exports._errnoException (util.js:874:11)\n  at exports._exceptionWithHostPort (util.js:897:20)\n  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)\n' },

And another:
   ParseError {
     code: 107,
     message: 'Received an error with invalid JSON from Parse: Error: connect ECONNREFUSED 52.2.192.194:443\n  at Object.exports._errnoException (util.js:874:11)\n  at exports._exceptionWithHostPort (util.js:897:20)\n  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)\n' },

To reproduce, take a long list of User object ids (about 4,000 of them), then in a loop do a query.find by object ids on the User table.

**Comment by wangmengyan95** [comment]
Hi @arethtapslots, this is actually a backend/platform bug. We still use facebook bug tools to track backend bugs. We have noticed this issue and you can check the status of it [here](https://developers.facebook.com/bugs/777781325661733/). I will close this issue for now. Feel free to reopen it if you find this is related to our JS SDK.
