### ISSUE TITLE
Instance method `existed()` always returns `false` in CloudCode.

### ISSUE THREAD

**Issue by apersaud** [ParsePlatform/Parse-SDK-JS#69]
It seems that as part of removing Backbone from the framework, something went incorrectly in reporting the state of an object in the afterSave() hook. (Note that `isNew()` works as expected).

Steps to reproduct:
* Create a Parse app with a Table called 'Test' and a column field 'number'.
* Setup cloud code with SDK 1.6.7 with the following:
```javascript
Parse.Cloud.beforeSave("Test", function(request, response) {
	var record = request.object;
	console.log("Test isNew beforeSave?: " + record.isNew() );
  response.success();
});

Parse.Cloud.afterSave("Test", function(request){
     var record = request.object;
     console.log("Test existed afterSave?: " + record.existed() );
});
```

* Next add a new row and see the status of the `existed()` in the console. Then change the value of the 'number' column and see the status of `existed()`. The existed() method always seems to return false.

Example console output:
```
I2015-10-27T19:50:02.841Z]v20 before_save triggered for Test as master:
  Input: {"original":{"createdAt":"2015-10-23T06:38:06.072Z","number":6,"objectId":"pY6StCSBV0","updatedAt":"2015-10-27T19:47:34.635Z"},"update":{"number":20}}
  Result: Update changed to {"number":20}
I2015-10-27T19:50:02.879Z]Test isNew beforeSave?: false
I2015-10-27T19:50:02.886Z]v20 after_save triggered for Test as master:
  Input: {"object":{"createdAt":"2015-10-23T06:38:06.072Z","number":20,"objectId":"pY6StCSBV0","updatedAt":"2015-10-27T19:50:02.883Z"}}
  Result: Success
I2015-10-27T19:50:02.922Z]Test existed afterSave?: false
```

**Comment by andrewimm** [comment]
This is actually tied to the environment-loading code we use when initializing each Cloud Code sandbox, not the SDK itself. Still, I'll leave this task open until we've written and deployed a fix to cloud code.

**Comment by andrew8712** [comment]
I can confirm this as well. Please fix this ASAP as this is a very serious issue, which breaks the backend logic!!

**Comment by mnazemi** [comment]
This bug is already reported for Parse Cloud. Follow here: https://developers.facebook.com/bugs/1675561372679121/

**Comment by andrewimm** [comment]
This should be resolved.

**Comment by roddylindsay** [comment]
thanks Andrew!

On Mon, Dec 7, 2015 at 2:37 PM, Andrew Imm <notifications@github.com> wrote:

> This should be resolved.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParsePlatform/Parse-SDK-JS/issues/69#issuecomment-162691270>
> .
>



-- 
"Buy the ticket, take the ride."

**Comment by pmogilev** [comment]
checked it right now and and didn`t work Neither existed() nor isNew()

**Comment by akselect** [comment]
This started happening again. existed() is always returning true even for new objects.

**Comment by andrewimm** [comment]
@akselect note that the original issue was for exists() always retuning false, not always returning true.
I have a test app for this issue, and it continues to be working as expected. New objects have existed() returning false; previously-modified objects return true. Can you provide code that reproduces this error consistently?

**Comment by jugal-ionic** [comment]
I have tried for both request.object.existed() for afterSave & request.object.isNew() for beforeSave. both returning always true. I am using Latest SDK
deploy: v39 - Thursday January 7th 2016 at 5:10:32am (+0550) - Parse JavaScript SDK Version: 1.6.12
