### ISSUE TITLE
Promises are not rejected when the SDK fails to deserialize response

### ISSUE THREAD

**Issue by TylerBrock** [ParsePlatform/Parse-SDK-JS#71]
We are experiencing an issue where Parse promises are neither resolved or rejected when receiving a bad response body that is not able to be parsed as JSON.

Requests that are met with ETIMEDOUT, ECONNRESET, or ECONNREFUSED by api.parse.com seem to not reject the promise that initiated the request. I believe this to be because of Parse's non standard (A+ compliant) promise implementation.

This is causing us to **lose data in production**. Unfortunately, we are still on the 1.5.x SDK and not yet able to upgrade to the 1.6.x version so this is a large problem for us.

**Comment by andrewimm** [comment]
@TylerBrock this does not involve the Promises handling of errors; rather, it's related to the fact that the polyfill we use (node-xmlhttprequest) breaks the spec when dealing with network errors. If you dig into the code, you'll see that the exception-generating code does not occur within a `then()` block; instead it happens before any code resolves/rejects a Promise, and before any propagation of errors.

I just committed a fix for this to both retry on network failure, and report back a useful error on promise rejection. It should go out today in 1.6.8

**Comment by TylerBrock** [comment]
We can't use 1.6.x unfortunately.

**Comment by andrewimm** [comment]
Closing, as this should be resolved in 1.6.8
