### ISSUE TITLE
Parse JS SDK in Chrome Packed app

### ISSUE THREAD

**Issue by weiway** [ParsePlatform/Parse-SDK-JS#72]
Hi I need some help. I'm building a chrome app with parse.
It seems that Parse JS can't work with chrome packed app because ```window.localStorage``` is not available in chrome packed app. However, chrome app has ```chrome.storage.local``` api which serves the same functional wise with ```window.localStorage```. 
So what I am asking is if its possible to substitute ```window.localStorage``` with ```chrome.storage.local```. 

I know those two kind of storage works differently so it won't be easy.

**Comment by andrewimm** [comment]
As of version 1.6, the JS SDK has swappable controllers for all functionality. Behind the scenes, we swap out different Storage implementations for the browser, node, and React Native. If you look at the different Storage Controllers, I'm sure you could implement your own for a chrome extension; all you have to do then is call `Parse.CoreManager.setStorageController(YOUR_STORAGE_CONTROLLER)` before you initialize Parse

**Comment by weiway** [comment]
@andrewimm Could you give me a little hint on which part of ***Parse src code / doc*** I should be looking at in order to correctly implement chrome storage controllers to work with Parse

Chrome storage is all async, however i got Parse to store data successfully (the ```setItem``` function),
but no luck with ```getItem``` function.

To be more specific:
I checked the unminified Parse 1.6.7 source and found ```getItem``` and ```setItem``` functions will pass in a ```path```  parameter. 
My understanding on this ```path``` is that it works like a key. 

So in my ```setItem``` function  I store a ```{path,value}``` pair in Chrome local storage, and in my ```getItem``` function I query the storage with a given ```path``` . 
But ```getItem``` didn't work.

**Comment by andrewimm** [comment]
Look at https://github.com/ParsePlatform/Parse-SDK-JS/blob/master/src/StorageController.react-native.js , it implements an asynchronous storage interface using React Native's `AsyncStorage`.

You don't need to modify the SDK in any way. You can simply implement something that follows the Storage Controller interface, and then at runtime specify the module as your Storage Controller with the line I mentioned above.

**Comment by weiway** [comment]
@andrewimm **Thank you for your effort and it did work! I strongly recommend including those informations in Parse Javascript SDK Documentation**

**One thing I noticed:**
(This might be a separate issue) After I set my storage controller, when I call ```Parse.User.logIn``` **only for the first time**, it will not be executed correctly.

Here's a screen shot: 
As you can see, the first time ```Parse.User.login``` is called, it didn't return a promise as promised and threw an ```Uncaught TypeError```.

![screen shot 2015-10-28 at 4 07 56 pm](https://cloud.githubusercontent.com/assets/4580862/10806556/8665bc96-7d93-11e5-8541-c9a9bd5a1ee6.png)


If needed, I can provide my custom storage controller code and more details

**Comment by andrewimm** [comment]
If you go back through the code, you'll see that the static `logIn` call traces back to your implementation of `setItemAsync` not returning a Promise.

It would definitely be helpful to see your implementation of your storage controller.

**Comment by weiway** [comment]
Ok, here's my code, and also a screen shot of detailed error message;

```javascript
angular.module("myApp.Storage",[])
.factory("ChromeStorageController",function(){
    var store = {};//Object.create(null);
    store.async = 1;
    store.getItemAsync = function(path){
        var get = new Promise(function(resolve,reject){
            chrome.storage.local.get(path,function(data){
                //careful here: get return a key,value pair but we only need the value
                resolve(data[path]);
            });
        });
        return get;
    };
    store.setItemAsync = function(path,value){
        var set = new Promise(function(resolve,reject){
            var item = Object.create(null);
            item[path] = value;
            chrome.storage.local.set(item, function(err){
                if(err){
                    reject(err);
                }else{
                    resolve(value);
                }
            });
        });
        return set;
    };
    store.removeItemAsync = function(path){
        var remove = new Promise(function(resolve,reject){
            chrome.storage.local.remove(path,function(err){
                if(err){
                    reject(err);
                }else{
                    resolve();
                }
            })
        });
        return remove;
    };
    store.clear = function(){
        chrome.storage.local.clear();
    };
    return store;
})
```
And the screen shot:

![screen shot 2015-10-28 at 5 29 17 pm](https://cloud.githubusercontent.com/assets/4580862/10807167/f0b8c4e8-7d99-11e5-8040-850a521fa372.png)

**Comment by weiway** [comment]
@andrewimm 
I doubt this is because the Promise I'm using is different than the ParsePromise.
When the function was called for the first time, line 7698 ```controller.logIn``` returns a vanilla Promise object, which does not have ```_thenRunCallbacks```
But when the function was called for the second time, ```controller.logIn``` returns a ParsePromise object

**Comment by andrewimm** [comment]
Because of legacy support for backbone-style `success`/`error` callbacks, the internals of the SDK expect that Promises used within are overloaded with this `_thenRunCallbacks` method. There is a deprecation proposal in place, but until that time, I suggest you use `Parse.Promise` in your Controller. That should probably make this work.

I believe the difference between the first and second run is due to a cache.

**Comment by weiway** [comment]
@andrewimm using ```Parse.Promise```  **and its syntax** did solve the problem. Thank you!

**Comment by quorak** [comment]
just for the records.

```javascript
    function ChromeStorageController(){
        var store = {};//Object.create(null);
        store.async = 1;
        store.getItemAsync = function(path){
            var get = new Parse.Promise()
            chrome.storage.local.get(path,function(data){
                    //careful here: get return a key,value pair but we only need the value
                    get.resolve(data[path]);
            });
            return get;
        };
        store.setItemAsync = function(path,value){
            var set = new Parse.Promise()
            var item = Object.create(null);
            item[path] = value;
            chrome.storage.local.set(item, function(err){
                if(err){
                    set.reject(err);
                }else{
                    set.resolve(value);
                }
            });
            return set;
        };
        store.removeItemAsync = function(path){
            var remove = new Parse.Promise()
            chrome.storage.local.remove(path,function(err){
                if(err){
                    remove.reject(err);
                }else{
                    remove.resolve();
                }
            })
            return remove;
        };
        store.clear = function(){
            chrome.storage.local.clear();
        };
        return store;
    }

Parse.CoreManager.setStorageController(ChromeStorageController())
```
