### ISSUE TITLE
Problem with exporting database

### ISSUE THREAD

**Issue by benag** [ParsePlatform/Parse-SDK-JS#75]
I tried to export a simple schema from the data browser and got empty json files to a few of my classes.. is there a Bug?

**Comment by wangmengyan95** [comment]
Hi @benag, this repository only contains code for the SDK, so we only handle SDK issues here.
Your issue seems to be a website databroswer issue. This kind of issues is tracked through https://www.parse.com/help. Could you please file a bug there?
