### ISSUE TITLE
anonymoucely saved filed

### ISSUE THREAD

**Issue by martianmartian** [ParsePlatform/Parse-SDK-JS#76]
So I was playing with the "anymeme " demo app. Downloaded and added the appID and JS-ID to my cloud code, deployed; it started working. 
https://parse.com/tutorials  then anymeme

Then I realized I didn't have my appID and JS-ID added to front-end code. I know the images are saved directly from Parse front-end code, so I'm wondering, if I haven't put in my appID and JS-ID, where are these images saved to ? under whose account?....

It doesn't seem very secure this way.. any instruction/ explanation would help!

**Comment by andrewimm** [comment]
If you look at the code, you'll see that the backend initializes the Parse SDK with your keys when it renders the page.

Please reserve issues on this GitHub repository for the discussion JS SDK bugs or new features.
