### ISSUE TITLE
Anonymous user in the JS sdk

### ISSUE THREAD

**Issue by dorongutman** [ParsePlatform/Parse-SDK-JS#82]
I know you said you know that the JS SDK doesn't have anonymous users yet and that you're thinking about it, but it's a major pain not having it in JS - specifically because you claim "Parse and React, a Shared Chemistry" but it doesn't exist in the JS sdk, and does exist in both ios and android.

Can you at least please say when can we expect such anonymous users in the JS SDK ?

**Comment by creole** [comment]
+1

**Comment by ichagas** [comment]
+1

**Comment by andrewimm** [comment]
This should be possible to implement with the open source `parse-server`.
