### ISSUE TITLE
Cannot Query Sessions by sessionToken

### ISSUE THREAD

**Issue by jlalvarez18** [ParsePlatform/Parse-SDK-JS#83]
I've noticed it's impossible to query for Session objects by the `sessionToken`. It doesn't work for iOS, Node and even in the Parse data browser!

I've tried also using the master key and still no results. If I remove the sessionToken constraint I get all the sessions just fine.

The results returned are empty.

``` Javascript
var sessionToken ... // valid user session token
    
var query = new Parse.Query(Parse.Session)
query.equalTo('sessionToken', sessionToken)

query.find({ useMasterKey: true }).then(function(results) {
    response.send(results)
}, function(error) {
    response.send(error)
})
```

**Comment by andrewimm** [comment]
This is not supported for security reasons. If you want to get a Session object by its token, the REST endpoint is `/1/sessions/me`: https://parse.com/docs/rest/guide#sessions-retrieving-sessions

We provide a wrapper around this endpoint in the SDK, at `Parse.User.become()`
