### ISSUE TITLE
query.include not working

### ISSUE THREAD

**Issue by chrislewispac** [ParsePlatform/Parse-SDK-JS#87]
If I run the following query on my class I get the included surveryQuestion object and its attributes.

           var Answer = Parse.Object.extend("SurveyAnswer");
            var query = new Parse.Query(Answer);
            query.include("surveyQuestion");
            query.limit(100);
            return query.find();

However, if I perform the following query on the same table I still get the survey question but suddenly the event object (and/or the profile object) are not returned at all. Not just that the attributes aren't returned, there is no reference to their existence at all in the query.:

           var Answer = Parse.Object.extend("SurveyAnswer");
            var query = new Parse.Query(Answer);
            query.include("surveyQuestion");
            query.include("event");
           query.include("profile");
            query.limit(100);
            return query.find();

**Comment by wangmengyan95** [comment]
Hi @chrislewispac, in your case, could you provide the following information to us:
1. You use the SDK in cloud code, node or browser?
2. You SDK version.
We did have a bug related to include but we fixed that in 1.6.6, so make sure you use the latest version of SDK.

**Comment by chrislewispac** [comment]
Thanks wangmengyan95. I am using parse-angular-patch so I don't have the freedom to update to a version with breaking changes. I am still on 1.4.2 of the JS SDK.

This is entirely in the browser. It is functional on all other tables but only reproduced on this particular table. I will attempt a CloudCode implementation as well and let you know if it reproduces there.

**Comment by wangmengyan95** [comment]
Hi @chrislewispac, 1.4.2 is a pretty old version of SDK. I think CloudCode is definitely a good workaround for your case, since you can always use the latest version of our SDK. Let me know whether it works or not.

**Comment by chrislewispac** [comment]
Issue was reproduced attempting with cloud code function.

I get no reference of events or profile in this query. It is as if they don't exist. If I remove query.include I get their reference but not the actual object.

Parse.Cloud.define("getAnswers", function (request, response) {
    var query = new Parse.Query("SurveyAnswer");
    query.include("event");
    query.include("profile");
    query.include("surveyQuestion");
    query.find({
        success: function (results) {
            response.success(results);
        },
        error: function () {
            response.error("Failed");
        }
    });
});
