### ISSUE TITLE
Parse tables GUI  autoscrolls on click of columns outside of view

### ISSUE THREAD

**Issue by aimpointgolf** [ParsePlatform/Parse-SDK-JS#90]
Steps to Reproduce:
1. Log in and access Parse.com Core Database.
2. Access a table that has more columns than visible on default table.
3. Scroll to column that is outside of original view
4. Double click or single click to edit column outside of original view.

Expected Behavior:
Will highlight field and allow editing

Actual Behavior:
Scrolls to "original view" without ability to view and edit the cell in the column that was double-clicked.

**Comment by andrewimm** [comment]
Thank you for your feedback. Unfortunately, issues on this repository are for JS SDK bugs or features. Anything related to the Parse Platform or Parse.com should go through parse.com's bug reporting channels.
