### ISSUE TITLE
Document/Resolve backwards breaking issues in SDK 1.6

### ISSUE THREAD

**Issue by TylerBrock** [ParsePlatform/Parse-SDK-JS#95]
We've just slogged through upgrading our codebase from 1.5.x to 1.6.x and it was **not** fun.

Some things I would hope Parse does in the future with regards to this open source project:

- Consider branding a **complete re-write** of the SDK as a major version bump (2.0.0) so as to notify that this is not a drop in replacement that is adding a couple of features (what is normally appropriate for a minor version bump) or a set of bug fixes (what is normally appropriate for a patch version bump). Without that major signal, developers who don't have time to look into all of this might wrongfully assume that 1.5.x -> 1.6.x is a minor change for their application.

- Document or resolve backward breaking changes with respect to SDK behavior. Sure the API needs to move forward but take a look at #89, #91, etc... which take a fully functioning app and make it completely broken with respect to how Parse.Object (core functionality) is handled. Why aren't there tests for this to ensure the new and old SDK behave the same in this regard or at the very least documentation on how users should expect Parse.Object to behave? It is critical that this not change without warning if people are to trust this software.

**Comment by andrewimm** [comment]
@TylerBrock aside from the few minor features we made the decision to remove, the breaks you mention were not intended. We have a large set of internal integration tests we run against, but the SDK and its use cases are numerous, and we can't catch things that aren't in our tests. You can trust that with each of these fixes, we've augmented our test suite to make sure these cases are covered in the future.

As for the general set of changes, we've noted in the past that our versioning is tied to our API, not semver. Major version numbers are reserved for major breaking changes in the way the SDK manages objects and ultimately its interface with Parse. When we rewrote the SDK, we did so with the intent to maintain the behavior of all public APIs except the few we were publicly changing. If all we had done was to remove the few features we did (without rewriting under the hood), we feel that a minor version bump would have been justified. Granted, there have been a few bugs, but as I noted previously, we were only tripped up by the cases that were not already covered in our test suite. The majority of SDK users have seen absolutely no changes in the way they use the SDK from 1.5 to 1.6 and beyond.

**Comment by TylerBrock** [comment]
I hear you, but I also find it hard to believe that the situations I outlined are uncommon.

I'm only mentioning it because I think it will help the project. I've found a lot of people don't speak up and just move on.

**Comment by TylerBrock** [comment]
How can I help to get those issues resolved? Should I convert my examples to tests that fail the test suite?

**Comment by polerin** [comment]
Is there any update on #91? I see the other has been resolved.

**Comment by TylerBrock** [comment]
No, both are still open. Neither is resolved.

**Comment by TylerBrock** [comment]
@andrewimm as we start to see more and more people having the issues I've outlined is there a way we can revisit this?

**Comment by jeveloper** [comment]
I'd like add that Cloud Code modules were removed in 1.6 yet documentation still referred to that feature (which used to be awesome).
Also weird how parse tool (3.x) is incapable of using jssdk 1.6.12 .
At the moment of writing im seeing errors when attempting to deploy with NO explanation.
