### ISSUE TITLE
Parse.Cloud.define only with func arguments

### ISSUE THREAD

**Issue by oriSomething** [ParsePlatform/Parse-SDK-JS#96]
it might be silly, but it would be a nice to add the ability to define `cloud function` only with a function in the arguments. `Function` instances have `name` property which can be used instead of manually `name:string` argument. for example:
```js
function hello(req, res) {
 res.success('hello');
}
hello.name === 'hello'; // true

Parse.Cloud.define(hello);
```

it's only sugar. but named functions in JavaScript get nicer logs anyway

**Comment by andrewimm** [comment]
This is something that would be handled by Cloud Code, not the JS SDK. I'll look into seeing if this is something we can implement.

**Comment by andrewimm** [comment]
If you want to see this, it would make a good PR for the open source `parse-server`.
