### ISSUE TITLE
The observation value "[Object]" is not subscribable. Make sure you are returning the Query, and not fetching it yourself.

### ISSUE THREAD

**Issue by pauldd91** [ParsePlatform/Parse-SDK-JS#98]
I can't seem to be able to query Parse. I'm using the ParseReact and React packages. Here's my code:

![screen shot 2015-11-24 at 12 29 27 pm](https://cloud.githubusercontent.com/assets/3650761/11375041/18883b94-92a7-11e5-9358-b67423d4c81f.png)

I get a this error and undefined in the ```render() {}``` block for ```tweets``` object. Any lead on how to resolve this would be great
![screen shot 2015-11-24 at 12 28 49 pm](https://cloud.githubusercontent.com/assets/3650761/11375053/295262ba-92a7-11e5-8414-21b488036b13.png)

**Comment by TylerBrock** [comment]
Put parens around `new Parse.Query('Tweet')`.

**Comment by pauldd91** [comment]
Hey @TylerBrock, I did  as your suggested (and you're right about constructing the query outside the return value), however it still consoles out ```undefined``` meaning that somehow I can't get the instance to subscribe to ```tweets```

**Comment by TylerBrock** [comment]
Are there any tweets in Tweet to observe?

It seems like you have errors compiling your JS, you might want to drop this into your webpack config:

```js
  node: {
    fs: 'empty',
    child_process: 'empty',
    readline: 'empty'
  },
```

**Comment by pauldd91** [comment]
I have > 1.9k tweets in my parse core. I updated my webpack config but it still gives me the same error. 
Here's my updated code.
![screen shot 2015-11-24 at 11 56 04 pm](https://cloud.githubusercontent.com/assets/3650761/11388719/3659d6cc-9307-11e5-9e4b-e4a501f7542c.png)

[Full Code](https://github.com/pauldd91/herbert/blob/fetch-tweets/src/stores/Tweet/TweetCollection.js)

**Comment by pauldd91** [comment]
[Issue 140](https://github.com/ParsePlatform/ParseReact/issues/140)

**Comment by andrewimm** [comment]
The issue is that you are using two different versions of the Parse SDK.
`require('parse-react')` pulls in the normally-named `'parse'` npm module, but you're constructing promises with `'parse-node'`.
If you switch to using `require('parse')`, you'll be fine.
